# Format and save Supplementary Data Tables from raw data files.

Generates all supplementary data tables (see [results](results/)) except Supplementary Table 8, which is generated in [`Upset Plots.ipynb`](scripts/07_figures_tables/UpSet%20Plots.ipynb).

In [2]:
import os
import sys
import pandas as pd
import numpy as np
from scipy.stats import norm
!{sys.executable} -m pip install openpyxl

# Resolve repo root whether cwd is repo root, scripts/, or a stage subdirectory.
cwd = os.getcwd()
if os.path.basename(cwd) == "orb-selection":
    repo_root = cwd
elif os.path.basename(os.path.dirname(cwd)) == "orb-selection":
    repo_root = os.path.dirname(cwd)
elif os.path.basename(os.path.dirname(os.path.dirname(cwd))) == "orb-selection":
    repo_root = os.path.dirname(os.path.dirname(cwd))
else:
    repo_root = cwd

data = os.path.join(repo_root, "data")
results = os.path.join(repo_root, "results")

src_path = os.path.join(repo_root, "src")
stage03_path = os.path.join(repo_root, "scripts", "03_selection_tests")
stage04_path = os.path.join(repo_root, "scripts", "04_permulation_loss_dup")
for path in (src_path, stage03_path, stage04_path):
    if path not in sys.path:
        sys.path.insert(0, path)

print(f"Using src path: {src_path}")
print(f"Using stage-03 path: {stage03_path}")
print(f"Using stage-04 path: {stage04_path}")

# Import the modules from stage-03/
from hyphy_results_parser import (
    RelaxResult,
    BustedPhResult
)
from id_converter import convert_hogs_to_locs, get_ptep_description

pd.set_option('display.max_columns', None, 'display.max_rows', 20)

Requirement already satisfied: openpyxl in /Users/calvin/miniforge3/envs/orb-selection/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/calvin/miniforge3/envs/orb-selection/lib/python3.13/site-packages (from openpyxl) (2.0.0)
Using src path: /Users/calvin/orb-selection/src
Using stage-03 path: /Users/calvin/orb-selection/scripts/03_selection_tests
Using stage-04 path: /Users/calvin/orb-selection/scripts/04_permulation_loss_dup

In [3]:
%load_ext autoreload

In [6]:
def move_column(df, col_name, new_pos):
    cols = list(df.columns)
    cols.insert(new_pos, cols.pop(cols.index(col_name)))
    return df[cols]

## Hyphy Results

In [7]:
hyphy_results = os.path.join(repo_root, "results/hyphy_results_cache/")

In [8]:
# Load the saved RELAX results
relax_result = RelaxResult.load_from_pickle(str(hyphy_results + "relax_results.pkl"))
relax_result_fltrd = relax_result.filter_omega(10000)
relax_hits_df = relax_result_fltrd.get_significant_results()

In [9]:
relax_hits_df = move_column(relax_hits_df, 'result', 0)  # Move 'result' column to the front
relax_hits_df['foreground'] = 'non-orbweavers'
relax_hits_df = move_column(relax_hits_df, 'foreground', 1)  # Move 'foreground' column to the front
relax_hits_df

,result,foreground,p_value,k,LRT,MG94xREV_ω_reference,MG94xREV_ω_test,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,
N5.HOG0060863,relaxed,non-orbweavers,0.012709,0.263420,6.209242,0.195456,0.144789,0.000000e+00,0.815970,0.840297,0.000000,1.149850,0.184030,0.000000,0.815970,0.516571,0.000000,1.699052,0.184030,0.211607,0.312677
N5.HOG0034724,intensified,non-orbweavers,0.000000,2.987698,10349.318069,0.375229,0.323449,1.202761e-13,0.754140,0.015275,0.000000,4.630327,0.245860,0.000047,0.754140,0.246701,0.000000,1.670260,0.245860,1.138414,0.410686
N5.HOG0053197,relaxed,non-orbweavers,0.000100,0.176158,15.139150,0.184215,0.103955,0.000000e+00,0.869894,0.952362,0.000000,1.495308,0.130106,0.000000,0.869894,0.757993,0.000000,9.815145,0.130106,0.194549,1.277013
N5.HOG0063749,intensified,non-orbweavers,0.032893,1.309127,4.551324,0.000016,0.000013,5.684186e-06,0.896994,0.918852,0.055231,2.434837,0.047775,0.000098,0.896994,0.937399,0.055231,1.973385,0.047775,0.167079,0.146140
N5.HOG0038544,intensified,non-orbweavers,0.000053,1.096950,16.345614,0.634951,0.000007,4.630540e-02,0.000000,0.054062,1.000000,1.521564,0.000000,0.060753,0.000000,0.069965,1.000000,1.466153,0.000000,0.054062,0.069965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0033066,relaxed,non-orbweavers,0.000099,0.565229,15.160434,0.150521,0.122973,0.000000e+00,0.840632,0.770516,0.000000,2.508798,0.159368,0.000000,0.840632,0.630514,0.000000,5.090170,0.159368,0.399821,0.811209
N5.HOG0048453,relaxed,non-orbweavers,0.006537,0.879559,7.396064,0.036306,0.058095,0.000000e+00,0.721171,0.153698,0.278432,20.572784,0.000397,0.000000,0.721171,0.118931,0.278432,31.126266,0.000397,0.050967,0.045479
N5.HOG0056527,intensified,non-orbweavers,0.000000,11.817292,628.122463,0.294712,0.242411,0.000000e+00,0.816089,0.995427,0.153590,5719.136264,0.030321,0.000000,0.816089,0.999612,0.153590,2.079466,0.030321,173.565615,0.216583
N5.HOG0067687,intensified,non-orbweavers,0.004062,1.139227,8.255676,0.179429,0.166086,1.051487e-01,1.000000,0.140360,0.000000,1.285121,0.000000,0.138469,1.000000,0.178427,0.000000,1.246320,0.000000,0.105149,0.138469
N5.HOG0056679,intensified,non-orbweavers,0.000005,1.153741,20.784522,0.000028,0.000022,7.198906e-06,0.246805,0.102695,0.753195,1.005362,0.000000,0.000035,0.246805,0.139080,0.753195,1.004646,0.000000,0.077351,0.104763

In [11]:
relaxed_hogs_path = os.path.join(
    repo_root,
    "results/PREVIOUS_go_enrichment/before_tet_fix_sig_gene_ids/relaxed_hogs.txt"
)

relaxed_hogs_list = (
    pd.read_csv(relaxed_hogs_path, header=None)[0]
    .dropna()
    .astype(str)
    .str.strip()
)
relaxed_hogs_list = relaxed_hogs_list[relaxed_hogs_list != ""].tolist()

# overlap with HOG index in relax_hits_df
overlap_hogs = relax_hits_df[relax_hits_df['result']=="relaxed"].index.intersection(relaxed_hogs_list)

print(f"HOGs in file: {len(relaxed_hogs_list)}")
print(f"HOGs in relax_hits_df: {len(relax_hits_df[relax_hits_df['result']=='relaxed'].index)}")
print(f"Overlap: {len(overlap_hogs)}")
overlap_hogs.tolist()[:10]

HOGs in file: 491
HOGs in relax_hits_df: 405
Overlap: 119

['N5.HOG0053831',
 'N5.HOG0033222',
 'N5.HOG0054138',
 'N5.HOG0047052',
 'N5.HOG0064470',
 'N5.HOG0045177',
 'N5.HOG0049247',
 'N5.HOG0059269',
 'N5.HOG0067619',
 'N5.HOG0040013']

In [13]:
intensified_hogs_path = os.path.join(
    repo_root,
    "results/PREVIOUS_go_enrichment/before_tet_fix_sig_gene_ids/intensified_hogs.txt"
)

intensified_hogs_list = (
    pd.read_csv(intensified_hogs_path, header=None)[0]
    .dropna()
    .astype(str)
    .str.strip()
)
intensified_hogs_list = intensified_hogs_list[intensified_hogs_list != ""].tolist()

# overlap with HOG index in relax_hits_df
overlap_hogs = relax_hits_df[relax_hits_df['result']=="intensified"].index.intersection(intensified_hogs_list)

print(f"HOGs in file: {len(intensified_hogs_list)}")
print(f"HOGs in relax_hits_df: {len(relax_hits_df[relax_hits_df['result']=='intensified'].index)}")
print(f"Overlap: {len(overlap_hogs)}")
overlap_hogs.tolist()[:10]

HOGs in file: 938
HOGs in relax_hits_df: 737
Overlap: 246

['N5.HOG0038544',
 'N5.HOG0010637',
 'N5.HOG0054359',
 'N5.HOG0010662',
 'N5.HOG0063608',
 'N5.HOG0036636',
 'N5.HOG0029662',
 'N5.HOG0053477',
 'N5.HOG0024380',
 'N5.HOG0062581']

In [14]:
# Load the saved BUSTED-PH results
busted_ph_result = BustedPhResult.load_from_pickle(str(hyphy_results + "busted_ph_results.pkl"))
busted_ph_result_fltrd = busted_ph_result.filter_omega(10000)
busted_ph_hits_df = busted_ph_result_fltrd.get_significant_results()
busted_ph_hits_df['foreground'] = 'orbweavers'
busted_ph_hits_df = move_column(busted_ph_hits_df, 'foreground', 0)  # Move 'foreground' column to the front
busted_ph_hits_df.drop(columns=['result'], inplace=True)  # Drop result column
busted_ph_hits_df

/var/folders/50/5g9n3tts73d9t0l7x7fh2rx00000gp/T/ipykernel_68085/2871403343.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  busted_ph_hits_df['foreground'] = 'orbweavers'

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0027399,orbweavers,7.317358e-04,13.053888,0.500000,-5.188044,0.000000e+00,91.381079,0.000061,0.000028,0.000000,0.342811,0.283104,0.605572,4.819836,0.051617,0.000000,0.371896,0.129794,0.568777,2.031410,0.059327,0.420223,0.194342
N5.HOG0067687,orbweavers,1.004369e-02,7.815326,0.100755,3.203833,1.230178e-02,14.582833,0.179252,0.165886,0.071938,0.823210,0.637933,0.174763,32.915611,0.002027,0.000000,0.352128,0.170137,0.615790,1.807669,0.032082,0.237421,0.162762
N5.HOG0046830,orbweavers,2.882947e-08,33.337441,0.197147,1.861315,9.025339e-06,31.081779,0.016357,0.018601,0.002168,0.925907,0.165569,0.073707,146.613468,0.000386,0.010733,0.980653,0.024182,0.012755,1.409533,0.006592,0.070794,0.020126
N5.HOG0064451,orbweavers,4.321191e-02,4.896984,0.500000,0.000000,2.590683e-11,58.408424,0.000040,0.000027,0.020711,0.643359,0.223796,0.353431,6.376223,0.003211,0.000000,0.234975,0.056956,0.737757,1.000000,0.027268,0.112893,0.069287
N5.HOG0064007,orbweavers,1.627531e-02,6.849918,0.500000,0.000000,6.157777e-05,26.829322,0.064759,0.078682,0.007946,0.729061,0.041205,0.270505,44.880916,0.000434,0.000000,0.114812,0.019444,0.862158,0.817365,0.023030,0.036434,0.035587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0056667,orbweavers,2.675535e-08,33.486768,0.500000,0.000000,6.122469e-06,31.934101,0.144294,0.123302,0.130652,0.360202,0.131566,0.638211,201.708351,0.001587,0.016790,0.155692,0.041429,0.582231,0.379806,0.262077,0.451151,0.126274
N5.HOG0034239,orbweavers,4.028513e-02,5.037251,0.058608,4.287467,2.791839e-03,18.126612,0.249524,0.155437,0.000000,0.615736,0.281903,0.335040,2.695367,0.049224,0.000000,0.123728,0.038189,0.809145,1.454237,0.067127,0.227126,0.128520
N5.HOG0058337,orbweavers,2.474044e-03,10.617508,0.500000,-1122.359434,8.853982e-04,20.795438,0.000062,0.000064,0.000000,0.537250,0.318621,0.446978,6.111431,0.015771,0.000088,0.702471,0.727526,0.293963,201.648060,0.003566,0.238802,0.933030
N5.HOG0054210,orbweavers,9.359787e-05,17.166711,0.500000,0.000000,1.605552e-03,19.418947,0.135085,0.112956,0.098307,0.946483,0.380050,0.050937,253.879126,0.002580,0.041209,0.469748,0.099148,0.393377,0.346891,0.136875,0.767302,0.105841
N5.HOG0062926,orbweavers,4.490367e-04,14.030518,0.500000,0.000000,7.680415e-05,26.335720,0.166421,0.129859,0.007867,0.443931,0.179596,0.554423,55.364149,0.001646,0.000000,0.244007,0.045415,0.564038,0.262784,0.191956,0.194221,0.076059

In [15]:
busted_orb_hogs_path = os.path.join(
    repo_root,
    "results/PREVIOUS_go_enrichment/before_tet_fix_sig_gene_ids/busted_ph_orb_hogs.txt"
)

busted_orb_hogs_list = (
    pd.read_csv(busted_orb_hogs_path, header=None)[0]
    .dropna()
    .astype(str)
    .str.strip()
)
busted_orb_hogs_list = busted_orb_hogs_list[busted_orb_hogs_list != ""].tolist()

# overlap with HOG index in busted_ph_hits_df
overlap_hogs = busted_ph_hits_df.index.intersection(busted_orb_hogs_list)

print(f"HOGs in file: {len(busted_orb_hogs_list)}")
print(f"HOGs in busted_ph_hits_df: {len(busted_ph_hits_df.index)}")
print(f"Overlap: {len(overlap_hogs)}")
overlap_hogs.tolist()[:10]

HOGs in file: 96
HOGs in busted_ph_hits_df: 93
Overlap: 24

['N5.HOG0064007',
 'N5.HOG0037858',
 'N5.HOG0062008',
 'N5.HOG0068073',
 'N5.HOG0060652',
 'N5.HOG0056632',
 'N5.HOG0032852',
 'N5.HOG0060473',
 'N5.HOG0033769',
 'N5.HOG0061780']

In [16]:
# Load the saved BUSTED-PH-rev results
busted_ph_rev_result = BustedPhResult.load_from_pickle(str(hyphy_results + "busted_ph_rev_results.pkl"))
busted_ph_rev_result_fltrd = busted_ph_rev_result.filter_omega(10000)
busted_ph_rev_hits_df = busted_ph_rev_result_fltrd.get_significant_results()
busted_ph_rev_hits_df['foreground'] = 'non-orbweavers'
busted_ph_rev_hits_df = move_column(busted_ph_rev_hits_df, 'foreground', 0)  # Move 'foreground' column to the front
busted_ph_rev_hits_df.drop(columns=['result'], inplace=True)  # Drop result column
busted_ph_rev_hits_df

/var/folders/50/5g9n3tts73d9t0l7x7fh2rx00000gp/T/ipykernel_68085/1011142091.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  busted_ph_rev_hits_df['foreground'] = 'non-orbweavers'

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0059647,non-orbweavers,0.000000,199.312524,0.500000,0.000000,1.303733e-09,50.129547,0.214145,0.194163,0.012272,0.506622,0.327546,0.490094,25048.011234,0.003284,0.000007,0.491375,0.197839,0.442325,1.000000,0.066300,82.433873,0.153813
N5.HOG0059162,non-orbweavers,0.000334,14.624765,0.500000,0.000000,1.337493e-03,19.842840,0.055725,0.047507,0.000000,0.000853,0.049085,0.997870,222.963619,0.001277,0.012491,0.517452,0.054831,0.466754,1.000000,0.015794,0.333618,0.047850
N5.HOG0047848,non-orbweavers,0.000043,18.745455,0.500000,0.000000,9.557485e-04,20.619345,0.105105,0.161232,0.000000,0.701083,0.125313,0.298330,393.914065,0.000587,0.006878,0.868193,0.474539,0.131807,0.506917,0.000000,0.268548,0.068519
N5.HOG0063971,non-orbweavers,0.000000,102.747636,0.191702,1.917329,1.196849e-06,35.497771,0.170064,0.162002,0.000000,0.383219,0.230648,0.613126,71295.094259,0.003655,0.043728,0.303971,0.083198,0.603464,1.306522,0.092566,260.719634,0.184438
N5.HOG0060034,non-orbweavers,0.003962,9.675863,0.393941,0.476816,6.303230e-05,26.777215,0.114910,0.123684,0.000000,0.029057,0.040354,0.952268,1.981266,0.018675,0.000000,0.595994,0.104636,0.366482,1.094276,0.037524,0.075429,0.079409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0059302,non-orbweavers,0.000000,172.054793,0.147904,2.436096,0.000000e+00,150.891145,0.214680,0.138669,0.090953,0.925501,0.092234,0.055359,583.997366,0.019140,0.055118,0.835128,0.055638,0.115320,1.519702,0.049552,11.267098,0.127751
N5.HOG0069361,non-orbweavers,0.000000,86.252659,0.500000,0.000000,2.216637e-08,44.094013,0.000025,0.000017,0.000000,0.560835,0.239895,0.430389,31096.071854,0.008776,0.000000,0.550003,0.064982,0.317284,0.834182,0.132713,273.009285,0.131325
N5.HOG0022097,non-orbweavers,0.000385,14.340682,0.416242,0.366682,5.013023e-11,57.018385,0.206016,0.190054,0.002126,0.716543,0.565311,0.282970,334.274233,0.000486,0.001392,0.807633,0.655649,0.192054,30.132889,0.000313,0.324074,0.136486
N5.HOG0066569,non-orbweavers,0.000091,17.218049,0.500000,0.000000,5.063692e-07,37.363624,0.015114,0.006381,0.009473,0.996193,1.000000,0.003242,121.156902,0.000566,0.002831,0.985232,0.045644,0.011594,0.851932,0.003174,0.081197,0.006022
N5.HOG0063677,non-orbweavers,0.000004,23.454576,0.499154,0.003385,1.559421e-02,14.002394,0.164763,0.198686,0.000372,0.642887,0.183646,0.356496,433890.703824,0.000617,0.004784,0.679048,0.159223,0.296341,1.193221,0.024611,267.701150,0.079799

In [17]:
busted_nonorb_hogs_path = os.path.join(
    repo_root,
    "results/PREVIOUS_go_enrichment/before_tet_fix_sig_gene_ids/busted_ph_nonorb_hogs.txt"
)

busted_nonorb_hogs_list = (
    pd.read_csv(busted_nonorb_hogs_path, header=None)[0]
    .dropna()
    .astype(str)
    .str.strip()
)
busted_nonorb_hogs_list = busted_nonorb_hogs_list[busted_nonorb_hogs_list != ""].tolist()

# overlap with HOG index in busted_ph_rev_hits_df
overlap_hogs = busted_ph_rev_hits_df.index.intersection(busted_nonorb_hogs_list)

print(f"HOGs in file: {len(busted_nonorb_hogs_list)}")
print(f"HOGs in busted_ph_rev_hits_df: {len(busted_ph_rev_hits_df.index)}")
print(f"Overlap: {len(overlap_hogs)}")
overlap_hogs.tolist()[:10]

HOGs in file: 196
HOGs in busted_ph_rev_hits_df: 235
Overlap: 88

['N5.HOG0047848',
 'N5.HOG0063971',
 'N5.HOG0035032',
 'N5.HOG0064953',
 'N5.HOG0044950',
 'N5.HOG0038057',
 'N5.HOG0066290',
 'N5.HOG0045696',
 'N5.HOG0057813',
 'N5.HOG0066882']

In [18]:
all_busted_hits_df = pd.concat([busted_ph_hits_df, busted_ph_rev_hits_df])
all_busted_hits_df

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0027399,orbweavers,7.317358e-04,13.053888,0.500000,-5.188044,0.000000e+00,91.381079,0.000061,0.000028,0.000000,0.342811,0.283104,0.605572,4.819836,0.051617,0.000000,0.371896,0.129794,0.568777,2.031410,0.059327,0.420223,0.194342
N5.HOG0067687,orbweavers,1.004369e-02,7.815326,0.100755,3.203833,1.230178e-02,14.582833,0.179252,0.165886,0.071938,0.823210,0.637933,0.174763,32.915611,0.002027,0.000000,0.352128,0.170137,0.615790,1.807669,0.032082,0.237421,0.162762
N5.HOG0046830,orbweavers,2.882947e-08,33.337441,0.197147,1.861315,9.025339e-06,31.081779,0.016357,0.018601,0.002168,0.925907,0.165569,0.073707,146.613468,0.000386,0.010733,0.980653,0.024182,0.012755,1.409533,0.006592,0.070794,0.020126
N5.HOG0064451,orbweavers,4.321191e-02,4.896984,0.500000,0.000000,2.590683e-11,58.408424,0.000040,0.000027,0.020711,0.643359,0.223796,0.353431,6.376223,0.003211,0.000000,0.234975,0.056956,0.737757,1.000000,0.027268,0.112893,0.069287
N5.HOG0064007,orbweavers,1.627531e-02,6.849918,0.500000,0.000000,6.157777e-05,26.829322,0.064759,0.078682,0.007946,0.729061,0.041205,0.270505,44.880916,0.000434,0.000000,0.114812,0.019444,0.862158,0.817365,0.023030,0.036434,0.035587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0059302,non-orbweavers,0.000000e+00,172.054793,0.147904,2.436096,0.000000e+00,150.891145,0.214680,0.138669,0.090953,0.925501,0.092234,0.055359,583.997366,0.019140,0.055118,0.835128,0.055638,0.115320,1.519702,0.049552,11.267098,0.127751
N5.HOG0069361,non-orbweavers,0.000000e+00,86.252659,0.500000,0.000000,2.216637e-08,44.094013,0.000025,0.000017,0.000000,0.560835,0.239895,0.430389,31096.071854,0.008776,0.000000,0.550003,0.064982,0.317284,0.834182,0.132713,273.009285,0.131325
N5.HOG0022097,non-orbweavers,3.845303e-04,14.340682,0.416242,0.366682,5.013023e-11,57.018385,0.206016,0.190054,0.002126,0.716543,0.565311,0.282970,334.274233,0.000486,0.001392,0.807633,0.655649,0.192054,30.132889,0.000313,0.324074,0.136486
N5.HOG0066569,non-orbweavers,9.122589e-05,17.218049,0.500000,0.000000,5.063692e-07,37.363624,0.015114,0.006381,0.009473,0.996193,1.000000,0.003242,121.156902,0.000566,0.002831,0.985232,0.045644,0.011594,0.851932,0.003174,0.081197,0.006022
N5.HOG0063677,non-orbweavers,4.035280e-06,23.454576,0.499154,0.003385,1.559421e-02,14.002394,0.164763,0.198686,0.000372,0.642887,0.183646,0.356496,433890.703824,0.000617,0.004784,0.679048,0.159223,0.296341,1.193221,0.024611,267.701150,0.079799

In [19]:
busted_hits_locs = convert_hogs_to_locs(all_busted_hits_df, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
busted_hits_locs_fltrd = busted_hits_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
busted_hits_locs_fltrd = move_column(busted_hits_locs_fltrd, 'HOG', 0)
busted_hits_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
busted_hits_locs_fltrd

Processing HOGs: 100%|██████████| 328/328 [00:00<00:00, 4415.96it/s]

,HOG,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0027399,orbweavers,7.317358e-04,13.053888,0.500000,-5.188044,0.000000e+00,91.381079,0.000061,0.000028,0.000000,0.342811,0.283104,0.605572,4.819836,0.051617,0.000000,0.371896,0.129794,0.568777,2.031410,0.059327,0.420223,0.194342,129224947,GO:0000976 [Name: transcription regulatory reg...,uncharacterized LOC129224947
1,N5.HOG0067687,orbweavers,1.004369e-02,7.815326,0.100755,3.203833,1.230178e-02,14.582833,0.179252,0.165886,0.071938,0.823210,0.637933,0.174763,32.915611,0.002027,0.000000,0.352128,0.170137,0.615790,1.807669,0.032082,0.237421,0.162762,NaN,NaN,NaN
2,N5.HOG0046830,orbweavers,2.882947e-08,33.337441,0.197147,1.861315,9.025339e-06,31.081779,0.016357,0.018601,0.002168,0.925907,0.165569,0.073707,146.613468,0.000386,0.010733,0.980653,0.024182,0.012755,1.409533,0.006592,0.070794,0.020126,129225235,GO:0005737 [Name: cytoplasm]; GO:0051603 [Name...,E3 ubiquitin-protein ligase RNF123-like
3,N5.HOG0064451,orbweavers,4.321191e-02,4.896984,0.500000,0.000000,2.590683e-11,58.408424,0.000040,0.000027,0.020711,0.643359,0.223796,0.353431,6.376223,0.003211,0.000000,0.234975,0.056956,0.737757,1.000000,0.027268,0.112893,0.069287,129217593,GO:0004345 [Name: glucose-6-phosphate dehydrog...,glucose-6-phosphate 1-dehydrogenase-like
4,N5.HOG0064007,orbweavers,1.627531e-02,6.849918,0.500000,0.000000,6.157777e-05,26.829322,0.064759,0.078682,0.007946,0.729061,0.041205,0.270505,44.880916,0.000434,0.000000,0.114812,0.019444,0.862158,0.817365,0.023030,0.036434,0.035587,129230660,GO:0017147 [Name: Wnt-protein binding]; GO:009...,secreted frizzled-related protein 5-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,N5.HOG0059302,non-orbweavers,0.000000e+00,172.054793,0.147904,2.436096,0.000000e+00,150.891145,0.214680,0.138669,0.090953,0.925501,0.092234,0.055359,583.997366,0.019140,0.055118,0.835128,0.055638,0.115320,1.519702,0.049552,11.267098,0.127751,129222734,-,zinc finger MYND domain-containing protein 19-...
322,N5.HOG0069361,non-orbweavers,0.000000e+00,86.252659,0.500000,0.000000,2.216637e-08,44.094013,0.000025,0.000017,0.000000,0.560835,0.239895,0.430389,31096.071854,0.008776,0.000000,0.550003,0.064982,0.317284,0.834182,0.132713,273.009285,0.131325,129219392,-,uncharacterized LOC129219392
323,N5.HOG0022097,non-orbweavers,3.845303e-04,14.340682,0.416242,0.366682,5.013023e-11,57.018385,0.206016,0.190054,0.002126,0.716543,0.565311,0.282970,334.274233,0.000486,0.001392,0.807633,0.655649,0.192054,30.132889,0.000313,0.324074,0.136486,129219189,GO:0005737 [Name: cytoplasm]; GO:0007052 [Name...,transforming acidic coiled-coil-containing pro...
324,N5.HOG0066569,non-orbweavers,9.122589e-05,17.218049,0.500000,0.000000,5.063692e-07,37.363624,0.015114,0.006381,0.009473,0.996193,1.000000,0.003242,121.156902,0.000566,0.002831,0.985232,0.045644,0.011594,0.851932,0.003174,0.081197,0.006022,129230806,GO:0003924 [Name: GTPase activity]; GO:0010506...,Ras-related GTP binding A/B
325,N5.HOG0063677,non-orbweavers,4.035280e-06,23.454576,0.499154,0.003385,1.559421e-02,14.002394,0.164763,0.198686,0.000372,0.642887,0.183646,0.356496,433890.703824,0.000617,0.004784,0.679048,0.159223,0.296341,1.193221,0.024611,267.701150,0.079799,129233742,GO:0006457 [Name: protein folding]; GO:0000209...,RING-type E3 ubiquitin-protein ligase PPIL2-like

In [20]:
%autoreload 2
busted_df = get_ptep_description(busted_hits_locs_fltrd)
busted_df

,HOG,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
0,N5.HOG0027399,orbweavers,7.317358e-04,13.053888,0.500000,-5.188044,0.000000e+00,91.381079,0.000061,0.000028,0.000000,0.342811,0.283104,0.605572,4.819836,0.051617,0.000000,0.371896,0.129794,0.568777,2.031410,0.059327,0.420223,0.194342,129224947,GO:0000976 [Name: transcription regulatory reg...,uncharacterized LOC129224947,uncharacterized protein isoform X2
1,N5.HOG0067687,orbweavers,1.004369e-02,7.815326,0.100755,3.203833,1.230178e-02,14.582833,0.179252,0.165886,0.071938,0.823210,0.637933,0.174763,32.915611,0.002027,0.000000,0.352128,0.170137,0.615790,1.807669,0.032082,0.237421,0.162762,NaN,NaN,NaN,trithorax group protein osa
2,N5.HOG0046830,orbweavers,2.882947e-08,33.337441,0.197147,1.861315,9.025339e-06,31.081779,0.016357,0.018601,0.002168,0.925907,0.165569,0.073707,146.613468,0.000386,0.010733,0.980653,0.024182,0.012755,1.409533,0.006592,0.070794,0.020126,129225235,GO:0005737 [Name: cytoplasm]; GO:0051603 [Name...,E3 ubiquitin-protein ligase RNF123-like,E3 ubiquitin-protein ligase RNF123 isoform X1
3,N5.HOG0064451,orbweavers,4.321191e-02,4.896984,0.500000,0.000000,2.590683e-11,58.408424,0.000040,0.000027,0.020711,0.643359,0.223796,0.353431,6.376223,0.003211,0.000000,0.234975,0.056956,0.737757,1.000000,0.027268,0.112893,0.069287,129217593,GO:0004345 [Name: glucose-6-phosphate dehydrog...,glucose-6-phosphate 1-dehydrogenase-like,glucose-6-phosphate 1-dehydrogenase X
4,N5.HOG0064007,orbweavers,1.627531e-02,6.849918,0.500000,0.000000,6.157777e-05,26.829322,0.064759,0.078682,0.007946,0.729061,0.041205,0.270505,44.880916,0.000434,0.000000,0.114812,0.019444,0.862158,0.817365,0.023030,0.036434,0.035587,129230660,GO:0017147 [Name: Wnt-protein binding]; GO:009...,secreted frizzled-related protein 5-like,secreted frizzled-related protein 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,N5.HOG0059302,non-orbweavers,0.000000e+00,172.054793,0.147904,2.436096,0.000000e+00,150.891145,0.214680,0.138669,0.090953,0.925501,0.092234,0.055359,583.997366,0.019140,0.055118,0.835128,0.055638,0.115320,1.519702,0.049552,11.267098,0.127751,129222734,-,zinc finger MYND domain-containing protein 19-...,zinc finger MYND domain-containing protein 19 ...
322,N5.HOG0069361,non-orbweavers,0.000000e+00,86.252659,0.500000,0.000000,2.216637e-08,44.094013,0.000025,0.000017,0.000000,0.560835,0.239895,0.430389,31096.071854,0.008776,0.000000,0.550003,0.064982,0.317284,0.834182,0.132713,273.009285,0.131325,129219392,-,uncharacterized LOC129219392,uncharacterized protein
323,N5.HOG0022097,non-orbweavers,3.845303e-04,14.340682,0.416242,0.366682,5.013023e-11,57.018385,0.206016,0.190054,0.002126,0.716543,0.565311,0.282970,334.274233,0.000486,0.001392,0.807633,0.655649,0.192054,30.132889,0.000313,0.324074,0.136486,129219189,GO:0005737 [Name: cytoplasm]; GO:0007052 [Name...,transforming acidic coiled-coil-containing pro...,transforming acidic coiled-coil-containing pro...
324,N5.HOG0066569,non-orbweavers,9.122589e-05,17.218049,0.500000,0.000000,5.063692e-07,37.363624,0.015114,0.006381,0.009473,0.996193,1.000000,0.003242,121.156902,0.000566,0.002831,0.985232,0.045644,0.011594,0.851932,0.003174,0.081197,0.006022,129230806,GO:0003924 [Name: GTPase activity]; GO:0010506...,Ras-related GTP binding A/B,ras-related GTP-binding protein A
325,N5.HOG0063677,non-orbweavers,4.035280e-06,23.454576,0.499154,0.003385,1.559421e-02,14.002394,0.164763,0.198686,0.000372,0.642887,0.183646,0.356496,433890.703824,0.000617,0.004784,0.679048,0.159223,0.296341,1.193221,0.024611,267.701150,0.079799,129233742,GO:0006457 [Name: protein folding]; GO:0000209...,RING-type E3 ubiquitin-protein ligase PPIL2-like,RING-type E3 ubiquitin-protein ligase PPIL2

In [41]:
busted_df.to_excel(os.path.join(repo_root, "results/Supplementary_Table_4_BUSTED_PH.xlsx"), index=False)

In [22]:
relax_hits_locs = convert_hogs_to_locs(relax_hits_df, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
relax_hits_locs_fltrd = relax_hits_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
relax_hits_locs_fltrd = move_column(relax_hits_locs_fltrd, 'HOG', 0)
relax_hits_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
relax_df = get_ptep_description(relax_hits_locs_fltrd)
relax_df

Processing HOGs: 100%|██████████| 1142/1142 [00:00<00:00, 52880.27it/s]

,HOG,result,foreground,p_value,k,LRT,MG94xREV_ω_reference,MG94xREV_ω_test,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
0,N5.HOG0060863,relaxed,non-orbweavers,0.012709,0.263420,6.209242,0.195456,0.144789,0.000000e+00,0.815970,0.840297,0.000000,1.149850,0.184030,0.000000,0.815970,0.516571,0.000000,1.699052,0.184030,0.211607,0.312677,129221600,GO:0004377 [Name: GDP-Man:Man3GlcNAc2-PP-Dol a...,"GDP-Man:Man(3)GlcNAc(2)-PP-Dol alpha-1,2-manno...","GDP-Man:Man(3)GlcNAc(2)-PP-Dol alpha-1,2-manno..."
1,N5.HOG0034724,intensified,non-orbweavers,0.000000,2.987698,10349.318069,0.375229,0.323449,1.202761e-13,0.754140,0.015275,0.000000,4.630327,0.245860,0.000047,0.754140,0.246701,0.000000,1.670260,0.245860,1.138414,0.410686,NaN,NaN,NaN,proclotting enzyme isoform X1
2,N5.HOG0053197,relaxed,non-orbweavers,0.000100,0.176158,15.139150,0.184215,0.103955,0.000000e+00,0.869894,0.952362,0.000000,1.495308,0.130106,0.000000,0.869894,0.757993,0.000000,9.815145,0.130106,0.194549,1.277013,129220170,GO:0005634 [Name: nucleus]; GO:0032502 [Name: ...,molecular chaperone MKKS-like,chromatin accessibility complex protein 1
3,N5.HOG0063749,intensified,non-orbweavers,0.032893,1.309127,4.551324,0.000016,0.000013,5.684186e-06,0.896994,0.918852,0.055231,2.434837,0.047775,0.000098,0.896994,0.937399,0.055231,1.973385,0.047775,0.167079,0.146140,129230607,-,TM2 domain-containing protein 2 amaretto,TM2 domain-containing protein 2
4,N5.HOG0038544,intensified,non-orbweavers,0.000053,1.096950,16.345614,0.634951,0.000007,4.630540e-02,0.000000,0.054062,1.000000,1.521564,0.000000,0.060753,0.000000,0.069965,1.000000,1.466153,0.000000,0.054062,0.069965,NaN,NaN,NaN,frizzled-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1137,N5.HOG0033066,relaxed,non-orbweavers,0.000099,0.565229,15.160434,0.150521,0.122973,0.000000e+00,0.840632,0.770516,0.000000,2.508798,0.159368,0.000000,0.840632,0.630514,0.000000,5.090170,0.159368,0.399821,0.811209,129217093,"GO:0016757 [Name: transferase activity, transf...",glycogenin-1-like,glycogenin-1
1138,N5.HOG0048453,relaxed,non-orbweavers,0.006537,0.879559,7.396064,0.036306,0.058095,0.000000e+00,0.721171,0.153698,0.278432,20.572784,0.000397,0.000000,0.721171,0.118931,0.278432,31.126266,0.000397,0.050967,0.045479,129227394,GO:0005634 [Name: nucleus]; GO:0004725 [Name: ...,eya transcriptional coactivator and phosphatase 2,eyes absent homolog 1 isoform X1
1139,N5.HOG0056527,intensified,non-orbweavers,0.000000,11.817292,628.122463,0.294712,0.242411,0.000000e+00,0.816089,0.995427,0.153590,5719.136264,0.030321,0.000000,0.816089,0.999612,0.153590,2.079466,0.030321,173.565615,0.216583,129230010,-,uncharacterized LOC129230010,uncharacterized protein isoform X1
1140,N5.HOG0067687,intensified,non-orbweavers,0.004062,1.139227,8.255676,0.179429,0.166086,1.051487e-01,1.000000,0.140360,0.000000,1.285121,0.000000,0.138469,1.000000,0.178427,0.000000,1.246320,0.000000,0.105149,0.138469,NaN,NaN,NaN,trithorax group protein osa
1141,N5.HOG0056679,intensified,non-orbweavers,0.000005,1.153741,20.784522,0.000028,0.000022,7.198906e-06,0.246805,0.102695,0.753195,1.005362,0.000000,0.000035,0.246805,0.139080,0.753195,1.004646,0.000000,0.077351,0.104763,129233134,GO:0005506 [Name: iron ion binding]; GO:001670...,ecdysone 20-monooxygenase-like,ecdysone 20-monooxygenase

In [23]:
relax_df.to_excel(os.path.join(repo_root, "results/Supplementary_Table_3_RELAX.xlsx"), index=False)

## Permutation test results

before fixing tetragnathids

In [24]:
%autoreload 2
perm_test_results_dir = os.path.join(repo_root, "results/odds_ratio_test/Results_Apr16/Run1_occ_30-88_10000x_all_orb/")
perm_results_old = pd.read_csv(os.path.join(perm_test_results_dir, "fltrd_hits.csv"), index_col="HOG")

perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_fg"), "Loss more likely in orb-weavers", None)
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_bg"), "Loss more likely in non-orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("dup_fg"), "Duplication more likely in orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("dup_bg"), "Duplication more likely in non-orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_bg"), "Loss more likely in orb-weavers, duplication more likely in non-orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_fg"), "Loss more likely in non-orb-weavers, duplication more likely in orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_fg"), "Loss more likely in orb-weavers, duplication more likely in orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_bg"), "Loss more likely in non-orb-weavers, duplication more likely in non-orb-weavers", perm_results_old["Result"])

perm_results_old = move_column(perm_results_old, "Result", 0)  # Move 'Result' column to the front
perm_results_old["LOR outside permuted avg thresholds"] = np.where(perm_results_old["Significant by avgd thresholds"].notnull(), "Yes", "No")
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_fg, dup_bg")), "Yes for both tests", perm_results_old["LOR outside permuted avg thresholds"])

perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_bg, dup_fg")), "Yes for both tests", perm_results_old["LOR outside permuted avg thresholds"])


perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_fg, dup_fg")), "Yes for both tests", perm_results_old["LOR outside permuted avg thresholds"])


perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_bg, dup_bg")), "Yes for both tests", perm_results_old["LOR outside permuted avg thresholds"])


perm_results_old = move_column(perm_results_old, "LOR outside permuted avg thresholds", 4)  # Move 'LOR outside permuted avg thresholds' column to the front
perm_results_old = perm_results_old.drop(columns=["Significant by avgd thresholds", "Significant by permulation"])
perm_results_old = perm_results_old.rename(columns={
    "P-value loss more likely in fg": "P-value, loss more likely in orb-weavers", 
    "P-value loss more likely in bg": "P-value, loss more likely in non-orb-weavers", 
    "P-value duplication more likely in fg": "P-value, duplication more likely in orb-weavers", 
    "P-value duplication more likely in bg": "P-value, duplication more likely in non-orb-weavers", 
    })
perm_results_old

,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers"
HOG,,,,,,,,,
N5.HOG0001041,Loss more likely in orb-weavers,46,2.288042,-0.281735,No,0.0038,0.9962,0.5328,0.4672
N5.HOG0001609,Loss more likely in non-orb-weavers,49,-2.841587,2.391485,No,0.9605,0.0395,0.0747,0.9253
N5.HOG0001627,"Loss more likely in orb-weavers, duplication m...",33,2.048043,-4.020457,No for loss; yes for duplication,0.0449,0.9551,0.9745,0.0253
N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.823601,1.854638,Yes,0.9996,0.0004,0.3311,0.6686
N5.HOG0002072,Loss more likely in orb-weavers,52,3.473733,-0.762726,Yes,0.0108,0.9892,0.7989,0.2011
...,...,...,...,...,...,...,...,...,...
N5.HOG0073114,Loss more likely in orb-weavers,36,1.310443,-1.206534,No,0.0218,0.9782,0.7961,0.2038
N5.HOG0073157,Loss more likely in non-orb-weavers,34,-3.186391,1.988284,Yes,0.9576,0.0424,0.1151,0.8846
N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.038058,0.724732,No,0.9929,0.0071,0.1394,0.8606
N5.HOG0073251,Loss more likely in non-orb-weavers,33,-3.434295,1.656853,Yes,0.9866,0.0134,0.2178,0.7822
N5.HOG0073526,Loss more likely in non-orb-weavers,31,-2.277030,1.982725,No,0.9679,0.0321,0.1323,0.8675

Reformat results table

In [25]:
%autoreload 2
perm_test_results_dir = os.path.join(repo_root, "results/odds_ratio_test/Results_Jul22/Run1_occ_30-88_10000x/")
perm_results = pd.read_csv(os.path.join(perm_test_results_dir, "fltrd_hits.csv"), index_col="HOG")

perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg"), "Loss more likely in orb-weavers", None)
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg"), "Loss more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("dup_fg"), "Duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("dup_bg"), "Duplication more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg"), "Loss more likely in orb-weavers, duplication more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg"), "Loss more likely in non-orb-weavers, duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg"), "Loss more likely in orb-weavers, duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg"), "Loss more likely in non-orb-weavers, duplication more likely in non-orb-weavers", perm_results["Result"])

perm_results = move_column(perm_results, "Result", 0)  # Move 'Result' column to the front
perm_results["LOR outside permuted avg thresholds"] = np.where(perm_results["Significant by avgd thresholds"].notnull(), "Yes", "No")
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg, dup_bg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])

perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg, dup_fg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg, dup_fg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg, dup_bg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results = move_column(perm_results, "LOR outside permuted avg thresholds", 4)  # Move 'LOR outside permuted avg thresholds' column to the front
perm_results = perm_results.drop(columns=["Significant by avgd thresholds", "Significant by permulation"])
perm_results = perm_results.rename(columns={
    "P-value loss more likely in fg": "P-value, loss more likely in orb-weavers", 
    "P-value loss more likely in bg": "P-value, loss more likely in non-orb-weavers", 
    "P-value duplication more likely in fg": "P-value, duplication more likely in orb-weavers", 
    "P-value duplication more likely in bg": "P-value, duplication more likely in non-orb-weavers", 
    })
perm_results

,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers"
HOG,,,,,,,,,
N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202
N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127
N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880
N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964
N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416
...,...,...,...,...,...,...,...,...,...
N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887
N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850
N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940
N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296
N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558

In [26]:
# intersection of indices
common_idx = perm_results.index.intersection(perm_results_old.index)
intersection_df = perm_results.loc[common_idx]

# quick summary
print(f"Common HOGs: {len(common_idx)}")
intersection_df.head()

Common HOGs: 999

,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers"
HOG,,,,,,,,,
N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202
N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127
N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880
N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964
N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416

In [27]:
%autoreload 2
perm_locs = convert_hogs_to_locs(perm_results, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
perm_locs_filtered = perm_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
perm_locs_filtered = move_column(perm_locs_filtered, 'HOG', 0)
perm_locs_filtered.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
perm_locs_filtered

Processing HOGs: 100%|██████████| 1482/1482 [00:00<00:00, 71487.24it/s]

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202,NaN,NaN,NaN
1,N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127,NaN,NaN,NaN
2,N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880,129233975,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like
3,N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964,129217362,GO:0008010 [Name: structural constituent of ch...,proteoglycan 4-like
4,N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416,129217825,GO:0008010 [Name: structural constituent of ch...,cuticle protein-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887,NaN,NaN,NaN
1478,N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850,NaN,NaN,NaN
1479,N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940,129221249,-,cuticle protein 38-like
1480,N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296,NaN,NaN,NaN
1481,N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558,NaN,NaN,NaN

In [28]:
%autoreload 2
perm_df = get_ptep_description(perm_locs_filtered)
perm_df

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
0,N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202,NaN,NaN,NaN,gastrula zinc finger protein XlCGF7.1
1,N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127,NaN,NaN,NaN,speckle-type POZ protein
2,N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880,129233975,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like,cuticle protein 10.9
3,N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964,129217362,GO:0008010 [Name: structural constituent of ch...,proteoglycan 4-like,uncharacterized protein
4,N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416,129217825,GO:0008010 [Name: structural constituent of ch...,cuticle protein-like,cuticle protein 10.9-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887,NaN,NaN,NaN,uncharacterized protein
1478,N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850,NaN,NaN,NaN,DNA mismatch repair protein Mlh3
1479,N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940,129221249,-,cuticle protein 38-like,cuticle protein 63-like
1480,N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296,NaN,NaN,NaN,NO_HIT
1481,N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558,NaN,NaN,NaN,NO_HIT

In [42]:
perm_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_5_OddsRatioTest.xlsx'), index=False)

In [43]:
previous_interesting = pd.read_csv(os.path.join(repo_root, 'data/interesting_hits.txt'), header=None, names=['HOG'])

In [44]:
perm_previous_interesting_df = perm_df[perm_df['HOG'].isin(previous_interesting['HOG'])]
perm_previous_interesting_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_6_OddsRatioTest_interesting_hits.xlsx'), index=False)
perm_previous_interesting_df

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
43,N5.HOG0007453,Loss more likely in orb-weavers,50,1.946870,-1.544702,No,0.0165,0.9835,0.9383,0.0617,129216356,GO:0043005 [Name: neuron projection],lachesin-like,lachesin
113,N5.HOG0014159,Duplication more likely in orb-weavers,78,0.169513,2.093720,No,0.3622,0.6378,0.0394,0.9606,129217691,GO:0005109 [Name: frizzled binding]; GO:000557...,protein Wnt-16-like,protein Wnt-16-like precursor
175,N5.HOG0018539,Loss more likely in non-orb-weavers,84,-1.480659,0.395499,No,0.9706,0.0294,0.3609,0.6391,129230744,GO:0005737 [Name: cytoplasm]; GO:0097320 [Name...,protein kinase C and casein kinase substrate i...,protein kinase C and casein kinase substrate i...
228,N5.HOG0022330,Loss more likely in non-orb-weavers,50,-2.722522,2.141345,No,0.9938,0.0062,0.0579,0.9421,129217545,GO:0046777 [Name: protein autophosphorylation]...,dual specificity tyrosine-phosphorylation-regu...,dual specificity tyrosine-phosphorylation-regu...
260,N5.HOG0024065,"Loss more likely in non-orb-weavers, duplicati...",66,-2.850324,2.026191,Yes for loss; no for duplication,0.9583,0.0417,0.0115,0.9885,129218972,GO:0005737 [Name: cytoplasm]; GO:0006468 [Name...,uncharacterized LOC129218972,uncharacterized protein
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275,N5.HOG0067099,Duplication more likely in non-orb-weavers,56,2.257462,-2.780946,Yes,0.0830,0.9170,0.9689,0.0311,129225034,GO:0005737 [Name: cytoplasm]; GO:0019901 [Name...,Cdk5 activator-like protein,cyclin-dependent kinase 5 activator 1 isoform X1
1283,N5.HOG0067221,Duplication more likely in orb-weavers,89,-1.504431,1.649684,No,0.9095,0.0905,0.0213,0.9787,129222939,GO:0006670 [Name: sphingosine metabolic proces...,sphingosine-1-phosphate phosphatase 2-like,sphingosine-1-phosphate phosphatase 2
1347,N5.HOG0068715,Loss more likely in non-orb-weavers,83,-2.162736,0.712293,No,0.9910,0.0090,0.2442,0.7558,129232140,GO:0004930 [Name: G-protein coupled receptor a...,probable G-protein coupled receptor AH9.1,probable G-protein coupled receptor AH9.1
1354,N5.HOG0068937,Loss more likely in orb-weavers,78,1.716305,-0.226392,No,0.0063,0.9937,0.5667,0.4333,129225023,GO:0007218 [Name: neuropeptide signaling pathway],FMRFamide propeptide,myomodulin neuropeptides
1378,N5.HOG0069577,Loss more likely in non-orb-weavers,81,-1.740438,0.352464,No,0.9532,0.0468,0.2143,0.7857,129219120,GO:0000981 [Name: RNA polymerase II transcript...,homeobox protein vnd-like,homeobox protein Nkx-2.5

In [36]:
relax_previous_interesting_df = relax_df[relax_df['HOG'].isin(previous_interesting['HOG'])]
relax_previous_interesting_df

,HOG,result,foreground,p_value,k,LRT,MG94xREV_ω_reference,MG94xREV_ω_test,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
73,N5.HOG0019920,intensified,non-orbweavers,3.011191e-11,1.130083,44.169612,0.100545,0.097475,0.062908,1.000000,0.103306,0.000000,8.630577,0.000000,0.086494,1.000000,0.134156,0.000000,6.734307,0.000000,0.062908,0.086494,129222487,GO:0005515 [Name: protein binding]; GO:0007052...,mitogen-activated protein kinase-binding prote...,mitogen-activated protein kinase-binding prote...
116,N5.HOG0042919,relaxed,non-orbweavers,1.224287e-04,0.609426,14.754904,0.081368,0.084417,0.000000,0.812948,0.963395,0.000000,5.241449,0.187052,0.000000,0.812948,0.940642,0.000000,15.154436,0.187052,0.980422,2.834664,129216273,GO:0007186 [Name: G-protein coupled receptor s...,G-protein coupled receptor moody-like,protein trapped in endoderm-1
168,N5.HOG0067795,intensified,non-orbweavers,2.642783e-05,1.322133,17.658882,0.328540,0.247638,0.000000,0.335605,0.320439,0.664395,2.505454,0.000000,0.000000,0.335605,0.422833,0.664395,2.003084,0.000000,0.212898,0.280928,129216741,GO:0006303 [Name: double-strand break repair v...,uncharacterized LOC129216741,DNA repair protein xrcc4
179,N5.HOG0064387,relaxed,non-orbweavers,0.000000e+00,0.999881,128.798248,0.000004,0.000007,0.000000,0.906387,0.989755,0.000202,537.595764,0.093410,0.000000,0.906387,0.989753,0.000202,537.998949,0.093410,50.217237,50.254898,129226526,GO:0018107 [Name: peptidyl-threonine phosphory...,serine/threonine-protein kinase meng-po-like,serine/threonine-protein kinase meng-po
225,N5.HOG0045324,relaxed,non-orbweavers,1.062393e-04,0.891436,15.022459,0.052815,0.082167,0.051174,0.189255,0.051764,0.810745,1.564664,0.000000,0.035631,0.189255,0.036093,0.810745,1.652337,0.000000,0.051653,0.036005,129217616,GO:0004402 [Name: histone acetyltransferase ac...,males absent on the first,histone acetyltransferase KAT8 isoform X1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
951,N5.HOG0058762,relaxed,non-orbweavers,6.228512e-05,0.862489,16.031871,0.025584,0.040996,0.000248,0.575322,0.087112,0.424678,5.560925,0.000000,0.000066,0.575322,0.059032,0.424678,7.310548,0.000000,0.037137,0.025108,129217234,GO:0035556 [Name: intracellular signal transdu...,SH2B adapter-like protein Lnk,SH2B adapter protein 2
1041,N5.HOG0049782,intensified,non-orbweavers,5.427900e-07,1.683998,25.105458,0.138874,0.108572,0.000000,0.775011,0.061117,0.185664,36.931320,0.039325,0.000000,0.775011,0.190193,0.185664,8.526252,0.039325,1.463682,0.370609,129224572,GO:0005524 [Name: ATP binding]; GO:0004335 [Na...,galactokinase-like,galactokinase
1089,N5.HOG0014639,relaxed,non-orbweavers,4.964535e-02,0.932220,3.853397,0.081830,0.110404,0.073574,0.881520,0.076769,0.118480,4.100417,0.000000,0.060859,0.881520,0.063699,0.118480,4.543447,0.000000,0.073952,0.061195,129231150,GO:0007165 [Name: signal transduction]; GO:004...,glycine receptor subunit alpha-1-like,glycine receptor subunit alpha-2
1093,N5.HOG0055160,relaxed,non-orbweavers,2.533306e-02,0.924907,5.000974,0.020549,0.039738,0.021891,0.619884,0.022983,0.380116,1.535520,0.000000,0.016051,0.619884,0.016919,0.380116,1.589929,0.000000,0.022306,0.016381,129216986,GO:0005524 [Name: ATP binding]; GO:0004674 [Na...,cAMP-dependent protein kinase catalytic subuni...,cAMP-dependent protein kinase catalytic subuni...
1099,N5.HOG0060437,intensified,non-orbweavers,1.321389e-04,1.177272,14.611030,0.019282,0.010964,0.006707,0.989409,0.076536,0.009916,24.139114,0.000675,0.014250,0.989409,0.112702,0.009916,14.945574,0.000675,0.023685,0.025302,129223920,GO:0005515 [Name: protein binding]; GO:0005737...,guanine nucleotide-binding protein subunit beta-5,guanine nucleotide-binding protein subunit beta-5

In [37]:
busted_previous_interesting_df = busted_df[busted_df['HOG'].isin(previous_interesting['HOG'])]
busted_previous_interesting_df

,HOG,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
35,N5.HOG0032852,orbweavers,2.785605e-11,47.221645,0.500000,0.000000,3.302527e-07,38.287987,0.000036,0.000044,0.000000,0.670725,0.286393,0.328303,4565.730570,0.000972,0.050513,0.166069,0.051164,0.742309,1.000000,0.091622,4.533844,0.137990,129218644,GO:0000407 [Name: pre-autophagosomal structure...,autophagy-related protein 13-like,autophagy-related protein 13 homolog
85,N5.HOG0062144,orbweavers,2.457163e-03,10.631201,0.313645,0.932690,1.665398e-04,24.598444,0.218025,0.166806,0.000000,0.461881,0.182661,0.537188,61.036923,0.000931,0.000000,0.028024,0.057845,0.952909,1.446556,0.019067,0.154945,0.082703,129230419,GO:0006470 [Name: protein dephosphorylation]; ...,tyrosine-protein phosphatase non-receptor type...,tyrosine-protein phosphatase non-receptor type...
188,N5.HOG0041449,non-orbweavers,5.171743e-05,18.353137,0.164183,2.227253,4.605308e-04,22.292970,0.027916,0.020816,0.002549,0.356142,0.026173,0.639577,5.073675,0.004281,0.010137,0.984991,0.010916,0.007683,1.708281,0.007326,0.039370,0.022583,129216205,GO:0005886 [Name: plasma membrane]; GO:0019905...,Syntaxin-binding protein Rop,protein ROP
190,N5.HOG0053555,non-orbweavers,2.749896e-07,28.826771,0.500000,0.000000,9.880103e-06,30.882732,0.009285,0.003611,0.002276,0.964561,0.037733,0.032931,16.420085,0.002507,0.000032,0.294884,0.000725,0.701359,1.000000,0.003756,0.044611,0.004274,129228121,GO:0004749 [Name: ribose phosphate diphosphoki...,phosphoribosyl pyrophosphate synthase-associat...,phosphoribosyl pyrophosphate synthase-associat...
252,N5.HOG0056026,non-orbweavers,1.083936e-09,39.899039,0.500000,0.000000,7.874723e-05,26.279844,0.131348,0.130610,0.055443,0.896880,0.648480,0.099914,5117.627513,0.003206,0.000000,0.193818,0.005657,0.597448,0.522570,0.208734,16.523892,0.112458,129233356,GO:0006020 [Name: inositol metabolic process];...,inositol monophosphatase 1-like,inositol monophosphatase 1
292,N5.HOG0012725,non-orbweavers,1.109307e-03,12.221746,0.207989,1.754248,1.859624e-13,68.755691,0.308294,0.275076,0.000000,0.236411,0.254948,0.718100,2.516173,0.045489,0.067390,0.776744,0.550223,0.173813,1.683657,0.049443,0.297537,0.231225,129227599,GO:0016020 [Name: membrane]; GO:1902936 [Name:...,alpha-tocopherol transfer protein-like,alpha-tocopherol transfer protein-like

## Spider accessions and BUSCO scores

In [36]:
buscos = pd.read_csv(f'{data}/orthorun_list_fams_busco90.csv')
accessions = pd.read_csv(f'{data}/txptome_accessions.csv')
accessions.drop(columns=['Infraorder', 'Family', 'Web_Type', 'Cribellum'], inplace=True)

buscos_accessions = pd.merge(buscos, accessions, on='Species', how='left')

buscos_accessions.drop_duplicates(inplace=True)
buscos_accessions.dropna(how='any', inplace=True)
buscos_accessions.reset_index(drop=True, inplace=True)
# Collapse rows: group by all columns except 'Accession', join 'Accession' values as comma-separated string
buscos_accessions.rename(columns={'Single': 'Single_copy_BUSCOs', 'Duplicated': 'Duplicated_BUSCOs', 'Total': 'Total_BUSCOs'}, inplace=True)
buscos_accessions.shape[0]

102

In [37]:
buscos_accessions.to_excel(f'{results}/Supplementary_Table_1_SpiderAccessions_BUSCOs.xlsx', index=False)

In [38]:
# Count rows with NaN in the 'Accession' column before collapsing
num_nan_accession = buscos_accessions['Accession'].isna().sum()
print(f"Rows with NaN in 'Accession': {num_nan_accession}")

Rows with NaN in 'Accession': 0

## N5 HOGs

this is just to make the format match the others

In [11]:
n5_hogs = pd.read_csv(f'{data}/N5.tsv', sep='\t')
n5_hogs

/var/folders/bh/l9d0n24d5011lh6bfqzp4n7r0000gn/T/ipykernel_63324/2966892365.py:1: DtypeWarning: Columns (3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,36,37,39,40,41,42,43,44,45,46,47,48,49,51,52,53,54,55,56,57,58,59,60,61,62,63,64,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94) have mixed types. Specify dtype option on import or set low_memory=False.
  n5_hogs = pd.read_csv(f'{data}/N5.tsv', sep='\t')

,HOG,OG,Gene Tree Parent Clade,Acroaspis_sp_IDV6688,Acrosomoides_sp_IDV7426,Ainerigone_saitoi,Ambicodamus_IDV6680,Antrodiaetus_roretzi,Araneus_inustus,Arcuphantes_paiki,Arcuphantes_tamaensis,Arcuphantes_uenoi,Argiope_aetheroides,Argiope_bruennichi,Argiope_keyserlingi,Argyrodes_flavescens,Argyrodes_miniaceus,Backobourkia_brouni,Baryphymula_kamakuraensis,Caerostris_darwini,Caerostris_extrusa,Chrysso_octomaculata,Clubiona_robusta,Cryptachaea_gigantipes,Cyclosa_octotuberculata,Cyrtarachne_bufo,Cyrtophora_cicatrosa,Deinopis_sp_IDV6783,Deinopis_sp_IDV7365,Desis_marina,Diaea_subdola,Doenitzius_peniculus,Doenitzius_pruvus,Dolophones_sp_IDV6683,Drapetisca_socialis,Drosophila_melanogaster,Ebrechtella_tricuspidata,Eriophora_pustulosa,Falcileptoneta_japonica,Floronia_bucculenta,Gnathonarium_exsiccatum,Helpis_minitabunda,Hypselistes_asiaticus,Hypsosinga_pygmaea,Larinia_phthisica,Lariniaria_argiopiformis,Larinioides_cornutus,Latrodectus_hasseltii,Lehtinelagia_evanida,Leucauge_dromedari,Masirana_silvicola,Mesida_sp_IDV5268,Metazygia_zilloides,Metleucauge_yunohamensis,Microbathyphantes_tateyamaensis,Neoantistea_quelpartensis,Neon_minutus,Neoscona_adianta,Neoscona_nautica,Neoscona_scylla,Neoscona_subpullata,Neoscona_theisi,Neriene_clathrata,Neriene_oidedicata,Nuctenea_umbratica,Orchestina_okitsui,Ordgarius_hobsoni,Ordgarius_sexspinosus,Oxytate_striatipes,Ozyptila_nongae,Parasteatoda_culicivora,Paratheuma_awasensis,Pardosa_graminea,Pharta_brevipalpus,Phonognatha_graeffei,Phrurolithus_coreanus,Piratula_tanakai,Plebs_sachalinensis,Poecilopachys_australasia,Psechrus_IDV5238,Pseudomicrargus_latitegulatus,Rhomphaea_labiata,Robertus_nojimai,Ryojius_japonicus,Saaristoa_nipponica,Saitonia_ojiroensis,Steatoda_grossa,Stephanopis_cambridgei,Stertinius_kumadai,Syedra_oii,Tekellina_sadamotoi,Tetragnatha_brevignatha,Tetragnatha_extensa,Tetragnatha_filiciphilia,Tetragnatha_mandibulata,Tetragnatha_maxillosa,Tetragnatha_paludicola,Tetragnatha_quasimodo,Tetragnatha_stelarobusta,Tetragnatha_vermiformis,Tetragnatha_waikamoi,Tetragnatha_yesoensis,Theridion_varians,Uloborus_diversus,Ummeliata_osakaensis,Zelotes_iriomotensis
0,N5.HOG0000000,OG0000000,n6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBHE01016182.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBYA01011843.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N5.HOG0000001,OG0000000,n10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAJV01004504.1.p1, IAJV01032038.1.p1",IAFI01007613.1.p1,IAHZ01018353.1.p1,NaN,NaN,IBHV01013931.1.p1,NaN,ICDG01046476.1.p1,NaN,IBVS01009860.1.p1,NaN,NaN,NaN,IBRX01018078.1.p1,"ICBF01004250.1.p1, ICBF01032375.1.p1",IAEU01028549.1.p2,"IBPZ01042485.1.p1, IBPZ01001432.1.p1","IAXT01039719.1.p1, IAXT01003871.1.p1",NaN,NaN,"IAPM01038371.1.p1, IAPM01013637.1.p1, IAPM0102...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GITM01041654.1.p1,IAHF01031891.1.p1,GITN01024129.1.p1,ICFC01017347.1.p1,"ICMP01008935.1.p1, ICMP01020576.1.p1",GITO01026887.1.p1,GITP01051515.1.p1,GITQ01067807.1.p1,IAJJ01011887.1.p1,GITR01106566.1.p1,IBMZ01020084.1.p1,NaN,NaN,NaN,NaN
2,N5.HOG0000002,OG0000000,n40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IASB01000065.1.p1,NaN,IAET01037148.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBJP01018148.1.p1,IBVW01007283.1.p1,NaN,NaN,NaN,NaN,IBIK01042678.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBDY01023263.1.p1,IBVS01007432.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IALM01040017.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ICHT01027615.1.p1, ICHT01017775.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N5.HOG0000003,OG0000000,n50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICCG01026617.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAQZ01002733.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAUM01007052.1.p1,NaN,NaN,NaN,NaN,IAHZ01017123.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N5.HOG0000004,OG0000000,n54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICCG01017817.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAQZ01033432.1.p1,NaN,NaN,NaN,ICOI01021205.1.p1,NaN,NaN,NaN,NaN,"IBZG01014388.1.p1, IBZG01025934.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAOT01017345.1.p1,ICEG01003535.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IBDY01001551.1.p1, IBDY01030445.1.p1",NaN,ICFH01038389.1.p1,NaN,IAIC01008931.1.p1,IBRX01015679.1.p1,NaN,IAEU01025729.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAGL01014301.1.p1,ICMU01023364.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"GJZJ01103430.1.p1, GJZJ01279486.1.p1, GJZJ0101...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107981,N5.HOG0107981,OG0046213,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01041866.1.p2, IAHP01035491.1.p2"
107982,N5.HOG0107982,OG0046214,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01042646.1.p2, IAHP01035715.1.p2"
107983,N5.HOG0107983,OG0046215,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01041096.1.p1, IAHP01036455.1.p1"
107984,N5.HOG0107984,OG0046216,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01037270.1.p1, IAHP01039697.1.p1"
107985,N5.HOG0107985,OG0046217,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01038618.1.p1, IAHP01041943.1.p1"

In [12]:
# Count non-NaN entries across species columns (from current 4th column to end)
occupancy = n5_hogs.iloc[:, 3:].notna().sum(axis=1)

# Ensure "Occupancy" is placed between "Gene Tree Parent Clade" and "Acroaspis_sp_IDV6688"
if "Occupancy" in n5_hogs.columns:
    n5_hogs = n5_hogs.drop(columns=["Occupancy"])

n5_hogs.insert(3, "Occupancy", occupancy)

n5_hogs

,HOG,OG,Gene Tree Parent Clade,Occupancy,Acroaspis_sp_IDV6688,Acrosomoides_sp_IDV7426,Ainerigone_saitoi,Ambicodamus_IDV6680,Antrodiaetus_roretzi,Araneus_inustus,Arcuphantes_paiki,Arcuphantes_tamaensis,Arcuphantes_uenoi,Argiope_aetheroides,Argiope_bruennichi,Argiope_keyserlingi,Argyrodes_flavescens,Argyrodes_miniaceus,Backobourkia_brouni,Baryphymula_kamakuraensis,Caerostris_darwini,Caerostris_extrusa,Chrysso_octomaculata,Clubiona_robusta,Cryptachaea_gigantipes,Cyclosa_octotuberculata,Cyrtarachne_bufo,Cyrtophora_cicatrosa,Deinopis_sp_IDV6783,Deinopis_sp_IDV7365,Desis_marina,Diaea_subdola,Doenitzius_peniculus,Doenitzius_pruvus,Dolophones_sp_IDV6683,Drapetisca_socialis,Drosophila_melanogaster,Ebrechtella_tricuspidata,Eriophora_pustulosa,Falcileptoneta_japonica,Floronia_bucculenta,Gnathonarium_exsiccatum,Helpis_minitabunda,Hypselistes_asiaticus,Hypsosinga_pygmaea,Larinia_phthisica,Lariniaria_argiopiformis,Larinioides_cornutus,Latrodectus_hasseltii,Lehtinelagia_evanida,Leucauge_dromedari,Masirana_silvicola,Mesida_sp_IDV5268,Metazygia_zilloides,Metleucauge_yunohamensis,Microbathyphantes_tateyamaensis,Neoantistea_quelpartensis,Neon_minutus,Neoscona_adianta,Neoscona_nautica,Neoscona_scylla,Neoscona_subpullata,Neoscona_theisi,Neriene_clathrata,Neriene_oidedicata,Nuctenea_umbratica,Orchestina_okitsui,Ordgarius_hobsoni,Ordgarius_sexspinosus,Oxytate_striatipes,Ozyptila_nongae,Parasteatoda_culicivora,Paratheuma_awasensis,Pardosa_graminea,Pharta_brevipalpus,Phonognatha_graeffei,Phrurolithus_coreanus,Piratula_tanakai,Plebs_sachalinensis,Poecilopachys_australasia,Psechrus_IDV5238,Pseudomicrargus_latitegulatus,Rhomphaea_labiata,Robertus_nojimai,Ryojius_japonicus,Saaristoa_nipponica,Saitonia_ojiroensis,Steatoda_grossa,Stephanopis_cambridgei,Stertinius_kumadai,Syedra_oii,Tekellina_sadamotoi,Tetragnatha_brevignatha,Tetragnatha_extensa,Tetragnatha_filiciphilia,Tetragnatha_mandibulata,Tetragnatha_maxillosa,Tetragnatha_paludicola,Tetragnatha_quasimodo,Tetragnatha_stelarobusta,Tetragnatha_vermiformis,Tetragnatha_waikamoi,Tetragnatha_yesoensis,Theridion_varians,Uloborus_diversus,Ummeliata_osakaensis,Zelotes_iriomotensis
0,N5.HOG0000000,OG0000000,n6,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBHE01016182.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBYA01011843.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N5.HOG0000001,OG0000000,n10,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAJV01004504.1.p1, IAJV01032038.1.p1",IAFI01007613.1.p1,IAHZ01018353.1.p1,NaN,NaN,IBHV01013931.1.p1,NaN,ICDG01046476.1.p1,NaN,IBVS01009860.1.p1,NaN,NaN,NaN,IBRX01018078.1.p1,"ICBF01004250.1.p1, ICBF01032375.1.p1",IAEU01028549.1.p2,"IBPZ01042485.1.p1, IBPZ01001432.1.p1","IAXT01039719.1.p1, IAXT01003871.1.p1",NaN,NaN,"IAPM01038371.1.p1, IAPM01013637.1.p1, IAPM0102...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GITM01041654.1.p1,IAHF01031891.1.p1,GITN01024129.1.p1,ICFC01017347.1.p1,"ICMP01008935.1.p1, ICMP01020576.1.p1",GITO01026887.1.p1,GITP01051515.1.p1,GITQ01067807.1.p1,IAJJ01011887.1.p1,GITR01106566.1.p1,IBMZ01020084.1.p1,NaN,NaN,NaN,NaN
2,N5.HOG0000002,OG0000000,n40,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IASB01000065.1.p1,NaN,IAET01037148.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBJP01018148.1.p1,IBVW01007283.1.p1,NaN,NaN,NaN,NaN,IBIK01042678.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBDY01023263.1.p1,IBVS01007432.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IALM01040017.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ICHT01027615.1.p1, ICHT01017775.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N5.HOG0000003,OG0000000,n50,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICCG01026617.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAQZ01002733.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAUM01007052.1.p1,NaN,NaN,NaN,NaN,IAHZ01017123.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N5.HOG0000004,OG0000000,n54,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICCG01017817.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAQZ01033432.1.p1,NaN,NaN,NaN,ICOI01021205.1.p1,NaN,NaN,NaN,NaN,"IBZG01014388.1.p1, IBZG01025934.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAOT01017345.1.p1,ICEG01003535.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IBDY01001551.1.p1, IBDY01030445.1.p1",NaN,ICFH01038389.1.p1,NaN,IAIC01008931.1.p1,IBRX01015679.1.p1,NaN,IAEU01025729.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAGL01014301.1.p1,ICMU01023364.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"GJZJ01103430.1.p1, GJZJ01279486.1.p1, GJZJ0101...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107981,N5.HOG0107981,OG0046213,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01041866.1.p2, IAHP01035491.1.p2"
107982,N5.HOG0107982,OG0046214,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01042646.1.p2, IAHP01035715.1.p2"
107983,N5.HOG0107983,OG0046215,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01041096.1.p1, IAHP01036455.1.p1"
107984,N5.HOG0107984,OG0046216,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01037270.1.p1, IAHP01039697.1.p1"
107985,N5.HOG0107985,OG0046217,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01038618.1.p1, IAHP01041943.1.p1"

Filter to occupancy 30+ (all analyses in the paper used minimum occupancy of 30, 50 or 75)

In [13]:
n5_hogs_occ_30 = n5_hogs[n5_hogs['Occupancy'] >= 30]
n5_hogs_occ_30

,HOG,OG,Gene Tree Parent Clade,Occupancy,Acroaspis_sp_IDV6688,Acrosomoides_sp_IDV7426,Ainerigone_saitoi,Ambicodamus_IDV6680,Antrodiaetus_roretzi,Araneus_inustus,Arcuphantes_paiki,Arcuphantes_tamaensis,Arcuphantes_uenoi,Argiope_aetheroides,Argiope_bruennichi,Argiope_keyserlingi,Argyrodes_flavescens,Argyrodes_miniaceus,Backobourkia_brouni,Baryphymula_kamakuraensis,Caerostris_darwini,Caerostris_extrusa,Chrysso_octomaculata,Clubiona_robusta,Cryptachaea_gigantipes,Cyclosa_octotuberculata,Cyrtarachne_bufo,Cyrtophora_cicatrosa,Deinopis_sp_IDV6783,Deinopis_sp_IDV7365,Desis_marina,Diaea_subdola,Doenitzius_peniculus,Doenitzius_pruvus,Dolophones_sp_IDV6683,Drapetisca_socialis,Drosophila_melanogaster,Ebrechtella_tricuspidata,Eriophora_pustulosa,Falcileptoneta_japonica,Floronia_bucculenta,Gnathonarium_exsiccatum,Helpis_minitabunda,Hypselistes_asiaticus,Hypsosinga_pygmaea,Larinia_phthisica,Lariniaria_argiopiformis,Larinioides_cornutus,Latrodectus_hasseltii,Lehtinelagia_evanida,Leucauge_dromedari,Masirana_silvicola,Mesida_sp_IDV5268,Metazygia_zilloides,Metleucauge_yunohamensis,Microbathyphantes_tateyamaensis,Neoantistea_quelpartensis,Neon_minutus,Neoscona_adianta,Neoscona_nautica,Neoscona_scylla,Neoscona_subpullata,Neoscona_theisi,Neriene_clathrata,Neriene_oidedicata,Nuctenea_umbratica,Orchestina_okitsui,Ordgarius_hobsoni,Ordgarius_sexspinosus,Oxytate_striatipes,Ozyptila_nongae,Parasteatoda_culicivora,Paratheuma_awasensis,Pardosa_graminea,Pharta_brevipalpus,Phonognatha_graeffei,Phrurolithus_coreanus,Piratula_tanakai,Plebs_sachalinensis,Poecilopachys_australasia,Psechrus_IDV5238,Pseudomicrargus_latitegulatus,Rhomphaea_labiata,Robertus_nojimai,Ryojius_japonicus,Saaristoa_nipponica,Saitonia_ojiroensis,Steatoda_grossa,Stephanopis_cambridgei,Stertinius_kumadai,Syedra_oii,Tekellina_sadamotoi,Tetragnatha_brevignatha,Tetragnatha_extensa,Tetragnatha_filiciphilia,Tetragnatha_mandibulata,Tetragnatha_maxillosa,Tetragnatha_paludicola,Tetragnatha_quasimodo,Tetragnatha_stelarobusta,Tetragnatha_vermiformis,Tetragnatha_waikamoi,Tetragnatha_yesoensis,Theridion_varians,Uloborus_diversus,Ummeliata_osakaensis,Zelotes_iriomotensis
42,N5.HOG0000042,OG0000000,n521,30,NaN,NaN,IBTE01045250.1.p1,NaN,NaN,NaN,NaN,IAKU01033670.1.p2,NaN,NaN,NaN,IAET01038018.1.p1,IAFU01017320.1.p2,IBQT01027662.1.p2,ICCG01023241.1.p1,IBGF01007960.1.p3,NaN,NaN,NaN,NaN,NaN,IAQZ01013625.1.p2,NaN,IBHY01031234.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IBIK01029058.1.p2, IBIK01035878.1.p1",NaN,"ICGA01033433.1.p2, ICGA01025359.1.p2",NaN,NaN,IAOT01038489.1.p3,NaN,"IAJV01010093.1.p1, IAJV01019277.1.p1",NaN,IAHZ01019957.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IBVS01042499.1.p1,ICFH01001894.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAXT01012028.1.p2,NaN,NaN,"IAPM01002546.1.p1, IAPM01007779.1.p1",NaN,NaN,ICMU01011756.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IATW01039505.1.p1,NaN,NaN,"ICHT01026571.1.p1, ICHT01009148.1.p1",NaN,NaN,IBJR01049059.1.p3,ICFA01019693.1.p2,ICAL01003840.1.p1,NaN,IBAR01011710.1.p1,NaN,"IAPP01031453.1.p1, IAPP01018406.1.p1, IAPP0100...",NaN,NaN,IAXS01029553.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GITP01099019.1.p1,GITQ01074980.1.p1,NaN,NaN,IBMZ01047024.1.p1,NaN,NaN,NaN,NaN
52,N5.HOG0000052,OG0000000,n667,30,NaN,NaN,NaN,ICBW01009633.1.p1,NaN,IAHS01041868.1.p1,NaN,IAKU01006172.1.p1,IBBK01025117.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ICOE01034450.1.p1, ICOE01020152.1.p1",NaN,NaN,NaN,NaN,NaN,IBHY01006183.1.p1,NaN,NaN,NaN,ICGF01019809.1.p1,NaN,IBVW01012136.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICEG01034146.1.p1,IAJV01041573.1.p1,IAFI01040479.1.p1,IAHZ01026716.1.p1,NaN,IBFM01010861.1.p1,NaN,NaN,NaN,IBDY01012329.1.p1,IBVS01036228.1.p1,NaN,NaN,IAIC01019294.1.p1,"IBRX01015955.1.p1, IBRX01015087.1.p1",ICBF01028066.1.p1,IAEU01018909.1.p1,IBPZ01016824.1.p1,NaN,"IAFP01028931.1.p1, IAFP01007703.1.p1, IAFP0100...",IAQC01004191.1.p1,NaN,NaN,NaN,NaN,IALM01031986.1.p1,ICBR01046734.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICFA01036094.1.p1,NaN,IBWO01022169.1.p1,NaN,NaN,NaN,ICHM01016774.1.p1,"IAUC01015023.1.p1, IAUC01043947.1.p3, IAUC0104...",IAXS01007743.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAHP01002859.1.p1
147,N5.HOG0000147,OG0000000,n1866,34,IANO01045459.1.p1,ICOJ01034563.1.p1,NaN,NaN,NaN,IAHS01010517.1.p1,NaN,NaN,NaN,IASB01004179.1.p1,IBFJ01008057.1.p1,IAET01001136.1.p1,NaN,NaN,NaN,NaN,ICOF01016127.1.p1,ICOE01010111.1.p1,NaN,NaN,NaN,IAQZ01021454.1.p1,ICFD01036047.1.p1,"IBHY01036715.1.p1, IBHY01023209.1.p1, IBHY0102...",NaN,NaN,GIWQ01381602.1.p1,NaN,NaN,NaN,IBZG01032581.1.p1,NaN,NaN,NaN,IBIK01028214.1.p1,NaN,NaN,NaN,NaN,NaN,ICEG01018260.1.p1,NaN,NaN,NaN,NaN,NaN,IBHV01007634.1.p1,NaN,NaN,IBDY01031959.1.p1,"IBVS01031350.1.p1, IBVS01009057.1.p1","ICFH01036969.1.p1, ICFH01009273.1.p1",NaN,NaN,IBRX01012041.1.p1,ICBF01026346.1.p1,IAEU01009270.1.p1,IBPZ01024792.1.p1,IAXT01012292.1.p1,NaN,NaN,IAPM01019489.1.p1,NaN,IAGL01002019.1.p1,ICMU01001930.1.p1,NaN,NaN,NaN,IARK01036035.1.p1,NaN,NaN,IATW01005412.1.p1,NaN,NaN,ICHT01034227.1.p1,ICKB01015416.1.p1,IAQN01003844.1.p1,NaN,NaN,NaN,IBWO01038624.1.p1,NaN,NaN,IAPP01000817.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,N5.HOG0000196,OG0000000,n2556,46,IANO01032399.1.p1,ICOJ01037145.1.p1,NaN,ICBW01020954.1.p1,NaN,IAHS01007736.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAFU01008817.1.p1,IBQT01025194.1.p1,NaN,IBGF01043878.1.p1,ICOF01006072.1.p1,NaN,NaN,NaN,NaN,NaN,ICFD01014754.1.p1,IBHY01005130.1.p1,IBBP01002725.1.p1,NaN,NaN,ICGF01010448.1.p1,NaN,IBVW01042278.1.p1,"IBZG01018677.1.p1, IBZG01004248.1.p1",NaN,NaN,NaN,IBIK01041139.1.p1,NaN,ICGA01034284.1.p1,ICCR01015754.1.p1,NaN,NaN,NaN,IAJV01031018.1.p1,NaN,IAHZ01041432.1.p1,IBKS01003116.1.p1,NaN,IBHV01011975.1.p1,NaN,NaN,NaN,IBVS01016666.1.p1,ICFH01015354.1.p1,NaN,NaN,IBRX01034936.1.p1,NaN,NaN,IBPZ01017323.1.p1,IAXT01001688.1.p1,IAFP01018621.1.p1,NaN,NaN,NaN,"IAGL01040560.1.p1, IAGL01031492.1.p1",ICMU01000314.1.p1,IALM01039207.1.p1,ICBR01028520.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICHT01020831.1.p1,NaN,NaN,IBJR01014622.1.p1,ICFA01004483.1.p1,ICAL01010752.1.p1,IBWO01026510.1.p1,IBAR01012902.1.p1,NaN,NaN,NaN,NaN,NaN,IALE01037253.1.p1,NaN,NaN,GITN01088792.1.p1,NaN,"ICMP01041011.1.p1, ICMP01002610.1.p1","GITO01054842.1.p1, GITO01000601.1.p1",NaN,GITQ01025507.1.p1,IAJJ01017983.1.p1,GITR01102608.1.p1,"IBMZ01028119.1.p1, IBMZ01009689.1.p1",NaN,NaN,IBXZ01011769.1.p1,NaN
276,N5.HOG0000276,OG0000000,n3453,30,IANO01031715.1.p1,ICOJ01034962.1.p1,NaN,NaN,NaN,IAHS01033255.1.p1,NaN,NaN,NaN,IASB01012130.1.p1,IBFJ01030513.1.p1,IAET01007769.1.p1,NaN,NaN,ICCG01027298.1.p1,NaN,ICOF01000903.1.p1,ICOE01014025.1.p1,NaN,NaN,NaN,IAQZ01013785.1.p1,ICFD01041007.1.p1,IBHY01041380.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,"IBZG01009391.1.p1, IBZG01029040.1.p1",NaN,NaN,NaN,IBIK01022906.1.p1,NaN,NaN,NaN,NaN,NaN,ICEG01030255.1.p1,IAJV01027646.1.p1,IAFI01011162.1.p1,IAHZ01030342.1.p1,NaN,NaN,NaN,NaN,NaN,IBDY01015241.1.p1,NaN,NaN,NaN,NaN,IBRX01019363.1.p1,ICBF01039514.1.p1,IAEU01041650.1.p1,IBPZ01047814.1.p1,IAXT01028253.1.p1,NaN,NaN,IAPM01041038.1.p1,NaN,IAGL01036927.1.p1,"ICMU01021987.1.p1, ICMU01013273.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,IATW01023225.1.p1,NaN,NaN,ICHT01014576.1.p1,ICKB01005891.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73724,N5.HOG0073724,OG0010664,n0,31,NaN,ICOJ01040730.1.p1,IBTE01046677.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAFU01008057.1.p1,IBQT01038485.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBHY01016117.1.p1,NaN,NaN,GIWQ01135313.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICGA01040230.1.p1,NaN,NaN,IAOT01035970.1.p1,NaN,IAJV01034819.1.p1,IAFI01041558.1.p1,NaN,NaN,NaN,NaN,NaN,ICDG01042469.1.p1,NaN,IBVS01020873.1.p1,NaN,NaN,NaN,IBRX01013188.1.p1,NaN,IAEU01019630.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBTW01026556.1.p1,IARK01001627.1.p1,ICDS01023904.1.p1,NaN,NaN,NaN,NaN,ICHT01036049.1.p1,NaN,IAQN01035291.1.p1,NaN,ICFA01018177.1.p1,NaN,NaN,NaN,NaN,IAPP01018210.1.p1,NaN,NaN,NaN,NaN,GITM01003150.1.p1,NaN,GITN01079596.1.p1,ICFC01006401.1.p1,ICMP01009837.1.p1,GITO01024665.1.p1,"GITP01082162.1.p1, GITP01071870.1.p1",GITQ01001293.1.p1,IAJJ01034856.1.p1,GITR01008734.1.p1,IBMZ01008021.1.p1,NaN,NaN,NaN,NaN
73740,N5.HOG0073740,OG0010674,n0,30,NaN,NaN,NaN,ICBW01000105.1.p2,NaN,NaN,IAWN01030888.1.p1,NaN,IBBK01018300.1.p1,NaN,NaN,NaN,NaN,IBQT01004616.1.p1,NaN,IBGF01047311.1.p1,NaN,NaN,NaN,ICJS01011875.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,GIWQ01117802.1.p1,ICGF01041525.1.p1,IBJP01030739.1.p1,NaN,IBZG01034776.1.p1,NaN,NaN,ICBZ01025532.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBFM01004794.1.p1,NaN,NaN,ICDG01020384.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,ICBF01027551.1.p2,NaN,IBPZ01002143.1.p3,NaN,IAFP01023432.1.p1,NaN,NaN,NaN,NaN,NaN,IALM01033208.1.p1,NaN,NaN,IARK01026543.1.p2,ICDS01003106.1.p3,IAWA01000034.1.p2,IATW01008106.1.p1,IBPN01003877.1.p1,IBYA01043291.1.p1,NaN,NaN,IAQN01022845.1.p1,NaN,ICFA01032641.1.p1,ICAL01014058.1.p1,IBWO01011520.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICMP01043134.1.p1,NaN,NaN,NaN,NaN,NaN,IBMZ01023210.1.p2,NaN,jg24230.t1.p1,NaN,NaN
73766,N5.HOG0073766,OG0010684,n0,30,NaN,NaN,NaN,NaN,NaN,IAHS01040657.1.p1,IAWN01008785.1.p2,IAKU01006408.1.p2,IBBK01028251.1.p2,NaN,NaN,NaN,IAFU01037065.1.p1,NaN,NaN,IBGF01018746.1.p1,NaN,NaN,NaN,ICJS01005026.1.p1,NaN,NaN,NaN,IBHY01021609.1.p1,IBBP01017949.1.p1,NaN,GIWQ01132137.1.p1,ICGF01019478.1.p1,IBJP01000789.1.p2,NaN,IBZG01018576.1.p1,ICKS01041030.1.p3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICEG01035043.1.p1,NaN,NaN,NaN,NaN,IBFM01020812.1.p3,NaN,NaN,NaN,NaN,NaN,ICFH01001098.1.p1,NaN,NaN,NaN,ICBF01039148.1.p1,NaN,IBPZ01015023.1.p1,IAXT01005806.1.p1,IAFP01033995.1.p1,IAQC01016858.1.p1,NaN,NaN,NaN,NaN,IALM01033509.1.p1,ICBR01030418.1.p1,NaN,NaN,ICDS01000240.1.p1,NaN,NaN,NaN,IBYA01045995.1.p1,NaN,ICKB01018174.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAXS01001729.1.p3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBMZ01046339.1.p1,NaN,GJZJ01249014.1.p1,NaN,NaN
73773,N5.HOG0073773,OG0010691,n0,32,NaN,NaN,NaN,NaN,NaN,NaN,IAWN01042058.1.p1,IAKU01018766.1.p1,IBBK01012119.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GIWQ01078670.1.p1,NaN,IBJP01036834.1.p1,NaN,IBZG01031076.1.p1,ICKS01003098.1.p1,NaN,NaN,IBIK01037113.1.p1,NaN,ICGA01010898.1.p1,ICCR01025524.1.p1,NaN,NaN,NaN,IAJV01005156.1.p1,NaN,NaN,NaN,IBFM01033393.1.p1,IBHV01023425.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICBF01028898.1.p1,NaN,NaN,NaN,IAFP01026296.1.p1,NaN,NaN,NaN,IAGL01005682.1.p1,ICMU01000769.1.p1,NaN,NaN,NaN,IARK01008905.1.p1,ICDS01041418.1.p1,NaN,IATW01012982.1.p1,IBPN01039291.1.p1,NaN,NaN,ICKB01012518.1.p1,NaN,NaN,NaN,ICAL01021288.1.p1,IBWO01015655.1.p1,NaN,NaN,NaN,NaN,IAUC01036457.1.p1,IAXS01035856.1.p1,IALE01033371.1.p1,NaN,IAHF01001704.1.p1,NaN,ICFC01003335.1.p1,NaN,NaN,NaN,NaN,IAJJ01038305.1.p2,NaN,NaN,NaN,GJZJ01239057.1.p1,NaN,IAHP01000870.1.p1
73818,N5.HOG0073818,OG0010723,n0,30,IANO01037111.1.p1,NaN,NaN,ICBW01013549.1.p1,NaN,NaN,IAWN01024921.1.p1,NaN,NaN,IASB01025750.1.p1,NaN,NaN,NaN,NaN,NaN,IBGF01044780.1.p1,NaN,ICOE01025274.1.p1,NaN,NaN,IBTR01005915.1.p1,NaN,ICFD01035609.1.p1,NaN,NaN,NaN,GIWQ01383041.1.p1,NaN,NaN,NaN,IBZG01012975.1.p1,NaN,NaN,NaN,IBIK01005536.1.p1,NaN,NaN,NaN,NaN,NaN,ICEG01017263.1.p1,NaN,IAFI01001428.1.p1,NaN,IBKS01017448.1.p2,"IBFM01031672.1.p1, IBFM01017932.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAGL01007245.1.p1,NaN,NaN,NaN,IBTW01046018.1.p2,IARK01017407.1.p1,ICDS01011957.1.p1,IAWA01034949.1.p1,NaN,NaN,NaN,NaN,NaN,IAQN01018303.1.p1,NaN,NaN,ICAL01036097.1.p1,NaN,NaN,NaN,IAPP01029674.1.p1,ICHM01024813.1.p2,NaN,NaN,IALE01009140.1.p1,NaN,IAHF01049739.1.p1,NaN,ICFC01002755.1.p1,NaN,GITO01060063.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBXZ01047078.1.p1,IAHP01017676.1.p1

In [14]:
n5_hogs_occ_30.to_csv(f'{data}/N5_occ_30.tsv', sep='\t', index=False)

In [8]:
n5_hogs_occ_30.to_excel(f'{results}/Supplementary_Table_2_Entelegyne_HOGs.xlsx', index=False)

## PhyloGLM results

In [45]:
phyloglm = pd.read_csv(f'{results}/phyloglm/phyloglm_p_adj.csv', index_col="HOG")
phyloglm

,error,coef_.Intercept._Estimate,coef_.Intercept._StdErr,coef_.Intercept._z.value,coef_.Intercept._p.value,coef_orb_weavingTRUE_Estimate,coef_orb_weavingTRUE_StdErr,coef_orb_weavingTRUE_z.value,coef_orb_weavingTRUE_p.value,p_adj_bonferroni
HOG,,,,,,,,,,
N5.HOG0067161,NaN,-0.131217,0.111454,-1.177318,0.239069,0.462570,0.050010,9.249622,2.252871e-20,2.695110e-16
N5.HOG0062479,NaN,-0.102667,0.072843,-1.409441,0.158705,0.283759,0.032246,8.799725,1.371518e-18,1.640747e-14
N5.HOG0068083,NaN,-0.116300,0.102023,-1.139940,0.254311,0.391135,0.045379,8.619335,6.734435e-18,8.056405e-14
N5.HOG0068230,NaN,0.118418,0.062018,1.909418,0.056208,-0.274228,0.032937,-8.325893,8.369532e-17,1.001247e-12
N5.HOG0030400,NaN,1.146628,0.302901,3.785491,0.000153,-1.144605,0.137932,-8.298313,1.056000e-16,1.263293e-12
...,...,...,...,...,...,...,...,...,...,...
N5.HOG0066701,NaN,0.203044,0.124608,1.629462,0.103215,-0.312257,0.067792,-4.606109,4.102731e-06,4.908098e-02
N5.HOG0060348,NaN,0.493869,0.236504,2.088208,0.036779,-1.055627,0.229242,-4.604867,4.127303e-06,4.937492e-02
N5.HOG0061162,NaN,0.178121,0.154513,1.152796,0.248994,0.314913,0.068417,4.602884,4.166809e-06,4.984754e-02
N5.HOG0050233,NaN,0.637260,0.211430,3.014054,0.002578,-0.715788,0.155517,-4.602618,4.172129e-06,4.991118e-02
N5.HOG0065991,NaN,0.044545,0.116964,0.380840,0.703322,-0.288436,0.062672,-4.602332,4.177865e-06,4.997980e-02

In [48]:
phyloglm_sig = phyloglm.drop(columns=[
    'error', 'coef_.Intercept._Estimate', 'coef_.Intercept._StdErr', 'coef_.Intercept._z.value', 'coef_.Intercept._p.value'])
phyloglm_sig.rename(columns={
    'coef_orb_weavingTRUE_Estimate': 'Orb-weaving coefficient estimate',
    'coef_orb_weavingTRUE_StdErr': 'Orb-weaving coefficient standard error',
    'coef_orb_weavingTRUE_z.value': 'Orb-weaving coefficient z-value',
    'coef_orb_weavingTRUE_p.value': 'Orb-weaving coefficient p-value'
    }, inplace=True)

In [49]:
phyloglm_locs = convert_hogs_to_locs(phyloglm_sig, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
phyloglm_locs_fltrd = phyloglm_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
phyloglm_locs_fltrd = move_column(phyloglm_locs_fltrd, 'HOG', 0)
phyloglm_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
phyloglm_locs_fltrd

Processing HOGs: 100%|██████████| 337/337 [00:00<00:00, 57587.31it/s]

,HOG,Orb-weaving coefficient estimate,Orb-weaving coefficient standard error,Orb-weaving coefficient z-value,Orb-weaving coefficient p-value,p_adj_bonferroni,U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0067161,0.462570,0.050010,9.249622,2.252871e-20,2.695110e-16,NaN,NaN,NaN
1,N5.HOG0062479,0.283759,0.032246,8.799725,1.371518e-18,1.640747e-14,129224049,-,zygotic DNA replication licensing factor mcm3-...
2,N5.HOG0068083,0.391135,0.045379,8.619335,6.734435e-18,8.056405e-14,129224240,GO:0006888 [Name: ER to Golgi vesicle-mediated...,trafficking protein particle complex subunit 4...
3,N5.HOG0068230,-0.274228,0.032937,-8.325893,8.369532e-17,1.001247e-12,129229571,GO:0005739 [Name: mitochondrion]; GO:0000287 [...,mitochondrial ribosome-associated GTPase 2-like
4,N5.HOG0030400,-1.144605,0.137932,-8.298313,1.056000e-16,1.263293e-12,129223000,GO:0005615 [Name: extracellular space],uncharacterized LOC129223000
...,...,...,...,...,...,...,...,...,...
332,N5.HOG0066701,-0.312257,0.067792,-4.606109,4.102731e-06,4.908098e-02,129230750,GO:0045454 [Name: cell redox homeostasis]; GO:...,thioredoxin reductase-like selenoprotein T hom...
333,N5.HOG0060348,-1.055627,0.229242,-4.604867,4.127303e-06,4.937492e-02,129231768,-,U-scoloptoxin(19)-Tl1a-like
334,N5.HOG0061162,0.314913,0.068417,4.602884,4.166809e-06,4.984754e-02,129233683,GO:0005689 [Name: U12-type spliceosomal comple...,U11/U12 small nuclear ribonucleoprotein 25 kDa...
335,N5.HOG0050233,-0.715788,0.155517,-4.602618,4.172129e-06,4.991118e-02,129217819,GO:0017171 [Name: serine hydrolase activity],lethal (2) k09913
336,N5.HOG0065991,-0.288436,0.062672,-4.602332,4.177865e-06,4.997980e-02,129222783,GO:0004721 [Name: phosphoprotein phosphatase a...,mitochondrial import inner membrane translocas...

In [50]:
phyloglm_df = get_ptep_description(phyloglm_locs_fltrd)
phyloglm_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_7_PhyloGLM_hits.xlsx'), index=False)
phyloglm_df

,HOG,Orb-weaving coefficient estimate,Orb-weaving coefficient standard error,Orb-weaving coefficient z-value,Orb-weaving coefficient p-value,p_adj_bonferroni,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
0,N5.HOG0067161,0.462570,0.050010,9.249622,2.252871e-20,2.695110e-16,NaN,NaN,NaN,electron transfer flavoprotein subunit beta
1,N5.HOG0062479,0.283759,0.032246,8.799725,1.371518e-18,1.640747e-14,129224049,-,zygotic DNA replication licensing factor mcm3-...,zygotic DNA replication licensing factor mcm3 ...
2,N5.HOG0068083,0.391135,0.045379,8.619335,6.734435e-18,8.056405e-14,129224240,GO:0006888 [Name: ER to Golgi vesicle-mediated...,trafficking protein particle complex subunit 4...,trafficking protein particle complex subunit 4
3,N5.HOG0068230,-0.274228,0.032937,-8.325893,8.369532e-17,1.001247e-12,129229571,GO:0005739 [Name: mitochondrion]; GO:0000287 [...,mitochondrial ribosome-associated GTPase 2-like,mitochondrial ribosome-associated GTPase 2
4,N5.HOG0030400,-1.144605,0.137932,-8.298313,1.056000e-16,1.263293e-12,129223000,GO:0005615 [Name: extracellular space],uncharacterized LOC129223000,uncharacterized protein
...,...,...,...,...,...,...,...,...,...,...
332,N5.HOG0066701,-0.312257,0.067792,-4.606109,4.102731e-06,4.908098e-02,129230750,GO:0045454 [Name: cell redox homeostasis]; GO:...,thioredoxin reductase-like selenoprotein T hom...,LOW QUALITY PROTEIN: thioredoxin reductase-lik...
333,N5.HOG0060348,-1.055627,0.229242,-4.604867,4.127303e-06,4.937492e-02,129231768,-,U-scoloptoxin(19)-Tl1a-like,U-scoloptoxin(19)-Tl1a isoform X1
334,N5.HOG0061162,0.314913,0.068417,4.602884,4.166809e-06,4.984754e-02,129233683,GO:0005689 [Name: U12-type spliceosomal comple...,U11/U12 small nuclear ribonucleoprotein 25 kDa...,U11/U12 small nuclear ribonucleoprotein 25 kDa...
335,N5.HOG0050233,-0.715788,0.155517,-4.602618,4.172129e-06,4.991118e-02,129217819,GO:0017171 [Name: serine hydrolase activity],lethal (2) k09913,uncharacterized protein isoform X1
336,N5.HOG0065991,-0.288436,0.062672,-4.602332,4.177865e-06,4.997980e-02,129222783,GO:0004721 [Name: phosphoprotein phosphatase a...,mitochondrial import inner membrane translocas...,mitochondrial import inner membrane translocas...

In [51]:
previous_interesting_pglm_df = phyloglm_df[phyloglm_df['HOG'].isin(previous_interesting['HOG'])]
previous_interesting_pglm_df

,HOG,Orb-weaving coefficient estimate,Orb-weaving coefficient standard error,Orb-weaving coefficient z-value,Orb-weaving coefficient p-value,p_adj_bonferroni,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
253,N5.HOG0064389,0.472255,0.097118,4.862688,0.000001,0.013853,129233173,GO:0008254 [Name: 3'-nucleotidase activity]; G...,inositol monophosphatase 3-like,inositol monophosphatase 3
306,N5.HOG0059007,-0.435067,0.092856,-4.685398,0.000003,0.033427,129222006,GO:0003712 [Name: transcription cofactor activ...,G protein pathway suppressor 2-like,G protein pathway suppressor 2