# Format and save Supplementary Data Tables from raw data files.

Generates all supplementary data tables (see [results](results/)) except Supplementary Table 8, which is generated in [`Upset Plots.ipynb`](scripts/07_figures_tables/UpSet%20Plots.ipynb).

In [15]:
import os
import sys
import pandas as pd
import numpy as np
from scipy.stats import norm
!{sys.executable} -m pip install openpyxl

# Resolve repo root whether cwd is repo root, scripts/, or a stage subdirectory.
cwd = os.getcwd()
if os.path.basename(cwd) == "orb-selection":
    repo_root = cwd
elif os.path.basename(os.path.dirname(cwd)) == "orb-selection":
    repo_root = os.path.dirname(cwd)
elif os.path.basename(os.path.dirname(os.path.dirname(cwd))) == "orb-selection":
    repo_root = os.path.dirname(os.path.dirname(cwd))
else:
    repo_root = cwd

data = os.path.join(repo_root, "data")
results = os.path.join(repo_root, "results")

src_path = os.path.join(repo_root, "src")
stage03_path = os.path.join(repo_root, "scripts", "03_selection_tests")
stage04_path = os.path.join(repo_root, "scripts", "04_permulation_loss_dup")
for path in (src_path, stage03_path, stage04_path):
    if path not in sys.path:
        sys.path.insert(0, path)

print(f"Using src path: {src_path}")
print(f"Using stage-03 path: {stage03_path}")
print(f"Using stage-04 path: {stage04_path}")

# Import the modules from stage-03/
from hyphy_results_parser import (
    RelaxResult,
    BustedPhResult
)
from id_converter import convert_hogs_to_locs, get_ptep_description

pd.set_option('display.max_columns', None, 'display.max_rows', 20)

Requirement already satisfied: openpyxl in /Users/gorduslab/opt/anaconda3/envs/orb-selection/lib/python3.10/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/gorduslab/opt/anaconda3/envs/orb-selection/lib/python3.10/site-packages (from openpyxl) (2.0.0)
Using src path: /Users/gorduslab/Documents/orb-selection/src
Using stage-03 path: /Users/gorduslab/Documents/orb-selection/scripts/03_selection_tests
Using stage-04 path: /Users/gorduslab/Documents/orb-selection/scripts/04_permulation_loss_dup

In [14]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
def move_column(df, col_name, new_pos):
    cols = list(df.columns)
    cols.insert(new_pos, cols.pop(cols.index(col_name)))
    return df[cols]

## Hyphy Results

In [19]:
hyphy_results = os.path.join(repo_root, "results/hyphy_results_cache/")

In [20]:
# Load the saved RELAX results
relax_result = RelaxResult.load_from_pickle(str(hyphy_results + "relax_results.pkl"))
relax_result_fltrd = relax_result.filter_omega(10000)
relax_hits_df = relax_result_fltrd.get_significant_results()

In [21]:
relax_hits_df = move_column(relax_hits_df, 'result', 0)  # Move 'result' column to the front
relax_hits_df['foreground'] = 'non-orbweavers'
relax_hits_df = move_column(relax_hits_df, 'foreground', 1)  # Move 'foreground' column to the front
relax_hits_df

,result,foreground,p_value,k,LRT,MG94xREV_ω_reference,MG94xREV_ω_test,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,
N5.HOG0060863,relaxed,non-orbweavers,0.012709,0.263420,6.209242,0.195456,0.144789,0.000000e+00,0.815970,0.840297,0.000000,1.149850,0.184030,0.000000,0.815970,0.516571,0.000000,1.699052,0.184030,0.211607,0.312677
N5.HOG0034724,intensified,non-orbweavers,0.000000,2.987698,10349.318069,0.375229,0.323449,1.202761e-13,0.754140,0.015275,0.000000,4.630327,0.245860,0.000047,0.754140,0.246701,0.000000,1.670260,0.245860,1.138414,0.410686
N5.HOG0053197,relaxed,non-orbweavers,0.000100,0.176158,15.139150,0.184215,0.103955,0.000000e+00,0.869894,0.952362,0.000000,1.495308,0.130106,0.000000,0.869894,0.757993,0.000000,9.815145,0.130106,0.194549,1.277013
N5.HOG0063749,intensified,non-orbweavers,0.032893,1.309127,4.551324,0.000016,0.000013,5.684186e-06,0.896994,0.918852,0.055231,2.434837,0.047775,0.000098,0.896994,0.937399,0.055231,1.973385,0.047775,0.167079,0.146140
N5.HOG0038544,intensified,non-orbweavers,0.000053,1.096950,16.345614,0.634951,0.000007,4.630540e-02,0.000000,0.054062,1.000000,1.521564,0.000000,0.060753,0.000000,0.069965,1.000000,1.466153,0.000000,0.054062,0.069965
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0033066,relaxed,non-orbweavers,0.000099,0.565229,15.160434,0.150521,0.122973,0.000000e+00,0.840632,0.770516,0.000000,2.508798,0.159368,0.000000,0.840632,0.630514,0.000000,5.090170,0.159368,0.399821,0.811209
N5.HOG0048453,relaxed,non-orbweavers,0.006537,0.879559,7.396064,0.036306,0.058095,0.000000e+00,0.721171,0.153698,0.278432,20.572784,0.000397,0.000000,0.721171,0.118931,0.278432,31.126266,0.000397,0.050967,0.045479
N5.HOG0056527,intensified,non-orbweavers,0.000000,11.817292,628.122463,0.294712,0.242411,0.000000e+00,0.816089,0.995427,0.153590,5719.136264,0.030321,0.000000,0.816089,0.999612,0.153590,2.079466,0.030321,173.565615,0.216583
N5.HOG0067687,intensified,non-orbweavers,0.004062,1.139227,8.255676,0.179429,0.166086,1.051487e-01,1.000000,0.140360,0.000000,1.285121,0.000000,0.138469,1.000000,0.178427,0.000000,1.246320,0.000000,0.105149,0.138469
N5.HOG0056679,intensified,non-orbweavers,0.000005,1.153741,20.784522,0.000028,0.000022,7.198906e-06,0.246805,0.102695,0.753195,1.005362,0.000000,0.000035,0.246805,0.139080,0.753195,1.004646,0.000000,0.077351,0.104763

In [28]:
relaxed_hogs_path = os.path.join(
    repo_root,
    "results/significant_gene_id_lists/before_tet_fix/relaxed_hogs.txt"
)

relaxed_hogs_list = (
    pd.read_csv(relaxed_hogs_path, header=None)[0]
    .dropna()
    .astype(str)
    .str.strip()
)
relaxed_hogs_list = relaxed_hogs_list[relaxed_hogs_list != ""].tolist()

# overlap with HOG index in relax_hits_df
overlap_hogs = relax_hits_df[relax_hits_df['result']=="relaxed"].index.intersection(relaxed_hogs_list)

print(f"HOGs in file: {len(relaxed_hogs_list)}")
print(f"HOGs in relax_hits_df: {len(relax_hits_df[relax_hits_df['result']=='relaxed'].index)}")
print(f"Overlap: {len(overlap_hogs)}")
overlap_hogs.tolist()[:10]

HOGs in file: 491
HOGs in relax_hits_df: 405
Overlap: 119

['N5.HOG0053831',
 'N5.HOG0033222',
 'N5.HOG0054138',
 'N5.HOG0047052',
 'N5.HOG0064470',
 'N5.HOG0045177',
 'N5.HOG0049247',
 'N5.HOG0059269',
 'N5.HOG0067619',
 'N5.HOG0040013']

In [29]:
intensified_hogs_path = os.path.join(
    repo_root,
    "results/significant_gene_id_lists/before_tet_fix/intensified_hogs.txt"
)

intensified_hogs_list = (
    pd.read_csv(intensified_hogs_path, header=None)[0]
    .dropna()
    .astype(str)
    .str.strip()
)
intensified_hogs_list = intensified_hogs_list[intensified_hogs_list != ""].tolist()

# overlap with HOG index in relax_hits_df
overlap_hogs = relax_hits_df[relax_hits_df['result']=="intensified"].index.intersection(intensified_hogs_list)

print(f"HOGs in file: {len(intensified_hogs_list)}")
print(f"HOGs in relax_hits_df: {len(relax_hits_df[relax_hits_df['result']=='intensified'].index)}")
print(f"Overlap: {len(overlap_hogs)}")
overlap_hogs.tolist()[:10]

HOGs in file: 938
HOGs in relax_hits_df: 737
Overlap: 246

['N5.HOG0038544',
 'N5.HOG0010637',
 'N5.HOG0054359',
 'N5.HOG0010662',
 'N5.HOG0063608',
 'N5.HOG0036636',
 'N5.HOG0029662',
 'N5.HOG0053477',
 'N5.HOG0024380',
 'N5.HOG0062581']

In [5]:
# Load the saved BUSTED-PH results
busted_ph_result = BustedPhResult.load_from_pickle(str(hyphy_results + "busted_ph_results.pkl"))
busted_ph_result_fltrd = busted_ph_result.filter_omega(10000)
busted_ph_hits_df = busted_ph_result_fltrd.get_significant_results()
busted_ph_hits_df['foreground'] = 'orbweavers'
busted_ph_hits_df = move_column(busted_ph_hits_df, 'foreground', 0)  # Move 'foreground' column to the front
busted_ph_hits_df.drop(columns=['result'], inplace=True)  # Drop result column
busted_ph_hits_df

/var/folders/50/5g9n3tts73d9t0l7x7fh2rx00000gp/T/ipykernel_33534/2871403343.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  busted_ph_hits_df['foreground'] = 'orbweavers'

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0027399,orbweavers,7.317358e-04,13.053888,0.500000,-5.188044,0.000000e+00,91.381079,0.000061,0.000028,0.000000,0.342811,0.283104,0.605572,4.819836,0.051617,0.000000,0.371896,0.129794,0.568777,2.031410,0.059327,0.420223,0.194342
N5.HOG0067687,orbweavers,1.004369e-02,7.815326,0.100755,3.203833,1.230178e-02,14.582833,0.179252,0.165886,0.071938,0.823210,0.637933,0.174763,32.915611,0.002027,0.000000,0.352128,0.170137,0.615790,1.807669,0.032082,0.237421,0.162762
N5.HOG0046830,orbweavers,2.882947e-08,33.337441,0.197147,1.861315,9.025339e-06,31.081779,0.016357,0.018601,0.002168,0.925907,0.165569,0.073707,146.613468,0.000386,0.010733,0.980653,0.024182,0.012755,1.409533,0.006592,0.070794,0.020126
N5.HOG0064451,orbweavers,4.321191e-02,4.896984,0.500000,0.000000,2.590683e-11,58.408424,0.000040,0.000027,0.020711,0.643359,0.223796,0.353431,6.376223,0.003211,0.000000,0.234975,0.056956,0.737757,1.000000,0.027268,0.112893,0.069287
N5.HOG0064007,orbweavers,1.627531e-02,6.849918,0.500000,0.000000,6.157777e-05,26.829322,0.064759,0.078682,0.007946,0.729061,0.041205,0.270505,44.880916,0.000434,0.000000,0.114812,0.019444,0.862158,0.817365,0.023030,0.036434,0.035587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0056667,orbweavers,2.675535e-08,33.486768,0.500000,0.000000,6.122469e-06,31.934101,0.144294,0.123302,0.130652,0.360202,0.131566,0.638211,201.708351,0.001587,0.016790,0.155692,0.041429,0.582231,0.379806,0.262077,0.451151,0.126274
N5.HOG0034239,orbweavers,4.028513e-02,5.037251,0.058608,4.287467,2.791839e-03,18.126612,0.249524,0.155437,0.000000,0.615736,0.281903,0.335040,2.695367,0.049224,0.000000,0.123728,0.038189,0.809145,1.454237,0.067127,0.227126,0.128520
N5.HOG0058337,orbweavers,2.474044e-03,10.617508,0.500000,-1122.359434,8.853982e-04,20.795438,0.000062,0.000064,0.000000,0.537250,0.318621,0.446978,6.111431,0.015771,0.000088,0.702471,0.727526,0.293963,201.648060,0.003566,0.238802,0.933030
N5.HOG0054210,orbweavers,9.359787e-05,17.166711,0.500000,0.000000,1.605552e-03,19.418947,0.135085,0.112956,0.098307,0.946483,0.380050,0.050937,253.879126,0.002580,0.041209,0.469748,0.099148,0.393377,0.346891,0.136875,0.767302,0.105841
N5.HOG0062926,orbweavers,4.490367e-04,14.030518,0.500000,0.000000,7.680415e-05,26.335720,0.166421,0.129859,0.007867,0.443931,0.179596,0.554423,55.364149,0.001646,0.000000,0.244007,0.045415,0.564038,0.262784,0.191956,0.194221,0.076059

In [6]:
busted_orb_hogs_path = os.path.join(
    repo_root,
    "results/significant_gene_id_lists/before_tet_fix/busted_ph_orb_hogs.txt"
)

busted_orb_hogs_list = (
    pd.read_csv(busted_orb_hogs_path, header=None)[0]
    .dropna()
    .astype(str)
    .str.strip()
)
busted_orb_hogs_list = busted_orb_hogs_list[busted_orb_hogs_list != ""].tolist()

# overlap with HOG index in busted_ph_hits_df
overlap_hogs = busted_ph_hits_df.index.intersection(busted_orb_hogs_list)

print(f"HOGs in file: {len(busted_orb_hogs_list)}")
print(f"HOGs in busted_ph_hits_df: {len(busted_ph_hits_df.index)}")
print(f"Overlap: {len(overlap_hogs)}")
overlap_hogs.tolist()[:10]

HOGs in file: 96
HOGs in busted_ph_hits_df: 93
Overlap: 24

['N5.HOG0064007',
 'N5.HOG0037858',
 'N5.HOG0062008',
 'N5.HOG0068073',
 'N5.HOG0060652',
 'N5.HOG0056632',
 'N5.HOG0032852',
 'N5.HOG0060473',
 'N5.HOG0033769',
 'N5.HOG0061780']

In [7]:
# Load the saved BUSTED-PH-rev results
busted_ph_rev_result = BustedPhResult.load_from_pickle(str(hyphy_results + "busted_ph_rev_results.pkl"))
busted_ph_rev_result_fltrd = busted_ph_rev_result.filter_omega(10000)
busted_ph_rev_hits_df = busted_ph_rev_result_fltrd.get_significant_results()
busted_ph_rev_hits_df['foreground'] = 'non-orbweavers'
busted_ph_rev_hits_df = move_column(busted_ph_rev_hits_df, 'foreground', 0)  # Move 'foreground' column to the front
busted_ph_rev_hits_df.drop(columns=['result'], inplace=True)  # Drop result column
busted_ph_rev_hits_df

/var/folders/50/5g9n3tts73d9t0l7x7fh2rx00000gp/T/ipykernel_33534/1011142091.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  busted_ph_rev_hits_df['foreground'] = 'non-orbweavers'

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0059647,non-orbweavers,0.000000,199.312524,0.500000,0.000000,1.303733e-09,50.129547,0.214145,0.194163,0.012272,0.506622,0.327546,0.490094,25048.011234,0.003284,0.000007,0.491375,0.197839,0.442325,1.000000,0.066300,82.433873,0.153813
N5.HOG0059162,non-orbweavers,0.000334,14.624765,0.500000,0.000000,1.337493e-03,19.842840,0.055725,0.047507,0.000000,0.000853,0.049085,0.997870,222.963619,0.001277,0.012491,0.517452,0.054831,0.466754,1.000000,0.015794,0.333618,0.047850
N5.HOG0047848,non-orbweavers,0.000043,18.745455,0.500000,0.000000,9.557485e-04,20.619345,0.105105,0.161232,0.000000,0.701083,0.125313,0.298330,393.914065,0.000587,0.006878,0.868193,0.474539,0.131807,0.506917,0.000000,0.268548,0.068519
N5.HOG0063971,non-orbweavers,0.000000,102.747636,0.191702,1.917329,1.196849e-06,35.497771,0.170064,0.162002,0.000000,0.383219,0.230648,0.613126,71295.094259,0.003655,0.043728,0.303971,0.083198,0.603464,1.306522,0.092566,260.719634,0.184438
N5.HOG0060034,non-orbweavers,0.003962,9.675863,0.393941,0.476816,6.303230e-05,26.777215,0.114910,0.123684,0.000000,0.029057,0.040354,0.952268,1.981266,0.018675,0.000000,0.595994,0.104636,0.366482,1.094276,0.037524,0.075429,0.079409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0059302,non-orbweavers,0.000000,172.054793,0.147904,2.436096,0.000000e+00,150.891145,0.214680,0.138669,0.090953,0.925501,0.092234,0.055359,583.997366,0.019140,0.055118,0.835128,0.055638,0.115320,1.519702,0.049552,11.267098,0.127751
N5.HOG0069361,non-orbweavers,0.000000,86.252659,0.500000,0.000000,2.216637e-08,44.094013,0.000025,0.000017,0.000000,0.560835,0.239895,0.430389,31096.071854,0.008776,0.000000,0.550003,0.064982,0.317284,0.834182,0.132713,273.009285,0.131325
N5.HOG0022097,non-orbweavers,0.000385,14.340682,0.416242,0.366682,5.013023e-11,57.018385,0.206016,0.190054,0.002126,0.716543,0.565311,0.282970,334.274233,0.000486,0.001392,0.807633,0.655649,0.192054,30.132889,0.000313,0.324074,0.136486
N5.HOG0066569,non-orbweavers,0.000091,17.218049,0.500000,0.000000,5.063692e-07,37.363624,0.015114,0.006381,0.009473,0.996193,1.000000,0.003242,121.156902,0.000566,0.002831,0.985232,0.045644,0.011594,0.851932,0.003174,0.081197,0.006022
N5.HOG0063677,non-orbweavers,0.000004,23.454576,0.499154,0.003385,1.559421e-02,14.002394,0.164763,0.198686,0.000372,0.642887,0.183646,0.356496,433890.703824,0.000617,0.004784,0.679048,0.159223,0.296341,1.193221,0.024611,267.701150,0.079799

In [8]:
busted_orb_hogs_path = os.path.join(
    repo_root,
    "results/significant_gene_id_lists/before_tet_fix/busted_ph_nonorb_hogs.txt"
)

busted_nonorb_hogs_list = (
    pd.read_csv(busted_orb_hogs_path, header=None)[0]
    .dropna()
    .astype(str)
    .str.strip()
)
busted_nonorb_hogs_list = busted_nonorb_hogs_list[busted_nonorb_hogs_list != ""].tolist()

# overlap with HOG index in busted_ph_hits_df
overlap_hogs = busted_ph_rev_hits_df.index.intersection(busted_nonorb_hogs_list)

print(f"HOGs in file: {len(busted_nonorb_hogs_list)}")
print(f"HOGs in busted_ph_rev_hits_df: {len(busted_ph_rev_hits_df.index)}")
print(f"Overlap: {len(overlap_hogs)}")
overlap_hogs.tolist()[:10]

HOGs in file: 196
HOGs in busted_ph_rev_hits_df: 235
Overlap: 88

['N5.HOG0047848',
 'N5.HOG0063971',
 'N5.HOG0035032',
 'N5.HOG0064953',
 'N5.HOG0044950',
 'N5.HOG0038057',
 'N5.HOG0066290',
 'N5.HOG0045696',
 'N5.HOG0057813',
 'N5.HOG0066882']

In [9]:
all_busted_hits_df = pd.concat([busted_ph_hits_df, busted_ph_rev_hits_df])
all_busted_hits_df

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0027399,orbweavers,7.317358e-04,13.053888,0.500000,-5.188044,0.000000e+00,91.381079,0.000061,0.000028,0.000000,0.342811,0.283104,0.605572,4.819836,0.051617,0.000000,0.371896,0.129794,0.568777,2.031410,0.059327,0.420223,0.194342
N5.HOG0067687,orbweavers,1.004369e-02,7.815326,0.100755,3.203833,1.230178e-02,14.582833,0.179252,0.165886,0.071938,0.823210,0.637933,0.174763,32.915611,0.002027,0.000000,0.352128,0.170137,0.615790,1.807669,0.032082,0.237421,0.162762
N5.HOG0046830,orbweavers,2.882947e-08,33.337441,0.197147,1.861315,9.025339e-06,31.081779,0.016357,0.018601,0.002168,0.925907,0.165569,0.073707,146.613468,0.000386,0.010733,0.980653,0.024182,0.012755,1.409533,0.006592,0.070794,0.020126
N5.HOG0064451,orbweavers,4.321191e-02,4.896984,0.500000,0.000000,2.590683e-11,58.408424,0.000040,0.000027,0.020711,0.643359,0.223796,0.353431,6.376223,0.003211,0.000000,0.234975,0.056956,0.737757,1.000000,0.027268,0.112893,0.069287
N5.HOG0064007,orbweavers,1.627531e-02,6.849918,0.500000,0.000000,6.157777e-05,26.829322,0.064759,0.078682,0.007946,0.729061,0.041205,0.270505,44.880916,0.000434,0.000000,0.114812,0.019444,0.862158,0.817365,0.023030,0.036434,0.035587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0059302,non-orbweavers,0.000000e+00,172.054793,0.147904,2.436096,0.000000e+00,150.891145,0.214680,0.138669,0.090953,0.925501,0.092234,0.055359,583.997366,0.019140,0.055118,0.835128,0.055638,0.115320,1.519702,0.049552,11.267098,0.127751
N5.HOG0069361,non-orbweavers,0.000000e+00,86.252659,0.500000,0.000000,2.216637e-08,44.094013,0.000025,0.000017,0.000000,0.560835,0.239895,0.430389,31096.071854,0.008776,0.000000,0.550003,0.064982,0.317284,0.834182,0.132713,273.009285,0.131325
N5.HOG0022097,non-orbweavers,3.845303e-04,14.340682,0.416242,0.366682,5.013023e-11,57.018385,0.206016,0.190054,0.002126,0.716543,0.565311,0.282970,334.274233,0.000486,0.001392,0.807633,0.655649,0.192054,30.132889,0.000313,0.324074,0.136486
N5.HOG0066569,non-orbweavers,9.122589e-05,17.218049,0.500000,0.000000,5.063692e-07,37.363624,0.015114,0.006381,0.009473,0.996193,1.000000,0.003242,121.156902,0.000566,0.002831,0.985232,0.045644,0.011594,0.851932,0.003174,0.081197,0.006022
N5.HOG0063677,non-orbweavers,4.035280e-06,23.454576,0.499154,0.003385,1.559421e-02,14.002394,0.164763,0.198686,0.000372,0.642887,0.183646,0.356496,433890.703824,0.000617,0.004784,0.679048,0.159223,0.296341,1.193221,0.024611,267.701150,0.079799

In [10]:
busted_hits_locs = convert_hogs_to_locs(all_busted_hits_df, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
busted_hits_locs_fltrd = busted_hits_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
busted_hits_locs_fltrd = move_column(busted_hits_locs_fltrd, 'HOG', 0)
busted_hits_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
busted_hits_locs_fltrd

Processing HOGs: 100%|██████████| 328/328 [00:00<00:00, 4446.08it/s]

,HOG,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0027399,orbweavers,7.317358e-04,13.053888,0.500000,-5.188044,0.000000e+00,91.381079,0.000061,0.000028,0.000000,0.342811,0.283104,0.605572,4.819836,0.051617,0.000000,0.371896,0.129794,0.568777,2.031410,0.059327,0.420223,0.194342,129224947,GO:0000976 [Name: transcription regulatory reg...,uncharacterized LOC129224947
1,N5.HOG0067687,orbweavers,1.004369e-02,7.815326,0.100755,3.203833,1.230178e-02,14.582833,0.179252,0.165886,0.071938,0.823210,0.637933,0.174763,32.915611,0.002027,0.000000,0.352128,0.170137,0.615790,1.807669,0.032082,0.237421,0.162762,NaN,NaN,NaN
2,N5.HOG0046830,orbweavers,2.882947e-08,33.337441,0.197147,1.861315,9.025339e-06,31.081779,0.016357,0.018601,0.002168,0.925907,0.165569,0.073707,146.613468,0.000386,0.010733,0.980653,0.024182,0.012755,1.409533,0.006592,0.070794,0.020126,129225235,GO:0005737 [Name: cytoplasm]; GO:0051603 [Name...,E3 ubiquitin-protein ligase RNF123-like
3,N5.HOG0064451,orbweavers,4.321191e-02,4.896984,0.500000,0.000000,2.590683e-11,58.408424,0.000040,0.000027,0.020711,0.643359,0.223796,0.353431,6.376223,0.003211,0.000000,0.234975,0.056956,0.737757,1.000000,0.027268,0.112893,0.069287,129217593,GO:0004345 [Name: glucose-6-phosphate dehydrog...,glucose-6-phosphate 1-dehydrogenase-like
4,N5.HOG0064007,orbweavers,1.627531e-02,6.849918,0.500000,0.000000,6.157777e-05,26.829322,0.064759,0.078682,0.007946,0.729061,0.041205,0.270505,44.880916,0.000434,0.000000,0.114812,0.019444,0.862158,0.817365,0.023030,0.036434,0.035587,129230660,GO:0017147 [Name: Wnt-protein binding]; GO:009...,secreted frizzled-related protein 5-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,N5.HOG0059302,non-orbweavers,0.000000e+00,172.054793,0.147904,2.436096,0.000000e+00,150.891145,0.214680,0.138669,0.090953,0.925501,0.092234,0.055359,583.997366,0.019140,0.055118,0.835128,0.055638,0.115320,1.519702,0.049552,11.267098,0.127751,129222734,-,zinc finger MYND domain-containing protein 19-...
322,N5.HOG0069361,non-orbweavers,0.000000e+00,86.252659,0.500000,0.000000,2.216637e-08,44.094013,0.000025,0.000017,0.000000,0.560835,0.239895,0.430389,31096.071854,0.008776,0.000000,0.550003,0.064982,0.317284,0.834182,0.132713,273.009285,0.131325,129219392,-,uncharacterized LOC129219392
323,N5.HOG0022097,non-orbweavers,3.845303e-04,14.340682,0.416242,0.366682,5.013023e-11,57.018385,0.206016,0.190054,0.002126,0.716543,0.565311,0.282970,334.274233,0.000486,0.001392,0.807633,0.655649,0.192054,30.132889,0.000313,0.324074,0.136486,129219189,GO:0005737 [Name: cytoplasm]; GO:0007052 [Name...,transforming acidic coiled-coil-containing pro...
324,N5.HOG0066569,non-orbweavers,9.122589e-05,17.218049,0.500000,0.000000,5.063692e-07,37.363624,0.015114,0.006381,0.009473,0.996193,1.000000,0.003242,121.156902,0.000566,0.002831,0.985232,0.045644,0.011594,0.851932,0.003174,0.081197,0.006022,129230806,GO:0003924 [Name: GTPase activity]; GO:0010506...,Ras-related GTP binding A/B
325,N5.HOG0063677,non-orbweavers,4.035280e-06,23.454576,0.499154,0.003385,1.559421e-02,14.002394,0.164763,0.198686,0.000372,0.642887,0.183646,0.356496,433890.703824,0.000617,0.004784,0.679048,0.159223,0.296341,1.193221,0.024611,267.701150,0.079799,129233742,GO:0006457 [Name: protein folding]; GO:0000209...,RING-type E3 ubiquitin-protein ligase PPIL2-like

In [16]:
%autoreload 2
busted_df = get_ptep_description(busted_hits_locs_fltrd)
busted_df

,HOG,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
0,N5.HOG0027399,orbweavers,7.317358e-04,13.053888,0.500000,-5.188044,0.000000e+00,91.381079,0.000061,0.000028,0.000000,0.342811,0.283104,0.605572,4.819836,0.051617,0.000000,0.371896,0.129794,0.568777,2.031410,0.059327,0.420223,0.194342,129224947,GO:0000976 [Name: transcription regulatory reg...,uncharacterized LOC129224947,uncharacterized protein isoform X2
1,N5.HOG0067687,orbweavers,1.004369e-02,7.815326,0.100755,3.203833,1.230178e-02,14.582833,0.179252,0.165886,0.071938,0.823210,0.637933,0.174763,32.915611,0.002027,0.000000,0.352128,0.170137,0.615790,1.807669,0.032082,0.237421,0.162762,NaN,NaN,NaN,trithorax group protein osa
2,N5.HOG0046830,orbweavers,2.882947e-08,33.337441,0.197147,1.861315,9.025339e-06,31.081779,0.016357,0.018601,0.002168,0.925907,0.165569,0.073707,146.613468,0.000386,0.010733,0.980653,0.024182,0.012755,1.409533,0.006592,0.070794,0.020126,129225235,GO:0005737 [Name: cytoplasm]; GO:0051603 [Name...,E3 ubiquitin-protein ligase RNF123-like,E3 ubiquitin-protein ligase RNF123 isoform X1
3,N5.HOG0064451,orbweavers,4.321191e-02,4.896984,0.500000,0.000000,2.590683e-11,58.408424,0.000040,0.000027,0.020711,0.643359,0.223796,0.353431,6.376223,0.003211,0.000000,0.234975,0.056956,0.737757,1.000000,0.027268,0.112893,0.069287,129217593,GO:0004345 [Name: glucose-6-phosphate dehydrog...,glucose-6-phosphate 1-dehydrogenase-like,glucose-6-phosphate 1-dehydrogenase X
4,N5.HOG0064007,orbweavers,1.627531e-02,6.849918,0.500000,0.000000,6.157777e-05,26.829322,0.064759,0.078682,0.007946,0.729061,0.041205,0.270505,44.880916,0.000434,0.000000,0.114812,0.019444,0.862158,0.817365,0.023030,0.036434,0.035587,129230660,GO:0017147 [Name: Wnt-protein binding]; GO:009...,secreted frizzled-related protein 5-like,secreted frizzled-related protein 5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
321,N5.HOG0059302,non-orbweavers,0.000000e+00,172.054793,0.147904,2.436096,0.000000e+00,150.891145,0.214680,0.138669,0.090953,0.925501,0.092234,0.055359,583.997366,0.019140,0.055118,0.835128,0.055638,0.115320,1.519702,0.049552,11.267098,0.127751,129222734,-,zinc finger MYND domain-containing protein 19-...,zinc finger MYND domain-containing protein 19 ...
322,N5.HOG0069361,non-orbweavers,0.000000e+00,86.252659,0.500000,0.000000,2.216637e-08,44.094013,0.000025,0.000017,0.000000,0.560835,0.239895,0.430389,31096.071854,0.008776,0.000000,0.550003,0.064982,0.317284,0.834182,0.132713,273.009285,0.131325,129219392,-,uncharacterized LOC129219392,uncharacterized protein
323,N5.HOG0022097,non-orbweavers,3.845303e-04,14.340682,0.416242,0.366682,5.013023e-11,57.018385,0.206016,0.190054,0.002126,0.716543,0.565311,0.282970,334.274233,0.000486,0.001392,0.807633,0.655649,0.192054,30.132889,0.000313,0.324074,0.136486,129219189,GO:0005737 [Name: cytoplasm]; GO:0007052 [Name...,transforming acidic coiled-coil-containing pro...,transforming acidic coiled-coil-containing pro...
324,N5.HOG0066569,non-orbweavers,9.122589e-05,17.218049,0.500000,0.000000,5.063692e-07,37.363624,0.015114,0.006381,0.009473,0.996193,1.000000,0.003242,121.156902,0.000566,0.002831,0.985232,0.045644,0.011594,0.851932,0.003174,0.081197,0.006022,129230806,GO:0003924 [Name: GTPase activity]; GO:0010506...,Ras-related GTP binding A/B,ras-related GTP-binding protein A
325,N5.HOG0063677,non-orbweavers,4.035280e-06,23.454576,0.499154,0.003385,1.559421e-02,14.002394,0.164763,0.198686,0.000372,0.642887,0.183646,0.356496,433890.703824,0.000617,0.004784,0.679048,0.159223,0.296341,1.193221,0.024611,267.701150,0.079799,129233742,GO:0006457 [Name: protein folding]; GO:0000209...,RING-type E3 ubiquitin-protein ligase PPIL2-like,RING-type E3 ubiquitin-protein ligase PPIL2

In [17]:
busted_df.to_excel(os.path.join(repo_root, "results/Supplementary_Table_4_BUSTED_PH.xlsx"), index=False)

In [28]:
relax_hits_locs = convert_hogs_to_locs(relax_hits_df, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
relax_hits_locs_fltrd = relax_hits_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
relax_hits_locs_fltrd = move_column(relax_hits_locs_fltrd, 'HOG', 0)
relax_hits_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
relax_df = get_ptep_description(relax_hits_locs_fltrd)
relax_df

Processing HOGs: 100%|██████████| 1429/1429 [00:00<00:00, 55979.94it/s]

,HOG,result,foreground,p_value,k,LRT,MG94xREV_ω_reference,MG94xREV_ω_test,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
0,N5.HOG0067228,relaxed,non-orbweavers,5.069278e-13,0.031330,52.178060,2.038968e-05,1.110457e+00,0.000000,0.843804,0.389555,0.063292,1.000000,0.092904,0.000000,0.843804,8.541217e-14,0.063292,1.000000,0.092904,0.117560,0.092904,129223414,GO:0005737 [Name: cytoplasm]; GO:0016925 [Name...,activator of SUMO 1,SUMO-activating enzyme subunit 1
1,N5.HOG0059719,intensified,non-orbweavers,7.772996e-06,1.108589,19.992907,7.502321e-02,6.447394e-02,0.037770,0.404703,0.046494,0.595297,1.964199,0.000000,0.052061,0.404703,6.279584e-02,0.595297,1.838516,0.000000,0.042963,0.058452,129227349,GO:0005737 [Name: cytoplasm]; GO:0042803 [Name...,serine hydroxymethyltransferase-like,serine hydroxymethyltransferase
2,N5.HOG0063256,intensified,non-orbweavers,7.733957e-04,1.136232,11.304017,6.619584e-02,5.929911e-02,0.000000,0.810437,0.086857,0.189563,1.002673,0.000000,0.000000,0.810437,1.164229e-01,0.189563,1.002352,0.000000,0.016465,0.022069,129224590,GO:0003924 [Name: GTPase activity]; GO:0005737...,GPN-loop GTPase 2-like,GPN-loop GTPase 2 isoform X2
3,N5.HOG0053197,intensified,non-orbweavers,1.414873e-05,1.212468,18.848973,1.444946e-07,1.613655e-07,0.049339,0.277338,0.065543,0.722662,1.003152,0.000000,0.083597,0.277338,1.056603e-01,0.722662,1.002599,0.000000,0.061049,0.099541,129220170,GO:0005634 [Name: nucleus]; GO:0032502 [Name: ...,molecular chaperone MKKS-like,chromatin accessibility complex protein 1
4,N5.HOG0038544,intensified,non-orbweavers,7.216346e-05,1.097131,15.753260,2.865946e+00,4.260989e-06,0.053668,0.706817,0.054859,0.293183,1.002547,0.000000,0.069531,0.706817,7.093601e-02,0.293183,1.002321,0.000000,0.054018,0.069943,NaN,NaN,NaN,frizzled-4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,N5.HOG0067687,intensified,non-orbweavers,9.106801e-04,1.152606,11.000893,1.822100e-01,1.666336e-01,0.099776,0.262095,0.107294,0.737905,2.158247,0.000000,0.135381,0.262095,1.441878e-01,0.737905,1.949243,0.000000,0.105324,0.141880,NaN,NaN,NaN,trithorax group protein osa
1425,N5.HOG0064241,intensified,non-orbweavers,2.168763e-02,1.117584,5.270673,5.236016e-05,4.930010e-01,0.000000,0.302399,0.152434,0.697601,1.862849,0.000000,0.000000,0.302399,1.857939e-01,0.697601,1.744823,0.000000,0.106338,0.129610,129227186,"GO:0006352 [Name: DNA-templated transcription,...",TATA box-binding protein-like 1,TATA box-binding protein-like 1
1426,N5.HOG0066936,intensified,non-orbweavers,6.469430e-05,1.122134,15.960024,1.096739e-07,8.254460e-01,0.012756,0.285540,0.088955,0.714460,1.001747,0.000000,0.020506,0.285540,1.157564e-01,0.714460,1.001557,0.000000,0.067197,0.088559,129234669,GO:0009058 [Name: biosynthetic process]; GO:00...,eukaryotic translation initiation factor 2B su...,translation initiation factor eIF2B subunit gamma
1427,N5.HOG0060161,intensified,non-orbweavers,1.160829e-03,1.145080,10.551673,5.080422e-02,6.864197e-02,0.000000,0.876649,1.000000,0.118220,2318.115008,0.005132,0.000000,0.876649,1.000000e+00,0.118220,868.514944,0.005132,12.013916,4.575112,129226064,GO:0005515 [Name: protein binding]; GO:0007098...,partitioning defective protein 6,partitioning defective 6 homolog gamma
1428,N5.HOG0066090,relaxed,non-orbweavers,2.047802e-03,0.885224,9.506187,5.122371e-01,1.587455e-07,0.058717,0.011892,0.150626,0.988108,1.001382,0.000000,0.040656,0.011892,1.178442e-01,0.988108,1.001562,0.000000,0.149533,0.116926,129218525,-,putative uncharacterized protein DDB_G0271982,tubulin glycylase 3C

In [ ]:
relax_df.to_excel(os.path.join(repo_root, "results/Supplementary_Table_3_RELAX_hits.xlsx"), index=False)

## Permutation test results

before

In [8]:
%autoreload 2
perm_test_results_dir = os.path.join(repo_root, "results/odds_ratio_test/Results_Apr16/Run1_occ_30-88_10000x_all_orb/")
perm_results_old = pd.read_csv(os.path.join(perm_test_results_dir, "fltrd_hits.csv"), index_col="HOG")

perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_fg"), "Loss more likely in orb-weavers", None)
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_bg"), "Loss more likely in non-orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("dup_fg"), "Duplication more likely in orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("dup_bg"), "Duplication more likely in non-orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_bg"), "Loss more likely in orb-weavers, duplication more likely in non-orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_fg"), "Loss more likely in non-orb-weavers, duplication more likely in orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_fg"), "Loss more likely in orb-weavers, duplication more likely in orb-weavers", perm_results_old["Result"])
perm_results_old["Result"] = np.where(perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_bg"), "Loss more likely in non-orb-weavers, duplication more likely in non-orb-weavers", perm_results_old["Result"])

perm_results_old = move_column(perm_results_old, "Result", 0)  # Move 'Result' column to the front
perm_results_old["LOR outside permuted avg thresholds"] = np.where(perm_results_old["Significant by avgd thresholds"].notnull(), "Yes", "No")
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_fg, dup_bg")), "Yes for both tests", perm_results_old["LOR outside permuted avg thresholds"])

perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_bg, dup_fg")), "Yes for both tests", perm_results_old["LOR outside permuted avg thresholds"])


perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_fg, dup_fg")), "Yes for both tests", perm_results_old["LOR outside permuted avg thresholds"])


perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results_old["LOR outside permuted avg thresholds"])
perm_results_old["LOR outside permuted avg thresholds"] = np.where((perm_results_old["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results_old["Significant by avgd thresholds"].str.contains("loss_bg, dup_bg")), "Yes for both tests", perm_results_old["LOR outside permuted avg thresholds"])


perm_results_old = move_column(perm_results_old, "LOR outside permuted avg thresholds", 4)  # Move 'LOR outside permuted avg thresholds' column to the front
perm_results_old = perm_results_old.drop(columns=["Significant by avgd thresholds", "Significant by permulation"])
perm_results_old = perm_results_old.rename(columns={
    "P-value loss more likely in fg": "P-value, loss more likely in orb-weavers", 
    "P-value loss more likely in bg": "P-value, loss more likely in non-orb-weavers", 
    "P-value duplication more likely in fg": "P-value, duplication more likely in orb-weavers", 
    "P-value duplication more likely in bg": "P-value, duplication more likely in non-orb-weavers", 
    })
perm_results_old

,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers"
HOG,,,,,,,,,
N5.HOG0001041,Loss more likely in orb-weavers,46,2.288042,-0.281735,No,0.0038,0.9962,0.5328,0.4672
N5.HOG0001609,Loss more likely in non-orb-weavers,49,-2.841587,2.391485,No,0.9605,0.0395,0.0747,0.9253
N5.HOG0001627,"Loss more likely in orb-weavers, duplication m...",33,2.048043,-4.020457,No for loss; yes for duplication,0.0449,0.9551,0.9745,0.0253
N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.823601,1.854638,Yes,0.9996,0.0004,0.3311,0.6686
N5.HOG0002072,Loss more likely in orb-weavers,52,3.473733,-0.762726,Yes,0.0108,0.9892,0.7989,0.2011
...,...,...,...,...,...,...,...,...,...
N5.HOG0073114,Loss more likely in orb-weavers,36,1.310443,-1.206534,No,0.0218,0.9782,0.7961,0.2038
N5.HOG0073157,Loss more likely in non-orb-weavers,34,-3.186391,1.988284,Yes,0.9576,0.0424,0.1151,0.8846
N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.038058,0.724732,No,0.9929,0.0071,0.1394,0.8606
N5.HOG0073251,Loss more likely in non-orb-weavers,33,-3.434295,1.656853,Yes,0.9866,0.0134,0.2178,0.7822
N5.HOG0073526,Loss more likely in non-orb-weavers,31,-2.277030,1.982725,No,0.9679,0.0321,0.1323,0.8675

Reformat results table

In [10]:
%autoreload 2
perm_test_results_dir = os.path.join(repo_root, "results/odds_ratio_test/Results_Jul22/Run1_occ_30-88_10000x/")
perm_results = pd.read_csv(os.path.join(perm_test_results_dir, "fltrd_hits.csv"), index_col="HOG")

perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg"), "Loss more likely in orb-weavers", None)
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg"), "Loss more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("dup_fg"), "Duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("dup_bg"), "Duplication more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg"), "Loss more likely in orb-weavers, duplication more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg"), "Loss more likely in non-orb-weavers, duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg"), "Loss more likely in orb-weavers, duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg"), "Loss more likely in non-orb-weavers, duplication more likely in non-orb-weavers", perm_results["Result"])

perm_results = move_column(perm_results, "Result", 0)  # Move 'Result' column to the front
perm_results["LOR outside permuted avg thresholds"] = np.where(perm_results["Significant by avgd thresholds"].notnull(), "Yes", "No")
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg, dup_bg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])

perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg, dup_fg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg, dup_fg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg, dup_bg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results = move_column(perm_results, "LOR outside permuted avg thresholds", 4)  # Move 'LOR outside permuted avg thresholds' column to the front
perm_results = perm_results.drop(columns=["Significant by avgd thresholds", "Significant by permulation"])
perm_results = perm_results.rename(columns={
    "P-value loss more likely in fg": "P-value, loss more likely in orb-weavers", 
    "P-value loss more likely in bg": "P-value, loss more likely in non-orb-weavers", 
    "P-value duplication more likely in fg": "P-value, duplication more likely in orb-weavers", 
    "P-value duplication more likely in bg": "P-value, duplication more likely in non-orb-weavers", 
    })
perm_results

,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers"
HOG,,,,,,,,,
N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202
N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127
N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880
N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964
N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416
...,...,...,...,...,...,...,...,...,...
N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887
N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850
N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940
N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296
N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558

In [17]:
# intersection of indices
common_idx = perm_results.index.intersection(perm_results_old.index)
intersection_df = perm_results.loc[common_idx]

# quick summary
print(f"Common HOGs: {len(common_idx)}")
intersection_df.head()

Common HOGs: 999

,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers"
HOG,,,,,,,,,
N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202
N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127
N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880
N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964
N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416

In [12]:
%autoreload 2
perm_locs = convert_hogs_to_locs(perm_results, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
perm_locs_filtered = perm_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
perm_locs_filtered = move_column(perm_locs_filtered, 'HOG', 0)
perm_locs_filtered.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
perm_locs_filtered

Processing HOGs: 100%|██████████| 1482/1482 [00:00<00:00, 61000.57it/s]

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202,NaN,NaN,NaN
1,N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127,NaN,NaN,NaN
2,N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880,129233975,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like
3,N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964,129217362,GO:0008010 [Name: structural constituent of ch...,proteoglycan 4-like
4,N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416,129221291,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887,NaN,NaN,NaN
1478,N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850,NaN,NaN,NaN
1479,N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940,129221249,-,cuticle protein 38-like
1480,N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296,NaN,NaN,NaN
1481,N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558,NaN,NaN,NaN

In [13]:
%autoreload 2
perm_df = get_ptep_description(perm_locs_filtered)
perm_df

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
0,N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202,NaN,NaN,NaN,gastrula zinc finger protein XlCGF7.1
1,N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127,NaN,NaN,NaN,speckle-type POZ protein
2,N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880,129233975,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like,cuticle protein 10.9
3,N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964,129217362,GO:0008010 [Name: structural constituent of ch...,proteoglycan 4-like,uncharacterized protein
4,N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416,129221291,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like,cuticle protein 10.9-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887,NaN,NaN,NaN,uncharacterized protein
1478,N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850,NaN,NaN,NaN,DNA mismatch repair protein Mlh3
1479,N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940,129221249,-,cuticle protein 38-like,cuticle protein 63-like
1480,N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296,NaN,NaN,NaN,NO_HIT
1481,N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558,NaN,NaN,NaN,NO_HIT

In [18]:
perm_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_5_OddsRatioTest_hits.xlsx'), index=False)

In [14]:
previous_interesting = pd.read_csv(os.path.join(repo_root, 'data/interesting_hits.txt'), header=None, names=['HOG'])

In [15]:
previous_interesting_df = perm_df[perm_df['HOG'].isin(previous_interesting['HOG'])]
previous_interesting_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_6_OddsRatioTest_interesting_hits.xlsx'), index=False)
previous_interesting_df

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
43,N5.HOG0007453,Loss more likely in orb-weavers,50,1.946870,-1.544702,No,0.0165,0.9835,0.9383,0.0617,129216356,GO:0043005 [Name: neuron projection],lachesin-like,lachesin
113,N5.HOG0014159,Duplication more likely in orb-weavers,78,0.169513,2.093720,No,0.3622,0.6378,0.0394,0.9606,129217691,GO:0005109 [Name: frizzled binding]; GO:000557...,protein Wnt-16-like,protein Wnt-16-like precursor
175,N5.HOG0018539,Loss more likely in non-orb-weavers,84,-1.480659,0.395499,No,0.9706,0.0294,0.3609,0.6391,129230744,GO:0005737 [Name: cytoplasm]; GO:0097320 [Name...,protein kinase C and casein kinase substrate i...,protein kinase C and casein kinase substrate i...
228,N5.HOG0022330,Loss more likely in non-orb-weavers,50,-2.722522,2.141345,No,0.9938,0.0062,0.0579,0.9421,129217545,GO:0046777 [Name: protein autophosphorylation]...,dual specificity tyrosine-phosphorylation-regu...,dual specificity tyrosine-phosphorylation-regu...
260,N5.HOG0024065,"Loss more likely in non-orb-weavers, duplicati...",66,-2.850324,2.026191,Yes for loss; no for duplication,0.9583,0.0417,0.0115,0.9885,129218972,GO:0005737 [Name: cytoplasm]; GO:0006468 [Name...,uncharacterized LOC129218972,uncharacterized protein
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1124,N5.HOG0063077,Duplication more likely in non-orb-weavers,96,-1.260838,-1.784818,No,0.7608,0.2392,0.9733,0.0267,129219268,GO:0043025 [Name: neuronal cell body]; GO:0045...,fragile X messenger ribonucleoprotein 1 homolog,RNA-binding protein FXR1
1268,N5.HOG0066939,Loss more likely in non-orb-weavers,69,-2.650704,0.939259,No,0.9714,0.0286,0.0699,0.9301,129228009,GO:0015250 [Name: water channel activity]; GO:...,neurogenic protein big brain-like,aquaporin AQPAe.a
1275,N5.HOG0067099,Duplication more likely in non-orb-weavers,56,2.257462,-2.780946,Yes,0.0830,0.9170,0.9689,0.0311,129225034,GO:0005737 [Name: cytoplasm]; GO:0019901 [Name...,Cdk5 activator-like protein,cyclin-dependent kinase 5 activator 1 isoform X1
1347,N5.HOG0068715,Loss more likely in non-orb-weavers,83,-2.162736,0.712293,No,0.9910,0.0090,0.2442,0.7558,129232140,GO:0004930 [Name: G-protein coupled receptor a...,probable G-protein coupled receptor AH9.1,probable G-protein coupled receptor AH9.1
1354,N5.HOG0068937,Loss more likely in orb-weavers,78,1.716305,-0.226392,No,0.0063,0.9937,0.5667,0.4333,129225023,GO:0007218 [Name: neuropeptide signaling pathway],FMRFamide propeptide,myomodulin neuropeptides

## Spider accessions and BUSCO scores

In [36]:
buscos = pd.read_csv(f'{data}/orthorun_list_fams_busco90.csv')
accessions = pd.read_csv(f'{data}/txptome_accessions.csv')
accessions.drop(columns=['Infraorder', 'Family', 'Web_Type', 'Cribellum'], inplace=True)

buscos_accessions = pd.merge(buscos, accessions, on='Species', how='left')

buscos_accessions.drop_duplicates(inplace=True)
buscos_accessions.dropna(how='any', inplace=True)
buscos_accessions.reset_index(drop=True, inplace=True)
# Collapse rows: group by all columns except 'Accession', join 'Accession' values as comma-separated string
buscos_accessions.rename(columns={'Single': 'Single_copy_BUSCOs', 'Duplicated': 'Duplicated_BUSCOs', 'Total': 'Total_BUSCOs'}, inplace=True)
buscos_accessions.shape[0]

102

In [37]:
buscos_accessions.to_excel(f'{results}/Supplementary_Table_1_SpiderAccessions_BUSCOs.xlsx', index=False)

In [38]:
# Count rows with NaN in the 'Accession' column before collapsing
num_nan_accession = buscos_accessions['Accession'].isna().sum()
print(f"Rows with NaN in 'Accession': {num_nan_accession}")

Rows with NaN in 'Accession': 0

## N5 HOGs

this is just to make the format match the others

In [39]:
n5_hogs = pd.read_csv(f'{data}/N5.tsv', sep='\t')
n5_hogs.to_excel(f'{results}/Supplementary_Table_2_Entelegyne_HOGs.xlsx', index=False)

/var/folders/h8/wkfyd5dj3nnd_smftqfplclh0000gn/T/ipykernel_19504/1880799938.py:1: DtypeWarning: Columns (0: Acroaspis_sp_IDV6688, 1: Acrosomoides_sp_IDV7426, 2: Ainerigone_saitoi, 3: Ambicodamus_IDV6680, 4: Araneus_inustus, 5: Arcuphantes_paiki, 6: Arcuphantes_tamaensis, 7: Arcuphantes_uenoi, 8: Argiope_aetheroides, 9: Argiope_bruennichi, 10: Argiope_keyserlingi, 11: Argyrodes_flavescens, 12: Argyrodes_miniaceus, 13: Backobourkia_brouni, 14: Baryphymula_kamakuraensis, 15: Caerostris_darwini, 16: Caerostris_extrusa, 17: Chrysso_octomaculata, 18: Clubiona_robusta, 19: Cryptachaea_gigantipes, 20: Cyclosa_octotuberculata, 21: Cyrtarachne_bufo, 22: Cyrtophora_cicatrosa, 23: Deinopis_sp_IDV6783, 24: Deinopis_sp_IDV7365, 25: Desis_marina, 26: Diaea_subdola, 27: Doenitzius_peniculus, 28: Doenitzius_pruvus, 29: Dolophones_sp_IDV6683, 30: Drapetisca_socialis, 31: Ebrechtella_tricuspidata, 32: Eriophora_pustulosa, 33: Floronia_bucculenta, 34: Gnathonarium_exsiccatum, 35: Helpis_minitabunda, 36: Hypselistes_asiaticus, 37: Hypsosinga_pygmaea, 38: Larinia_phthisica, 39: Lariniaria_argiopiformis, 40: Larinioides_cornutus, 41: Latrodectus_hasseltii, 42: Lehtinelagia_evanida, 43: Leucauge_dromedari, 44: Mesida_sp_IDV5268, 45: Metazygia_zilloides, 46: Metleucauge_yunohamensis, 47: Microbathyphantes_tateyamaensis, 48: Neoantistea_quelpartensis, 49: Neon_minutus, 50: Neoscona_adianta, 51: Neoscona_nautica, 52: Neoscona_scylla, 53: Neoscona_subpullata, 54: Neoscona_theisi, 55: Neriene_clathrata, 56: Neriene_oidedicata, 57: Nuctenea_umbratica, 58: Ordgarius_hobsoni, 59: Ordgarius_sexspinosus, 60: Oxytate_striatipes, 61: Ozyptila_nongae, 62: Parasteatoda_culicivora, 63: Paratheuma_awasensis, 64: Pardosa_graminea, 65: Pharta_brevipalpus, 66: Phonognatha_graeffei, 67: Phrurolithus_coreanus, 68: Piratula_tanakai, 69: Plebs_sachalinensis, 70: Poecilopachys_australasia, 71: Psechrus_IDV5238, 72: Pseudomicrargus_latitegulatus, 73: Rhomphaea_labiata, 74: Robertus_nojimai, 75: Ryojius_japonicus, 76: Saaristoa_nipponica, 77: Saitonia_ojiroensis, 78: Steatoda_grossa, 79: Stephanopis_cambridgei, 80: Stertinius_kumadai, 81: Syedra_oii, 82: Tekellina_sadamotoi, 83: Tetragnatha_brevignatha, 84: Tetragnatha_extensa, 85: Tetragnatha_filiciphilia, 86: Tetragnatha_mandibulata) have mixed types. Specify dtype option on import or set low_memory=False.
  n5_hogs = pd.read_csv(f'{data}/N5.tsv', sep='\t')

## PhyloGLM results

In [19]:
phyloglm = pd.read_csv(f'{results}/phyloglm/phyloglm_qvals.csv', index_col="HOG")
phyloglm

,error,coef_.Intercept._Estimate,coef_.Intercept._StdErr,coef_.Intercept._z.value,coef_.Intercept._p.value,coef_orb_weavingTRUE_Estimate,coef_orb_weavingTRUE_StdErr,coef_orb_weavingTRUE_z.value,coef_orb_weavingTRUE_p.value,qvalue
HOG,,,,,,,,,,
N5.HOG0000042,NaN,-1.824872,1.886352,-0.967408,0.333340,-0.501943,1.173294,-0.427807,0.668792,0.611945
N5.HOG0000052,NaN,-0.856693,0.819677,-1.045159,0.295949,0.307564,0.362892,0.847535,0.396697,0.464750
N5.HOG0000147,NaN,-1.239375,0.740910,-1.672775,0.094372,0.030086,0.340894,0.088255,0.929674,0.696301
N5.HOG0000196,NaN,-0.863214,0.494447,-1.745817,0.080843,0.171416,0.220604,0.777031,0.437141,0.491348
N5.HOG0000276,NaN,-2.180273,1.272667,-1.713153,0.086684,0.537627,0.812604,0.661610,0.508221,0.532658
...,...,...,...,...,...,...,...,...,...,...
N5.HOG0073724,NaN,-0.935609,0.563660,-1.659881,0.096938,-0.639715,0.390120,-1.639791,0.101049,0.190854
N5.HOG0073740,NaN,-0.716498,0.376449,-1.903308,0.057000,0.121716,0.169320,0.718848,0.472235,0.513420
N5.HOG0073766,NaN,-1.630470,0.800970,-2.035620,0.041788,1.041255,0.419621,2.481418,0.013086,0.046133
N5.HOG0073773,NaN,-1.146885,0.522748,-2.193955,0.028239,0.500136,0.235999,2.119228,0.034071,0.090729
N5.HOG0073818,NaN,-0.788188,0.411475,-1.915519,0.055426,-0.090263,0.198029,-0.455806,0.648530,0.602811

In [20]:
phyloglm_sig = phyloglm[phyloglm['qvalue'] < 0.05].drop(columns=[
    'error', 'coef_.Intercept._Estimate', 'coef_.Intercept._StdErr', 'coef_.Intercept._z.value', 'coef_.Intercept._p.value'])
phyloglm_sig.rename(columns={
    'coef_orb_weavingTRUE_Estimate': 'Orb-weaving coefficient estimate',
    'coef_.coef_orb_weavingTRUE_StdErr': 'Orb-weaving coefficient standard error',
    'coef_.coef_orb_weavingTRUE_z.value': 'Orb-weaving coefficient z-value',
    'coef_.coef_orb_weavingTRUE_p.value': 'Orb-weaving coefficient p-value'
    }, inplace=True)

In [21]:
phyloglm_locs = convert_hogs_to_locs(phyloglm_sig, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
phyloglm_locs_fltrd = phyloglm_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
phyloglm_locs_fltrd = move_column(phyloglm_locs_fltrd, 'HOG', 0)
phyloglm_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
phyloglm_locs_fltrd

Processing HOGs: 100%|██████████| 2507/2507 [00:00<00:00, 98934.18it/s]

,HOG,Orb-weaving coefficient estimate,coef_orb_weavingTRUE_StdErr,coef_orb_weavingTRUE_z.value,coef_orb_weavingTRUE_p.value,qvalue,U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0000608,0.273735,0.071194,3.844943,0.000121,0.001440,129232144,GO:0000981 [Name: RNA polymerase II transcript...,zinc finger protein 596-like
1,N5.HOG0001051,-0.355112,0.141780,-2.504665,0.012257,0.043956,NaN,NaN,NaN
2,N5.HOG0001055,-0.856296,0.318821,-2.685826,0.007235,0.030491,129220793,GO:0000981 [Name: RNA polymerase II transcript...,zinc finger protein 484-like
3,N5.HOG0002047,1.126103,0.334118,3.370377,0.000751,0.005910,129219201,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like
4,N5.HOG0002053,0.800547,0.178541,4.483840,0.000007,0.000163,129227284,GO:0008010 [Name: structural constituent of ch...,adult-specific rigid cuticular protein 15.7-like
...,...,...,...,...,...,...,...,...,...
2502,N5.HOG0073277,0.660198,0.237229,2.782959,0.005387,0.024678,129219304,GO:0016020 [Name: membrane]; GO:0042246 [Name:...,ninjurin-B-like
2503,N5.HOG0073283,0.662456,0.199776,3.315995,0.000913,0.006776,129225051,-,uncharacterized LOC129225051
2504,N5.HOG0073483,0.636325,0.252186,2.523239,0.011628,0.042146,129221135,GO:0043087 [Name: regulation of GTPase activity],neurofibromin-like
2505,N5.HOG0073709,-0.572810,0.218613,-2.620203,0.008788,0.034901,129229743,GO:0070034 [Name: telomerase RNA binding]; GO:...,telomerase-binding protein EST1A-like
2506,N5.HOG0073766,1.041255,0.419621,2.481418,0.013086,0.046133,129219848,-,uncharacterized LOC129219848

In [22]:
phyloglm_df = get_ptep_description(phyloglm_locs_fltrd)
phyloglm_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_7_PhyloGLM_hits.xlsx'), index=False)
phyloglm_df

,HOG,Orb-weaving coefficient estimate,coef_orb_weavingTRUE_StdErr,coef_orb_weavingTRUE_z.value,coef_orb_weavingTRUE_p.value,qvalue,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
0,N5.HOG0000608,0.273735,0.071194,3.844943,0.000121,0.001440,129232144,GO:0000981 [Name: RNA polymerase II transcript...,zinc finger protein 596-like,zinc finger protein 888
1,N5.HOG0001051,-0.355112,0.141780,-2.504665,0.012257,0.043956,NaN,NaN,NaN,oocyte zinc finger protein XlCOF15-like isofor...
2,N5.HOG0001055,-0.856296,0.318821,-2.685826,0.007235,0.030491,129220793,GO:0000981 [Name: RNA polymerase II transcript...,zinc finger protein 484-like,zinc finger protein 271-like
3,N5.HOG0002047,1.126103,0.334118,3.370377,0.000751,0.005910,129219201,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like,cuticle protein 10.9
4,N5.HOG0002053,0.800547,0.178541,4.483840,0.000007,0.000163,129227284,GO:0008010 [Name: structural constituent of ch...,adult-specific rigid cuticular protein 15.7-like,adult-specific rigid cuticular protein 15.5
...,...,...,...,...,...,...,...,...,...,...
2502,N5.HOG0073277,0.660198,0.237229,2.782959,0.005387,0.024678,129219304,GO:0016020 [Name: membrane]; GO:0042246 [Name:...,ninjurin-B-like,ninjurin-2-like
2503,N5.HOG0073283,0.662456,0.199776,3.315995,0.000913,0.006776,129225051,-,uncharacterized LOC129225051,uncharacterized protein
2504,N5.HOG0073483,0.636325,0.252186,2.523239,0.011628,0.042146,129221135,GO:0043087 [Name: regulation of GTPase activity],neurofibromin-like,neurofibromin isoform X6
2505,N5.HOG0073709,-0.572810,0.218613,-2.620203,0.008788,0.034901,129229743,GO:0070034 [Name: telomerase RNA binding]; GO:...,telomerase-binding protein EST1A-like,LOW QUALITY PROTEIN: telomerase-binding protei...
2506,N5.HOG0073766,1.041255,0.419621,2.481418,0.013086,0.046133,129219848,-,uncharacterized LOC129219848,uncharacterized protein isoform X1

In [23]:
previous_interesting_pglm_df = phyloglm_df[phyloglm_df['HOG'].isin(previous_interesting['HOG'])]
previous_interesting_pglm_df

,HOG,Orb-weaving coefficient estimate,coef_orb_weavingTRUE_StdErr,coef_orb_weavingTRUE_z.value,coef_orb_weavingTRUE_p.value,qvalue,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit for the HOG
39,N5.HOG0007063,0.928897,0.292805,3.172408,0.001512,0.009702,129226340,GO:0005524 [Name: ATP binding]; GO:0035556 [Na...,receptor-type guanylate cyclase Gyc76C-like,receptor-type guanylate cyclase Gyc76C
45,N5.HOG0007453,-0.886271,0.254687,-3.479845,0.000502,0.004370,129216356,GO:0043005 [Name: neuron projection],lachesin-like,lachesin
122,N5.HOG0014431,-0.816211,0.290963,-2.805209,0.005028,0.023506,129228713,GO:0016020 [Name: membrane]; GO:0007186 [Name:...,G-protein coupled receptor Mth2-like,G-protein coupled receptor Mth2-like
349,N5.HOG0026939,-0.435990,0.136184,-3.201481,0.001367,0.009043,129223346,GO:0019001 [Name: guanyl nucleotide binding]; ...,guanine nucleotide-binding protein G(q) subuni...,guanine nucleotide-binding protein G(q) subuni...
353,N5.HOG0027166,0.731890,0.238427,3.069666,0.002143,0.012388,129218261,GO:0004672 [Name: protein kinase activity]; GO...,serine/threonine-protein kinase Nek4-like,uncharacterized protein isoform X2
...,...,...,...,...,...,...,...,...,...,...
1683,N5.HOG0063259,-0.553414,0.127124,-4.353331,0.000013,0.000265,129225143,GO:0000506 [Name: glycosylphosphatidylinositol...,Phosphatidylinositol glycan anchor biosynthesi...,phosphatidylinositol N-acetylglucosaminyltrans...
1805,N5.HOG0064389,0.472255,0.097118,4.862688,0.000001,0.000039,129233173,GO:0008254 [Name: 3'-nucleotidase activity]; G...,inositol monophosphatase 3-like,inositol monophosphatase 3
2177,N5.HOG0067680,-0.363030,0.080939,-4.485232,0.000007,0.000163,129230974,GO:0004930 [Name: G-protein coupled receptor a...,transmembrane protein adipocyte-associated 1-like,transmembrane protein adipocyte-associated 1 i...
2196,N5.HOG0067795,-0.326958,0.103626,-3.155163,0.001604,0.010089,129216741,GO:0006303 [Name: double-strand break repair v...,uncharacterized LOC129216741,DNA repair protein xrcc4
2309,N5.HOG0068937,-0.395375,0.116610,-3.390571,0.000697,0.005581,129225023,GO:0007218 [Name: neuropeptide signaling pathway],FMRFamide propeptide,myomodulin neuropeptides