# Format and save Supplementary Data Tables from raw data files.

Generates all supplementary data tables (see [results](results/)) except Supplementary Table 8, which is generated in [`Upset Plots.ipynb`](scripts/07_figures_tables/UpSet%20Plots.ipynb).

In [23]:
import os
import sys
import pandas as pd
import numpy as np
from scipy.stats import norm
!{sys.executable} -m pip install openpyxl

# Resolve repo root whether cwd is repo root, scripts/, or a stage subdirectory.
cwd = os.getcwd()
if os.path.basename(cwd) == "orb-selection":
    repo_root = cwd
elif os.path.basename(os.path.dirname(cwd)) == "orb-selection":
    repo_root = os.path.dirname(cwd)
elif os.path.basename(os.path.dirname(os.path.dirname(cwd))) == "orb-selection":
    repo_root = os.path.dirname(os.path.dirname(cwd))
else:
    repo_root = cwd

data = os.path.join(repo_root, "data")
results = os.path.join(repo_root, "results")

src_path = os.path.join(repo_root, "src")
stage03_path = os.path.join(repo_root, "scripts", "03_selection_tests")
stage04_path = os.path.join(repo_root, "scripts", "04_permulation_loss_dup")
for path in (src_path, stage03_path, stage04_path):
    if path not in sys.path:
        sys.path.insert(0, path)

print(f"Using src path: {src_path}")
print(f"Using stage-03 path: {stage03_path}")
print(f"Using stage-04 path: {stage04_path}")

# Import the modules from stage-03/
from hyphy_results_parser import (
    RelaxResult,
    BustedPhResult
)
from id_converter import convert_hogs_to_locs, get_ptep_description, get_udiv_best_blast

pd.set_option('display.max_columns', None, 'display.max_rows', 20)

Requirement already satisfied: openpyxl in /Users/calvin/anaconda3/envs/orb-selection/lib/python3.11/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/calvin/anaconda3/envs/orb-selection/lib/python3.11/site-packages (from openpyxl) (2.0.0)
Using src path: /Users/calvin/orb-selection/src
Using stage-03 path: /Users/calvin/orb-selection/scripts/03_selection_tests
Using stage-04 path: /Users/calvin/orb-selection/scripts/04_permulation_loss_dup

In [24]:
%load_ext autoreload

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [25]:
def move_column(df, col_name, new_pos):
    cols = list(df.columns)
    cols.insert(new_pos, cols.pop(cols.index(col_name)))
    return df[cols]

## Hyphy Results

In [26]:
hyphy_results = os.path.join(repo_root, "results/hyphy_results_cache/")

In [27]:
# Load the saved RELAX results
relax_result = RelaxResult.load_from_pickle(str(hyphy_results + "relax_results.pkl"))
# relax_result_fltrd = relax_result.filter_omega(10000)
relax_hits_df = relax_result.get_significant_results()

In [28]:
relax_hits_df = move_column(relax_hits_df, 'result', 0)  # Move 'result' column to the front
relax_hits_df

,result,p_value,k,LRT,MG94xREV_ω_reference,MG94xREV_ω_test,ω0_test,ω0_test_P,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω0_ref,ω0_ref_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω0_test_pd,ω0_test_pd_P,ω1_test_pd,ω1_test_pd_P,ω2_test_pd,ω2_test_pd_P,ω3_test_pd,ω3_test_pd_P,ω0_ref_pd,ω0_ref_pd_P,ω1_ref_pd,ω1_ref_pd_P,ω2_ref_pd,ω2_ref_pd_P,ω3_ref_pd,ω3_ref_pd_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0060863,intensified,9.313940e-09,1.138476,32.979424,0.173235,0.145250,1.000000e+10,0.000154,0.102822,0.977555,0.220477,0.022291,1.007076,0.0,1.269621e+02,0.000000,0.135597,0.977706,0.264991,0.022294,1.006213,0.0,1.000000e+10,0.000167,0.000000,0.170091,0.130165,0.829742,6.666951,0.0,1.218414e+02,0.000000,0.100723,0.187279,0.149321,0.812721,1.203268,0.000000,0.105429,0.138481
N5.HOG0067228,relaxed,4.973489e-10,0.842274,38.687638,0.109075,0.183061,1.052570e+02,0.000000,0.108890,0.041879,0.113187,0.958121,2.976131,0.0,2.040563e+02,0.000000,0.071888,0.041879,0.075268,0.958121,3.650472,0.0,2.006031e+02,0.000000,0.112386,1.000000,0.122038,0.000000,3.650470,0.0,1.352971e+02,0.000000,0.075311,1.000000,0.122038,0.000000,3.650471,0.000000,0.113007,0.075126
N5.HOG0050233,relaxed,4.692477e-02,0.938852,3.948084,0.121772,0.132100,3.091073e+08,0.000491,0.093355,0.925516,0.162785,0.073993,1.005832,0.0,9.416490e+04,0.000000,0.079995,0.925971,0.144633,0.074029,1.006213,0.0,2.988428e+08,0.000495,0.081489,0.799730,0.165550,0.199776,6.666951,0.0,2.273387e+02,0.000000,0.079435,0.720790,0.104211,0.279210,6.666951,0.000000,0.098446,0.084780
N5.HOG0063534,intensified,4.099878e-05,1.104053,16.824582,0.136673,0.104080,1.000000e+02,0.000096,0.079687,0.999904,0.852558,0.000000,6.931226,0.0,1.056345e+02,0.000000,0.101141,1.000000,0.865472,0.000000,5.775196,0.0,1.000000e+02,0.000103,0.080215,0.999897,0.692583,0.000000,5.775196,0.0,4.974252e+02,0.000000,0.099459,1.000000,0.692583,0.000000,5.775196,0.000000,0.079679,0.101141
N5.HOG0034724,intensified,4.730694e-04,1.134600,12.218934,0.375921,0.301795,1.030430e+02,0.000000,0.145281,1.000000,0.190626,0.000000,1.068212,0.0,7.676711e+03,0.000321,0.182640,0.999679,0.232047,0.000000,1.059883,0.0,4.726991e+02,0.000000,0.148499,1.000000,0.232047,0.000000,7.323302,0.0,7.796966e+03,0.000319,0.175140,0.999681,0.232047,0.000000,7.323302,0.000000,0.145281,0.182582
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0066936,intensified,2.820222e-04,1.095263,13.186173,0.101392,0.085183,1.852422e+02,0.000000,0.000384,0.000000,0.061332,1.000000,13.727116,0.0,3.795102e+02,0.000000,0.000761,0.000000,0.078187,1.000000,10.930401,0.0,1.325643e+02,0.000000,0.000761,0.000000,0.062094,1.000000,7.863654,0.0,2.641847e+02,0.000000,0.000761,0.000000,0.076907,1.000000,7.863654,0.000000,0.061332,0.078187
N5.HOG0056679,intensified,0.000000e+00,1.273525,118.211284,0.145800,0.087588,1.042048e+02,0.000000,0.000324,0.000000,0.059685,1.000000,97.741291,0.0,2.791748e+02,0.000171,0.001818,0.000000,0.109341,0.999829,36.530274,0.0,4.836641e+02,0.000000,0.001818,0.000000,0.060229,1.000000,9.516366,0.0,2.771138e+02,0.000178,0.001818,0.000000,0.106916,0.999822,9.516366,0.000000,0.059685,0.109323
N5.HOG0066090,relaxed,3.493457e-04,0.903140,12.785343,0.149488,0.180555,3.623446e+02,0.000723,0.001198,0.000000,0.153168,0.999277,4.983097,0.0,6.607702e+03,0.000000,0.000582,0.000000,0.125250,1.000000,5.919770,0.0,3.661390e+02,0.000731,0.000582,0.000000,0.154310,0.999269,5.919770,0.0,3.074563e+02,0.000000,0.000582,0.000000,0.122518,1.000000,5.919770,0.000000,0.153057,0.125250
N5.HOG0048225,intensified,3.357489e-08,1.401179,30.489092,0.312336,0.260905,1.000000e+10,0.001644,0.000000,0.312173,0.291718,0.686183,1.008716,0.0,4.015458e+04,0.001309,0.000000,0.312278,0.415099,0.686413,1.006213,0.0,1.000000e+10,0.001500,0.000000,0.207052,0.246041,0.791448,7.634074,0.0,4.678803e+04,0.001028,0.059906,0.605158,0.623668,0.387645,6.775433,0.006169,0.200172,0.284930
N5.HOG0035083,intensified,6.413629e-04,1.102965,11.651920,0.171406,0.139721,8.081092e+02,0.000000,0.106557,1.000000,0.368615,0.000000,1.067099,0.0,1.000000e+10,0.000366,0.131328,0.999634,0.404608,0.000000,1.060649,0.0,2.260040e+02,0.000000,0.105918,1.000000,0.404608,0.000000,7.332973,0.0,1.000000e+10,0.000364,0.133552,0.999636,0.749789,0.000000,1.142256,0.000000,0.106557,0.131280

In [29]:
relax_hits_df.loc["N5.HOG0052434"]

result                  intensified
p_value                         0.0
k                          1.131695
LRT                       33.141802
MG94xREV_ω_reference       0.124144
                           ...
ω2_ref_pd_P                     0.0
ω3_ref_pd                  1.594577
ω3_ref_pd_P                     0.0
ω_mean_test                0.049615
ω_mean_ref                 0.070326
Name: N5.HOG0052434, Length: 40, dtype: object

In [30]:
relax_hits_df.loc["N5.HOG0068277"]

result                   relaxed
p_value                 0.014157
k                       0.204655
LRT                     6.018422
MG94xREV_ω_reference    0.003617
                          ...
ω2_ref_pd_P                  0.0
ω3_ref_pd                7.23336
ω3_ref_pd_P             0.001505
ω_mean_test             0.003037
ω_mean_ref              0.009273
Name: N5.HOG0068277, Length: 40, dtype: object

In [31]:
# Load the saved BUSTED-PH, orb fg results
%autoreload 2
busted_ph_orb_result = BustedPhResult.load_from_pickle(str(hyphy_results + "busted_ph_orb_results.pkl"))
# busted_ph_orb_result_fltrd = busted_ph_orb_result.filter_omega(10000)
busted_ph_orb_hits_df = busted_ph_orb_result.get_significant_results()
busted_ph_orb_hits_df['foreground'] = 'orbweavers'
busted_ph_orb_hits_df = move_column(busted_ph_orb_hits_df, 'foreground', 0)  # Move 'foreground' column to the front
busted_ph_orb_hits_df.drop(columns=['result'], inplace=True)  # Drop result column
busted_ph_orb_hits_df

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω0_test,ω0_test_P,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω0_ref,ω0_ref_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω0_test_null,ω0_test_null_P,ω1_test_null,ω1_test_null_P,ω2_test_null,ω2_test_null_P,ω3_test_null,ω3_test_null_P,ω0_ref_null,ω0_ref_null_P,ω1_ref_null,ω1_ref_null_P,ω2_ref_null,ω2_ref_null_P,ω3_ref_null,ω3_ref_null_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0052434,orbweavers,0.003134,10.144697,0.5,0.0,2.216545e-10,59.163958,0.13060,0.088349,125.844278,0.0,0.066718,0.844177,0.102445,0.147742,6.714877,0.008081,122.103382,0.002592,0.051107,0.587143,0.050939,0.410265,1.080899,0.0,104.568204,0.000000,0.062011,0.677858,0.074615,0.292539,1.0,0.029603,105.928228,0.001687,0.050980,0.697312,0.049723,0.301001,2.530139,0.0,0.125723,0.050906
N5.HOG0068277,orbweavers,0.017813,6.669305,0.5,0.0,1.558252e-02,17.296264,0.00559,0.001486,2416.909320,0.0,0.000022,0.000000,0.000000,0.997786,6.557268,0.002214,1489.658364,0.000000,0.000733,0.338777,0.001736,0.661223,4.726758,0.0,223670.675527,0.000405,0.000022,0.000000,0.000000,0.995396,1.0,0.004199,1756.303614,0.000000,0.000797,0.328864,0.001693,0.671136,4.726758,0.0,0.014516,0.001396

In [32]:
# Load the saved BUSTED-PH, non-orb fg results
busted_ph_non_orb_result = BustedPhResult.load_from_pickle(str(hyphy_results + "busted_ph_non_orb_results.pkl"))
# busted_ph_non_orb_result_fltrd = busted_ph_non_orb_result.filter_omega(10000)
busted_ph_non_orb_hits_df = busted_ph_non_orb_result.get_significant_results()
busted_ph_non_orb_hits_df['foreground'] = 'non-orbweavers'
busted_ph_non_orb_hits_df = move_column(busted_ph_non_orb_hits_df, 'foreground', 0)  # Move 'foreground' column to the front
busted_ph_non_orb_hits_df.drop(columns=['result'], inplace=True)  # Drop result column
busted_ph_non_orb_hits_df

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω0_test,ω0_test_P,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω0_ref,ω0_ref_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω0_test_null,ω0_test_null_P,ω1_test_null,ω1_test_null_P,ω2_test_null,ω2_test_null_P,ω3_test_null,ω3_test_null_P,ω0_ref_null,ω0_ref_null_P,ω1_ref_null,ω1_ref_null_P,ω2_ref_null,ω2_ref_null_P,ω3_ref_null,ω3_ref_null_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0050057,non-orbweavers,0.000000e+00,225.027496,0.500000,0.000000,0.000000e+00,506.321321,0.493203,0.364339,43780.880107,0.010000,0.000014,0.291267,0.293328,0.668949,100.000000,0.029784,1.000000e+10,0.000719,0.029405,0.334226,0.338860,0.665056,1.046315,0.000000,54925.839920,0.010000,0.000004,0.268880,0.253917,0.591479,1.0,0.129641,1.000000e+10,0.000279,0.020879,0.227603,0.274381,0.772118,2.378997,0.000000,3.174590,0.235189
N5.HOG0033128,non-orbweavers,2.090426e-02,6.349310,0.500000,0.000000,0.000000e+00,247.510313,0.338733,0.294687,441934.000737,0.002046,0.538159,0.342597,0.062156,0.641077,3.371254,0.014280,2.481265e+03,0.000000,0.000000,0.120395,0.234366,0.879605,1.192692,0.000000,840232.290258,0.002269,0.571918,0.343102,0.055976,0.636154,1.0,0.018476,2.102142e+02,0.000000,0.000000,0.089162,0.222654,0.910838,2.808570,0.000000,0.272360,0.206149
N5.HOG0051320,non-orbweavers,2.962484e-02,5.651990,0.500000,0.000000,0.000000e+00,95.261272,0.239841,0.228719,3716.469975,0.004061,0.222265,0.749050,0.002384,0.234274,4.386745,0.012615,8.651278e+04,0.000310,0.098521,0.756833,0.525437,0.242857,1.006909,0.000000,3180.015433,0.004782,0.203176,0.705344,0.017069,0.243918,1.0,0.045956,1.052045e+05,0.000275,0.087241,0.689082,0.446574,0.310644,2.267209,0.000000,0.222387,0.202170
N5.HOG0068297,non-orbweavers,1.910763e-03,11.134211,0.500000,0.000000,5.564347e-06,36.608095,0.339757,0.326158,100.000000,0.000533,0.000000,0.351785,0.365666,0.612351,5.020344,0.035332,2.411733e+02,0.000000,0.560201,0.294812,0.129686,0.672870,1.000000,0.032318,100.000000,0.003819,0.000000,0.293103,0.219599,0.507447,1.0,0.195631,2.127683e+02,0.000000,0.537785,0.332265,0.134342,0.657861,1.000000,0.009874,0.401293,0.284734
N5.HOG0040346,non-orbweavers,1.291219e-03,11.918043,0.500000,0.000000,3.651934e-07,42.796178,0.013069,0.017975,213.353849,0.000000,0.006272,0.699465,0.010213,0.299368,7.210511,0.001167,1.000000e+10,0.000930,0.007693,0.980397,0.014294,0.018674,1.000000,0.000000,100.000000,0.000202,0.000000,0.115878,0.006766,0.879470,1.0,0.004449,1.000000e+10,0.000926,0.007673,0.971971,0.011131,0.027103,1.394172,0.000000,0.015860,0.007809
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0064830,non-orbweavers,7.339609e-07,26.863326,0.500000,0.000000,0.000000e+00,217.576259,0.523684,0.458766,1603.563890,0.010000,0.004096,0.347775,0.522605,0.554429,3.993571,0.087796,7.552411e+07,0.001056,0.000000,0.202612,0.498100,0.796332,1.006213,0.000000,1288.460260,0.010000,0.004398,0.300290,0.185424,0.253438,1.0,0.436272,2.654581e+08,0.000663,0.000000,0.166329,0.458556,0.833008,2.288073,0.000000,0.641791,0.396653
N5.HOG0060063,non-orbweavers,1.518230e-13,57.645558,0.500000,0.000000,0.000000e+00,413.619466,0.488485,0.344606,592.332621,0.010000,1.000000,0.391861,0.037673,0.583271,100.000000,0.014868,6.724371e+02,0.000000,0.498896,0.626459,0.000000,0.373541,1.011571,0.000000,1017.569926,0.010000,1.000000,0.401420,0.029634,0.570016,1.0,0.018564,1.399953e+02,0.000000,0.458067,0.652954,0.000000,0.347046,2.280349,0.000000,1.900651,0.312538
N5.HOG0062761,non-orbweavers,2.204701e-03,10.848032,0.055809,4.385341,0.000000e+00,105.784482,0.228451,0.169268,13915.474787,0.002234,0.124099,0.616156,0.180065,0.352294,3.252661,0.029316,1.000000e+10,0.000601,0.040576,0.604586,0.219370,0.376383,3.138457,0.018430,14521.143899,0.003106,0.125284,0.356043,0.126199,0.561058,1.0,0.079792,1.000000e+10,0.000511,0.045135,0.630054,0.228152,0.353592,3.275650,0.015844,0.235254,0.164940
N5.HOG0030400,non-orbweavers,1.056877e-12,53.765137,0.500000,0.000000,0.000000e+00,242.841860,0.213115,0.128814,103.229373,0.000000,0.089974,0.741911,0.280765,0.243500,19.594265,0.014589,1.481081e+02,0.000000,0.038820,0.595308,0.192435,0.400173,1.000000,0.004519,100.000000,0.005746,0.103534,0.660471,0.128228,0.272557,1.0,0.061226,3.730693e+02,0.000000,0.040633,0.611241,0.199243,0.388759,1.010475,0.000000,0.420986,0.104636
N5.HOG0056151,non-orbweavers,2.740750e-02,5.807583,0.500000,0.000000,6.890134e-05,30.757913,0.100607,0.080470,4983.630333,0.000000,0.064229,0.965937,0.546207,0.031761,9.034807,0.002302,1.000000e+02,0.000299,0.064232,0.999701,0.184190,0.000000,1.011901,0.000000,100.000000,0.000247,0.063832,0.969560,0.093315,0.005649,1.0,0.024544,1.000000e+02,0.000231,0.064019,0.999769,0.184190,0.000000,2.281281,0.000000,0.100186,0.064212

In [33]:
all_busted_hits_df = pd.concat([busted_ph_orb_hits_df, busted_ph_non_orb_hits_df])
all_busted_hits_df

,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω0_test,ω0_test_P,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω0_ref,ω0_ref_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω0_test_null,ω0_test_null_P,ω1_test_null,ω1_test_null_P,ω2_test_null,ω2_test_null_P,ω3_test_null,ω3_test_null_P,ω0_ref_null,ω0_ref_null_P,ω1_ref_null,ω1_ref_null_P,ω2_ref_null,ω2_ref_null_P,ω3_ref_null,ω3_ref_null_P,ω_mean_test,ω_mean_ref
HOG,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
N5.HOG0052434,orbweavers,3.133841e-03,10.144697,0.500000,0.000000,2.216545e-10,59.163958,0.130600,0.088349,125.844278,0.000000,0.066718,0.844177,0.102445,0.147742,6.714877,0.008081,1.221034e+02,0.002592,0.051107,0.587143,0.050939,0.410265,1.080899,0.000000,104.568204,0.000000,0.062011,0.677858,0.074615,0.292539,1.0,0.029603,1.059282e+02,0.001687,0.050980,0.697312,0.049723,0.301001,2.530139,0.000000,0.125723,0.050906
N5.HOG0068277,orbweavers,1.781348e-02,6.669305,0.500000,0.000000,1.558252e-02,17.296264,0.005590,0.001486,2416.909320,0.000000,0.000022,0.000000,0.000000,0.997786,6.557268,0.002214,1.489658e+03,0.000000,0.000733,0.338777,0.001736,0.661223,4.726758,0.000000,223670.675527,0.000405,0.000022,0.000000,0.000000,0.995396,1.0,0.004199,1.756304e+03,0.000000,0.000797,0.328864,0.001693,0.671136,4.726758,0.000000,0.014516,0.001396
N5.HOG0050057,non-orbweavers,0.000000e+00,225.027496,0.500000,0.000000,0.000000e+00,506.321321,0.493203,0.364339,43780.880107,0.010000,0.000014,0.291267,0.293328,0.668949,100.000000,0.029784,1.000000e+10,0.000719,0.029405,0.334226,0.338860,0.665056,1.046315,0.000000,54925.839920,0.010000,0.000004,0.268880,0.253917,0.591479,1.0,0.129641,1.000000e+10,0.000279,0.020879,0.227603,0.274381,0.772118,2.378997,0.000000,3.174590,0.235189
N5.HOG0033128,non-orbweavers,2.090426e-02,6.349310,0.500000,0.000000,0.000000e+00,247.510313,0.338733,0.294687,441934.000737,0.002046,0.538159,0.342597,0.062156,0.641077,3.371254,0.014280,2.481265e+03,0.000000,0.000000,0.120395,0.234366,0.879605,1.192692,0.000000,840232.290258,0.002269,0.571918,0.343102,0.055976,0.636154,1.0,0.018476,2.102142e+02,0.000000,0.000000,0.089162,0.222654,0.910838,2.808570,0.000000,0.272360,0.206149
N5.HOG0051320,non-orbweavers,2.962484e-02,5.651990,0.500000,0.000000,0.000000e+00,95.261272,0.239841,0.228719,3716.469975,0.004061,0.222265,0.749050,0.002384,0.234274,4.386745,0.012615,8.651278e+04,0.000310,0.098521,0.756833,0.525437,0.242857,1.006909,0.000000,3180.015433,0.004782,0.203176,0.705344,0.017069,0.243918,1.0,0.045956,1.052045e+05,0.000275,0.087241,0.689082,0.446574,0.310644,2.267209,0.000000,0.222387,0.202170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
N5.HOG0064830,non-orbweavers,7.339609e-07,26.863326,0.500000,0.000000,0.000000e+00,217.576259,0.523684,0.458766,1603.563890,0.010000,0.004096,0.347775,0.522605,0.554429,3.993571,0.087796,7.552411e+07,0.001056,0.000000,0.202612,0.498100,0.796332,1.006213,0.000000,1288.460260,0.010000,0.004398,0.300290,0.185424,0.253438,1.0,0.436272,2.654581e+08,0.000663,0.000000,0.166329,0.458556,0.833008,2.288073,0.000000,0.641791,0.396653
N5.HOG0060063,non-orbweavers,1.518230e-13,57.645558,0.500000,0.000000,0.000000e+00,413.619466,0.488485,0.344606,592.332621,0.010000,1.000000,0.391861,0.037673,0.583271,100.000000,0.014868,6.724371e+02,0.000000,0.498896,0.626459,0.000000,0.373541,1.011571,0.000000,1017.569926,0.010000,1.000000,0.401420,0.029634,0.570016,1.0,0.018564,1.399953e+02,0.000000,0.458067,0.652954,0.000000,0.347046,2.280349,0.000000,1.900651,0.312538
N5.HOG0062761,non-orbweavers,2.204701e-03,10.848032,0.055809,4.385341,0.000000e+00,105.784482,0.228451,0.169268,13915.474787,0.002234,0.124099,0.616156,0.180065,0.352294,3.252661,0.029316,1.000000e+10,0.000601,0.040576,0.604586,0.219370,0.376383,3.138457,0.018430,14521.143899,0.003106,0.125284,0.356043,0.126199,0.561058,1.0,0.079792,1.000000e+10,0.000511,0.045135,0.630054,0.228152,0.353592,3.275650,0.015844,0.235254,0.164940
N5.HOG0030400,non-orbweavers,1.056877e-12,53.765137,0.500000,0.000000,0.000000e+00,242.841860,0.213115,0.128814,103.229373,0.000000,0.089974,0.741911,0.280765,0.243500,19.594265,0.014589,1.481081e+02,0.000000,0.038820,0.595308,0.192435,0.400173,1.000000,0.004519,100.000000,0.005746,0.103534,0.660471,0.128228,0.272557,1.0,0.061226,3.730693e+02,0.000000,0.040633,0.611241,0.199243,0.388759,1.010475,0.000000,0.420986,0.104636
N5.HOG0056151,non-orbweavers,2.740750e-02,5.807583,0.500000,0.000000,6.890134e-05,30.757913,0.100607,0.080470,4983.630333,0.000000,0.064229,0.965937,0.546207,0.031761,9.034807,0.002302,1.000000e+02,0.000299,0.064232,0.999701,0.184190,0.000000,1.011901,0.000000,100.000000,0.000247,0.063832,0.969560,0.093315,0.005649,1.0,0.024544,1.000000e+02,0.000231,0.064019,0.999769,0.184190,0.000000,2.281281,0.000000,0.100186,0.064212

In [34]:
%autoreload 2
busted_hits_locs = convert_hogs_to_locs(all_busted_hits_df, os.path.join(repo_root, "data/N5.tsv"), one_gene_rep=True)
busted_hits_locs_fltrd = busted_hits_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
busted_hits_locs_fltrd = move_column(busted_hits_locs_fltrd, 'HOG', 0)
busted_hits_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
busted_hits_locs_fltrd

Processing HOGs: 100%|██████████| 23/23 [00:00<00:00, 726.67it/s]

,HOG,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω0_test,ω0_test_P,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω0_ref,ω0_ref_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω0_test_null,ω0_test_null_P,ω1_test_null,ω1_test_null_P,ω2_test_null,ω2_test_null_P,ω3_test_null,ω3_test_null_P,ω0_ref_null,ω0_ref_null_P,ω1_ref_null,ω1_ref_null_P,ω2_ref_null,ω2_ref_null_P,ω3_ref_null,ω3_ref_null_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0052434,orbweavers,3.133841e-03,10.144697,0.5,0.0,2.216545e-10,59.163958,0.130600,0.088349,125.844278,0.000000,0.066718,0.844177,0.102445,0.147742,6.714877,0.008081,1.221034e+02,2.592435e-03,0.051107,0.587143,0.050939,0.410265,1.080899,0.000000,104.568204,0.000000,0.062011,0.677858,0.074615,0.292539,1.0,0.029603,1.059282e+02,1.687249e-03,0.050980,0.697312,0.049723,0.301001,2.530139,0.000000,0.125723,0.050906,129221501,GO:0004362 [Name: glutathione-disulfide reduct...,"thioredoxin reductase 1, cytoplasmic-like"
1,N5.HOG0050057,non-orbweavers,0.000000e+00,225.027496,0.5,0.0,0.000000e+00,506.321321,0.493203,0.364339,43780.880107,0.010000,0.000014,0.291267,0.293328,0.668949,100.000000,0.029784,1.000000e+10,7.187434e-04,0.029405,0.334226,0.338860,0.665056,1.046315,0.000000,54925.839920,0.010000,0.000004,0.268880,0.253917,0.591479,1.0,0.129641,1.000000e+10,2.787595e-04,0.020879,0.227603,0.274381,0.772118,2.378997,0.000000,3.174590,0.235189,129229604,GO:0032281 [Name: AMPA glutamate receptor comp...,enolase-phosphatase E1-like
2,N5.HOG0033128,non-orbweavers,2.090426e-02,6.349310,0.5,0.0,0.000000e+00,247.510313,0.338733,0.294687,441934.000737,0.002046,0.538159,0.342597,0.062156,0.641077,3.371254,0.014280,2.481265e+03,0.000000e+00,0.000000,0.120395,0.234366,0.879605,1.192692,0.000000,840232.290258,0.002269,0.571918,0.343102,0.055976,0.636154,1.0,0.018476,2.102142e+02,0.000000e+00,0.000000,0.089162,0.222654,0.910838,2.808570,0.000000,0.272360,0.206149,129222940,GO:0007165 [Name: signal transduction],rho GTPase-activating protein 24-like
3,N5.HOG0051320,non-orbweavers,2.962484e-02,5.651990,0.5,0.0,0.000000e+00,95.261272,0.239841,0.228719,3716.469975,0.004061,0.222265,0.749050,0.002384,0.234274,4.386745,0.012615,8.651278e+04,3.096680e-04,0.098521,0.756833,0.525437,0.242857,1.006909,0.000000,3180.015433,0.004782,0.203176,0.705344,0.017069,0.243918,1.0,0.045956,1.052045e+05,2.745570e-04,0.087241,0.689082,0.446574,0.310644,2.267209,0.000000,0.222387,0.202170,129228337,-,uncharacterized LOC129228337
4,N5.HOG0040346,non-orbweavers,1.291219e-03,11.918043,0.5,0.0,3.651934e-07,42.796178,0.013069,0.017975,213.353849,0.000000,0.006272,0.699465,0.010213,0.299368,7.210511,0.001167,1.000000e+10,9.297445e-04,0.007693,0.980397,0.014294,0.018674,1.000000,0.000000,100.000000,0.000202,0.000000,0.115878,0.006766,0.879470,1.0,0.004449,1.000000e+10,9.255775e-04,0.007673,0.971971,0.011131,0.027103,1.394172,0.000000,0.015860,0.007809,129221589,GO:0004672 [Name: protein kinase activity]; GO...,Serine/threonine-protein kinase Tao
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,N5.HOG0068277,orbweavers,1.781348e-02,6.669305,0.5,0.0,1.558252e-02,17.296264,0.005590,0.001486,2416.909320,0.000000,0.000022,0.000000,0.000000,0.997786,6.557268,0.002214,1.489658e+03,0.000000e+00,0.000733,0.338777,0.001736,0.661223,4.726758,0.000000,223670.675527,0.000405,0.000022,0.000000,0.000000,0.995396,1.0,0.004199,1.756304e+03,0.000000e+00,0.000797,0.328864,0.001693,0.671136,4.726758,0.000000,0.014516,0.001396,NaN,NaN,NaN
19,N5.HOG0068297,non-orbweavers,1.910763e-03,11.134211,0.5,0.0,5.564347e-06,36.608095,0.339757,0.326158,100.000000,0.000533,0.000000,0.351785,0.365666,0.612351,5.020344,0.035332,2.411733e+02,0.000000e+00,0.560201,0.294812,0.129686,0.672870,1.000000,0.032318,100.000000,0.003819,0.000000,0.293103,0.219599,0.507447,1.0,0.195631,2.127683e+02,0.000000e+00,0.537785,0.332265,0.134342,0.657861,1.000000,0.009874,0.401293,0.284734,NaN,NaN,NaN
20,N5.HOG0059819,non-orbweavers,1.519386e-04,16.197774,0.5,0.0,2.669975e-11,63.758493,0.397314,0.331249,440.898378,0.000000,0.092215,0.374544,0.284068,0.583496,5.685323,0.041960,9.399805e+02,1.058791e-22,0.194412,0.460671,0.209735,0.539329,2.302977,0.000000,440.898378,0.000000,0.124628,0.250648,0.167334,0.590377,1.0,0.158975,1.449947e+02,1.058791e-22,0.195292,0.973522,0.201774,0.026478,6.826579,0.000000,0.438850,0.202676,NaN,NaN,NaN
21,N5.HOG0054027,non-orbweavers,9.862446e-03,7.851748,0.5,0.0,1.936919e-05,33.727503,0.334093,0.344264,1619.285289,0.000475,0.027766,0.371911,0.282915,0.544224,1.992119,0.083390,6.299751e+04,4.891445e-04,0.000292,0.454023,0.363542,0.353243,1.000000,0.192244,8823.573131,0.000781,0.029124,0.331644,0.192333,0.465140,1.0,0.202434,7.435194e+04,4.733250e-04,0.000274,0.454573,0.416485,0.400893,1.000000,0.144061,0.330419,0.320796,NaN,NaN,NaN
22,N5.HOG0064830,non-orbweavers,7.339609e-07,26.863326,0.5,0.0,0.000000e+00,217.576259,0.523684,0.458766,1603.563890,0.010000,0.004096,0.347775,0.522605,0.554429,3.993571,0.087796,7.552411e+07,1.056241e-03,0.000000,0.202612,0.498100,0.796332,1.006213,0.000000,1288.460260,0.010000,0.004398,0.300290,0.185424,0.253438,1.0,0.436272,2.654581e+08,6.628241e-04,0.000000,0.166329,0.458556,0.833008,2.288073,0.000000,0.641791,0.396653,NaN,NaN,NaN

In [35]:
%autoreload 2
busted_df_ptep = get_ptep_description(busted_hits_locs_fltrd)
busted_df = get_udiv_best_blast(busted_df_ptep)
busted_df

,HOG,foreground,test_pval,test_LRT,background_pval,background_LRT,shared_pval,shared_LRT,MG94xREV_ω_test,MG94xREV_ω_ref,ω0_test,ω0_test_P,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω0_ref,ω0_ref_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω0_test_null,ω0_test_null_P,ω1_test_null,ω1_test_null_P,ω2_test_null,ω2_test_null_P,ω3_test_null,ω3_test_null_P,ω0_ref_null,ω0_ref_null_P,ω1_ref_null,ω1_ref_null_P,ω2_ref_null,ω2_ref_null_P,ω3_ref_null,ω3_ref_null_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit LOC,P. tepidariorum best BLAST hit description,U. diversus best BLAST hit LOC,U. diversus best BLAST hit description
0,N5.HOG0052434,orbweavers,3.133841e-03,10.144697,0.5,0.0,2.216545e-10,59.163958,0.130600,0.088349,125.844278,0.000000,0.066718,0.844177,0.102445,0.147742,6.714877,0.008081,1.221034e+02,2.592435e-03,0.051107,0.587143,0.050939,0.410265,1.080899,0.000000,104.568204,0.000000,0.062011,0.677858,0.074615,0.292539,1.0,0.029603,1.059282e+02,1.687249e-03,0.050980,0.697312,0.049723,0.301001,2.530139,0.000000,0.125723,0.050906,129221501,GO:0004362 [Name: glutathione-disulfide reduct...,"thioredoxin reductase 1, cytoplasmic-like",LOC107443032,"thioredoxin reductase 1, cytoplasmic isoform X1",LOC129221501,"thioredoxin reductase 1, cytoplasmic-like"
1,N5.HOG0050057,non-orbweavers,0.000000e+00,225.027496,0.5,0.0,0.000000e+00,506.321321,0.493203,0.364339,43780.880107,0.010000,0.000014,0.291267,0.293328,0.668949,100.000000,0.029784,1.000000e+10,7.187434e-04,0.029405,0.334226,0.338860,0.665056,1.046315,0.000000,54925.839920,0.010000,0.000004,0.268880,0.253917,0.591479,1.0,0.129641,1.000000e+10,2.787595e-04,0.020879,0.227603,0.274381,0.772118,2.378997,0.000000,3.174590,0.235189,129229604,GO:0032281 [Name: AMPA glutamate receptor comp...,enolase-phosphatase E1-like,LOC107436697,uncharacterized protein isoform X4,LOC129229604,enolase-phosphatase E1-like isoform X1
2,N5.HOG0033128,non-orbweavers,2.090426e-02,6.349310,0.5,0.0,0.000000e+00,247.510313,0.338733,0.294687,441934.000737,0.002046,0.538159,0.342597,0.062156,0.641077,3.371254,0.014280,2.481265e+03,0.000000e+00,0.000000,0.120395,0.234366,0.879605,1.192692,0.000000,840232.290258,0.002269,0.571918,0.343102,0.055976,0.636154,1.0,0.018476,2.102142e+02,0.000000e+00,0.000000,0.089162,0.222654,0.910838,2.808570,0.000000,0.272360,0.206149,129222940,GO:0007165 [Name: signal transduction],rho GTPase-activating protein 24-like,LOC107438170,uncharacterized protein,LOC129222940,rho GTPase-activating protein 24-like
3,N5.HOG0051320,non-orbweavers,2.962484e-02,5.651990,0.5,0.0,0.000000e+00,95.261272,0.239841,0.228719,3716.469975,0.004061,0.222265,0.749050,0.002384,0.234274,4.386745,0.012615,8.651278e+04,3.096680e-04,0.098521,0.756833,0.525437,0.242857,1.006909,0.000000,3180.015433,0.004782,0.203176,0.705344,0.017069,0.243918,1.0,0.045956,1.052045e+05,2.745570e-04,0.087241,0.689082,0.446574,0.310644,2.267209,0.000000,0.222387,0.202170,129228337,-,uncharacterized LOC129228337,LOC107442330,myosin-11 isoform X2,LOC129228337,uncharacterized protein LOC129228337
4,N5.HOG0040346,non-orbweavers,1.291219e-03,11.918043,0.5,0.0,3.651934e-07,42.796178,0.013069,0.017975,213.353849,0.000000,0.006272,0.699465,0.010213,0.299368,7.210511,0.001167,1.000000e+10,9.297445e-04,0.007693,0.980397,0.014294,0.018674,1.000000,0.000000,100.000000,0.000202,0.000000,0.115878,0.006766,0.879470,1.0,0.004449,1.000000e+10,9.255775e-04,0.007673,0.971971,0.011131,0.027103,1.394172,0.000000,0.015860,0.007809,129221589,GO:0004672 [Name: protein kinase activity]; GO...,Serine/threonine-protein kinase Tao,LOC107448445,serine/threonine-protein kinase Tao,LOC129221589,serine/threonine-protein kinase Tao-like isofo...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18,N5.HOG0068277,orbweavers,1.781348e-02,6.669305,0.5,0.0,1.558252e-02,17.296264,0.005590,0.001486,2416.909320,0.000000,0.000022,0.000000,0.000000,0.997786,6.557268,0.002214,1.489658e+03,0.000000e+00,0.000733,0.338777,0.001736,0.661223,4.726758,0.000000,223670.675527,0.000405,0.000022,0.000000,0.000000,0.995396,1.0,0.004199,1.756304e+03,0.000000e+00,0.000797,0.328864,0.001693,0.671136,4.726758,0.000000,0.014516,0.001396,NaN,NaN,NaN,LOC107453013,AP-2 complex subunit sigma,LOC129221226,AP-1 complex subunit sigma-2-like
19,N5.HOG0068297,non-orbweavers,1.910763e-03,11.134211,0.5,0.0,5.564347e-06,36.608095,0.339757,0.326158,100.000000,0.000533,0.000000,0.351785,0.365666,0.612351,5.020344,0.035332,2.411733e+02,0.000000e+00,0.560201,0.294812,0.129686,0.672870,1.000000,0.032318,100.000000,0.003819,0.000000,0.293103,0.219599,0.507447,1.0,0.195631,2.127683e+02,0.000000e+00,0.537785,0.332265,0.134342,0.657861,1.000000,0.009874,0.401293,0.284734,NaN,NaN,NaN,NO_HIT,NO_HIT,NO_HIT,NO_HIT
20,N5.HOG0059819,non-orbweavers,1.519386e-04,16.197774,0.5,0.0,2.669975e-11,63.758493,0.397314,0.331249,440.898378,0.000000,0.092215,0.374544,0.284068,0.583496,5.685323,0.041960,9.399805e+02,1.058791e-22,0.194412,0.460671,0.209735,0.539329,2.302977,0.000000,440.898378,0.000000,0.124628,0.250648,0.167334,0.590377,1.0,0.158975,1.449947e+02,1.058791e-22,0.195292,0.973522,0.201774,0.026478,6.826579,0.000000,0.438850,0.202676,NaN,NaN,NaN,NO_HIT,NO_HIT,LOC129223840,RNA-binding protein 4.1-like isoform X1
21,N5.HOG0054027,non-orbweavers,9.862446e-03,7.851748,0.5,0.0,1.936919e-05,33.727503,0.334093,0.344264,1619.285289,0.000475,0.027766,0.371911,0.282915,0.544224,1.992119,0.083390,6.299751e+04,4.891445e-04,0.000292,0.454023,0.363542,0.353243,1.000000,0.192244,8823.573131,0.000781,0.029124,0.331644,0.192333,0.465140,1.0,0.202434,7.435194e+04,4.733250e-04,0.000274,0.454573,0.416485,0.400893,1.000000,0.144061,0.330419,0.320796,NaN,NaN,NaN,LOC107451375,PWWP domain-containing DNA repair factor 3A,NO_HIT,NO_HIT
22,N5.HOG0064830,non-orbweavers,7.339609e-07,26.863326,0.5,0.0,0.000000e+00,217.576259,0.523684,0.458766,1603.563890,0.010000,0.004096,0.347775,0.522605,0.554429,3.993571,0.087796,7.552411e+07,1.056241e-03,0.000000,0.202612,0.498100,0.796332,1.006213,0.000000,1288.460260,0.010000,0.004398,0.300290,0.185424,0.253438,1.0,0.436272,2.654581e+08,6.628241e-04,0.000000,0.166329,0.458556,0.833008,2.288073,0.000000,0.641791,0.396653,NaN,NaN,NaN,LOC107455578,uro-adherence factor A,NO_HIT,NO_HIT

In [36]:
busted_df.to_excel(os.path.join(repo_root, "results/Supplementary_Table_4_BUSTED_PH.xlsx"), index=False)

In [37]:
relax_hits_locs = convert_hogs_to_locs(relax_hits_df, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
relax_hits_locs_fltrd = relax_hits_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
relax_hits_locs_fltrd = move_column(relax_hits_locs_fltrd, 'HOG', 0)
relax_hits_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
relax_df_ptep = get_ptep_description(relax_hits_locs_fltrd)
relax_df = get_udiv_best_blast(relax_df_ptep)
relax_df

Processing HOGs: 100%|██████████| 2197/2197 [00:00<00:00, 60696.13it/s]

,HOG,result,p_value,k,LRT,MG94xREV_ω_reference,MG94xREV_ω_test,ω0_test,ω0_test_P,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω0_ref,ω0_ref_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω0_test_pd,ω0_test_pd_P,ω1_test_pd,ω1_test_pd_P,ω2_test_pd,ω2_test_pd_P,ω3_test_pd,ω3_test_pd_P,ω0_ref_pd,ω0_ref_pd_P,ω1_ref_pd,ω1_ref_pd_P,ω2_ref_pd,ω2_ref_pd_P,ω3_ref_pd,ω3_ref_pd_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit LOC,P. tepidariorum best BLAST hit description,U. diversus best BLAST hit LOC,U. diversus best BLAST hit description
0,N5.HOG0060863,intensified,9.313940e-09,1.138476,32.979424,0.173235,0.145250,1.000000e+10,0.000154,0.102822,0.977555,0.220477,0.022291,1.007076,0.0,1.269621e+02,0.000000,0.135597,0.977706,0.264991,0.022294,1.006213,0.0,1.000000e+10,0.000167,0.000000,0.170091,0.130165,0.829742,6.666951,0.0,1.218414e+02,0.000000,0.100723,0.187279,0.149321,0.812721,1.203268,0.000000,0.105429,0.138481,129221600,GO:0004377 [Name: GDP-Man:Man3GlcNAc2-PP-Dol a...,"GDP-Man:Man(3)GlcNAc(2)-PP-Dol alpha-1,2-manno...",LOC107446372,"GDP-Man:Man(3)GlcNAc(2)-PP-Dol alpha-1,2-manno...",LOC129221600,"GDP-Man:Man(3)GlcNAc(2)-PP-Dol alpha-1,2-manno..."
1,N5.HOG0067228,relaxed,4.973489e-10,0.842274,38.687638,0.109075,0.183061,1.052570e+02,0.000000,0.108890,0.041879,0.113187,0.958121,2.976131,0.0,2.040563e+02,0.000000,0.071888,0.041879,0.075268,0.958121,3.650472,0.0,2.006031e+02,0.000000,0.112386,1.000000,0.122038,0.000000,3.650470,0.0,1.352971e+02,0.000000,0.075311,1.000000,0.122038,0.000000,3.650471,0.000000,0.113007,0.075126,129223414,GO:0005737 [Name: cytoplasm]; GO:0016925 [Name...,activator of SUMO 1,LOC107457277,SUMO-activating enzyme subunit 1,LOC129223414,SUMO-activating enzyme subunit 1-like isoform X1
2,N5.HOG0050233,relaxed,4.692477e-02,0.938852,3.948084,0.121772,0.132100,3.091073e+08,0.000491,0.093355,0.925516,0.162785,0.073993,1.005832,0.0,9.416490e+04,0.000000,0.079995,0.925971,0.144633,0.074029,1.006213,0.0,2.988428e+08,0.000495,0.081489,0.799730,0.165550,0.199776,6.666951,0.0,2.273387e+02,0.000000,0.079435,0.720790,0.104211,0.279210,6.666951,0.000000,0.098446,0.084780,129217819,GO:0017171 [Name: serine hydrolase activity],lethal (2) k09913,LOC107446798,uncharacterized protein isoform X1,LOC129217819,transmembrane protein 53-like
3,N5.HOG0063534,intensified,4.099878e-05,1.104053,16.824582,0.136673,0.104080,1.000000e+02,0.000096,0.079687,0.999904,0.852558,0.000000,6.931226,0.0,1.056345e+02,0.000000,0.101141,1.000000,0.865472,0.000000,5.775196,0.0,1.000000e+02,0.000103,0.080215,0.999897,0.692583,0.000000,5.775196,0.0,4.974252e+02,0.000000,0.099459,1.000000,0.692583,0.000000,5.775196,0.000000,0.079679,0.101141,129227726,-,uncharacterized LOC129227726,LOC107446717,uncharacterized protein,LOC129227726,uncharacterized protein LOC129227726
4,N5.HOG0034724,intensified,4.730694e-04,1.134600,12.218934,0.375921,0.301795,1.030430e+02,0.000000,0.145281,1.000000,0.190626,0.000000,1.068212,0.0,7.676711e+03,0.000321,0.182640,0.999679,0.232047,0.000000,1.059883,0.0,4.726991e+02,0.000000,0.148499,1.000000,0.232047,0.000000,7.323302,0.0,7.796966e+03,0.000319,0.175140,0.999681,0.232047,0.000000,7.323302,0.000000,0.145281,0.182582,NaN,NaN,NaN,LOC107449515,proclotting enzyme isoform X1,LOC129230696,venom protease-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2192,N5.HOG0066936,intensified,2.820222e-04,1.095263,13.186173,0.101392,0.085183,1.852422e+02,0.000000,0.000384,0.000000,0.061332,1.000000,13.727116,0.0,3.795102e+02,0.000000,0.000761,0.000000,0.078187,1.000000,10.930401,0.0,1.325643e+02,0.000000,0.000761,0.000000,0.062094,1.000000,7.863654,0.0,2.641847e+02,0.000000,0.000761,0.000000,0.076907,1.000000,7.863654,0.000000,0.061332,0.078187,129234669,GO:0009058 [Name: biosynthetic process]; GO:00...,eukaryotic translation initiation factor 2B su...,LOC107439202,translation initiation factor eIF2B subunit gamma,LOC129234669,translation initiation factor eIF-2B subunit g...
2193,N5.HOG0056679,intensified,0.000000e+00,1.273525,118.211284,0.145800,0.087588,1.042048e+02,0.000000,0.000324,0.000000,0.059685,1.000000,97.741291,0.0,2.791748e+02,0.000171,0.001818,0.000000,0.109341,0.999829,36.530274,0.0,4.836641e+02,0.000000,0.001818,0.000000,0.060229,1.000000,9.516366,0.0,2.771138e+02,0.000178,0.001818,0.000000,0.106916,0.999822,9.516366,0.000000,0.059685,0.109323,129233134,GO:0005506 [Name: iron ion binding]; GO:001670...,ecdysone 20-monooxygenase-like,LOC107453276,ecdysone 20-monooxygenase,LOC129233134,ecdysone 20-monooxygenase-like
2194,N5.HOG0066090,relaxed,3.493457e-04,0.903140,12.785343,0.149488,0.180555,3.623446e+02,0.000723,0.001198,0.000000,0.153168,0.999277,4.983097,0.0,6.607702e+03,0.000000,0.000582,0.000000,0.125250,1.000000,5.919770,0.0,3.661390e+02,0.000731,0.000582,0.000000,0.154310,0.999269,5.919770,0.0,3.074563e+02,0.000000,0.000582,0.000000,0.122518,1.000000,5.919770,0.000000,0.153057,0.125250,129218525,-,putative uncharacterized protein DDB_G0271982,LOC107450204,tubulin glycylase 3C,LOC129218525,putative uncharacterized protein DDB_G0271982
2195,N5.HOG0048225,intensified,3.357489e-08,1.401179,30.489092,0.312336,0.260905,1.000000e+10,0.001644,0.000000,0.312173,0.291718,0.686183,1.008716,0.0,4.015458e+04,0.001309,0.000000,0.312278,0.415099,0.686413,1.006213,0.0,1.000000e+10,0.001500,0.000000,0.207052,0.246041,0.791448,7.634074,0.0,4.678803e+04,0.001028,0.059906,0.605158,0.623668,0.387645,6.775433,0.006169,0.200172,0.284930,129224485,GO:1990817 [Name: RNA adenylyltransferase acti...,speckle targeted PIP5K1A-regulated poly(A) pol...,LOC107448044,speckle targeted PIP5K1A-regulated poly(A) pol...,LOC129224485,speckle targeted PIP5K1A-regulated poly(A) pol...
2196,N5.HOG0035083,intensified,6.413629e-04,1.102965,11.651920,0.171406,0.139721,8.081092e+02,0.000000,0.106557,1.000000,0.368615,0.000000,1.067099,0.0,1.000000e+10,0.000366,0.131328,0.999634,0.404608,0.000000,1.060649,0.0,2.260040e+02,0.000000,0.105918,1.000000,0.404608,0.000000,7.332973,0.0,1.000000e+10,0.000364,0.133552,0.999636,0.749789,0.000000,1.142256,0.000000,0.106557,0.131280,129219806,GO:0003676 [Name: nucleic acid binding]; GO:00...,ERI1 exoribonuclease 3-like,LOC107441030,ERI1 exoribonuclease 3 isoform X2,LOC129221287,ERI1 exoribonuclease 3-like

In [38]:
relax_df.to_excel(os.path.join(repo_root, "results/Supplementary_Table_3_RELAX.xlsx"), index=False)

## Permutation test results

Reformat results table

In [39]:
%autoreload 2
perm_test_results_dir = os.path.join(repo_root, "results/odds_ratio_test/Results_Jul22/Run1_occ_30-88_10000x/")
perm_results = pd.read_csv(os.path.join(perm_test_results_dir, "fltrd_hits.csv"), index_col="HOG")

perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg"), "Loss more likely in orb-weavers", None)
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg"), "Loss more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("dup_fg"), "Duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("dup_bg"), "Duplication more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg"), "Loss more likely in orb-weavers, duplication more likely in non-orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg"), "Loss more likely in non-orb-weavers, duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg"), "Loss more likely in orb-weavers, duplication more likely in orb-weavers", perm_results["Result"])
perm_results["Result"] = np.where(perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg"), "Loss more likely in non-orb-weavers, duplication more likely in non-orb-weavers", perm_results["Result"])

perm_results = move_column(perm_results, "Result", 0)  # Move 'Result' column to the front
perm_results["LOR outside permuted avg thresholds"] = np.where(perm_results["Significant by avgd thresholds"].notnull(), "Yes", "No")
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg, dup_bg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])

perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg, dup_fg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("dup_fg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_fg, dup_fg") & perm_results["Significant by avgd thresholds"].str.contains("loss_fg, dup_fg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg")), "Yes for loss; no for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("dup_bg")), "No for loss; yes for duplication", perm_results["LOR outside permuted avg thresholds"])
perm_results["LOR outside permuted avg thresholds"] = np.where((perm_results["Significant by permulation"].str.contains("loss_bg, dup_bg") & perm_results["Significant by avgd thresholds"].str.contains("loss_bg, dup_bg")), "Yes for both tests", perm_results["LOR outside permuted avg thresholds"])


perm_results = move_column(perm_results, "LOR outside permuted avg thresholds", 4)  # Move 'LOR outside permuted avg thresholds' column to the front
perm_results = perm_results.drop(columns=["Significant by avgd thresholds", "Significant by permulation"])
perm_results = perm_results.rename(columns={
    "P-value loss more likely in fg": "P-value, loss more likely in orb-weavers", 
    "P-value loss more likely in bg": "P-value, loss more likely in non-orb-weavers", 
    "P-value duplication more likely in fg": "P-value, duplication more likely in orb-weavers", 
    "P-value duplication more likely in bg": "P-value, duplication more likely in non-orb-weavers", 
    })
perm_results

,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers"
HOG,,,,,,,,,
N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202
N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127
N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880
N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964
N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416
...,...,...,...,...,...,...,...,...,...
N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887
N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850
N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940
N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296
N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558

In [40]:
%autoreload 2
perm_locs = convert_hogs_to_locs(perm_results, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
perm_locs_filtered = perm_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
perm_locs_filtered = move_column(perm_locs_filtered, 'HOG', 0)
perm_locs_filtered.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
perm_locs_filtered

Processing HOGs: 100%|██████████| 1482/1482 [00:00<00:00, 67925.81it/s]

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202,NaN,NaN,NaN
1,N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127,NaN,NaN,NaN
2,N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880,129233975,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like
3,N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964,129217362,GO:0008010 [Name: structural constituent of ch...,proteoglycan 4-like
4,N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416,129217825,GO:0008010 [Name: structural constituent of ch...,cuticle protein-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887,NaN,NaN,NaN
1478,N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850,NaN,NaN,NaN
1479,N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940,129221249,-,cuticle protein 38-like
1480,N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296,NaN,NaN,NaN
1481,N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558,NaN,NaN,NaN

In [41]:
%autoreload 2
perm_df = get_ptep_description(perm_locs_filtered)
perm_df = get_udiv_best_blast(perm_df)
perm_df

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit LOC,P. tepidariorum best BLAST hit description,U. diversus best BLAST hit LOC,U. diversus best BLAST hit description
0,N5.HOG0001041,Loss more likely in orb-weavers,46,2.521478,-0.155768,No,0.0009,0.9991,0.4798,0.5202,NaN,NaN,NaN,LOC122268310,gastrula zinc finger protein XlCGF7.1,LOC129226906,zinc finger protein 239-like
1,N5.HOG0001627,Duplication more likely in non-orb-weavers,33,1.855831,-3.857911,Yes,0.0640,0.9360,0.9873,0.0127,NaN,NaN,NaN,LOC107454923,speckle-type POZ protein,LOC129230204,speckle-type POZ protein-like
2,N5.HOG0002031,Loss more likely in non-orb-weavers,46,-3.395453,1.332164,Yes,0.9984,0.0016,0.4120,0.5880,129233975,GO:0008010 [Name: structural constituent of ch...,cuticle protein 10.9-like,LOC107436551,cuticle protein 10.9,LOC129233975,cuticle protein 10.9-like
3,N5.HOG0002072,Loss more likely in orb-weavers,52,3.079265,-0.639315,Yes,0.0143,0.9857,0.8034,0.1964,129217362,GO:0008010 [Name: structural constituent of ch...,proteoglycan 4-like,LOC110283002,uncharacterized protein,LOC129217362,proteoglycan 4-like
4,N5.HOG0002076,Loss more likely in non-orb-weavers,55,-2.050543,0.725386,No,0.9545,0.0455,0.1584,0.8416,129217825,GO:0008010 [Name: structural constituent of ch...,cuticle protein-like,LOC107457534,cuticle protein 10.9-like,LOC129223916,cuticle protein 10.9-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1477,N5.HOG0073071,Duplication more likely in orb-weavers,35,-2.150469,2.393444,Yes,0.7460,0.2540,0.0113,0.9887,NaN,NaN,NaN,LOC110282665,uncharacterized protein,LOC129231832,uncharacterized protein LOC129231832
1478,N5.HOG0073090,Loss more likely in orb-weavers,32,1.527411,-1.712408,No,0.0256,0.9744,0.9150,0.0850,NaN,NaN,NaN,LOC107451793,DNA mismatch repair protein Mlh3,LOC129229813,DNA mismatch repair protein Mlh3-like
1479,N5.HOG0073180,Loss more likely in non-orb-weavers,32,-1.042447,0.851411,No,0.9953,0.0047,0.1060,0.8940,129221249,-,cuticle protein 38-like,LOC107450982,cuticle protein 63-like,LOC129221249,cuticle protein 38-like
1480,N5.HOG0073332,Loss more likely in non-orb-weavers,32,-3.602439,0.354166,Yes,0.9701,0.0299,0.4704,0.5296,NaN,NaN,NaN,NO_HIT,NO_HIT,NO_HIT,NO_HIT
1481,N5.HOG0073559,Loss more likely in non-orb-weavers,30,-1.251871,0.333645,No,0.9578,0.0422,0.4442,0.5558,NaN,NaN,NaN,NO_HIT,NO_HIT,NO_HIT,NO_HIT

In [42]:
len(set(list(perm_df["HOG"])))

1482

In [43]:
perm_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_5_OddsRatioTest.xlsx'), index=False)

In [44]:
previous_interesting = pd.read_csv(os.path.join(repo_root, 'data/interesting_hits.txt'), header=None, names=['HOG'])

In [45]:
pd.set_option('display.max_rows', 20)

perm_previous_interesting_df = perm_df[perm_df['HOG'].isin(previous_interesting['HOG'])]
perm_previous_interesting_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_6_OddsRatioTest_interesting_hits.xlsx'), index=False)
perm_previous_interesting_df

,HOG,Result,Occupancy,Log odds ratio of loss,Log odds ratio of duplication,LOR outside permuted avg thresholds,"P-value, loss more likely in orb-weavers","P-value, loss more likely in non-orb-weavers","P-value, duplication more likely in orb-weavers","P-value, duplication more likely in non-orb-weavers",U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit LOC,P. tepidariorum best BLAST hit description,U. diversus best BLAST hit LOC,U. diversus best BLAST hit description
43,N5.HOG0007453,Loss more likely in orb-weavers,50,1.946870,-1.544702,No,0.0165,0.9835,0.9383,0.0617,129216356,GO:0043005 [Name: neuron projection],lachesin-like,LOC107452585,lachesin,LOC129216356,lachesin-like
113,N5.HOG0014159,Duplication more likely in orb-weavers,78,0.169513,2.093720,No,0.3622,0.6378,0.0394,0.9606,129217691,GO:0005109 [Name: frizzled binding]; GO:000557...,protein Wnt-16-like,LOC107457243,protein Wnt-16-like precursor,LOC129217691,protein Wnt-16-like
175,N5.HOG0018539,Loss more likely in non-orb-weavers,84,-1.480659,0.395499,No,0.9706,0.0294,0.3609,0.6391,129230744,GO:0005737 [Name: cytoplasm]; GO:0097320 [Name...,protein kinase C and casein kinase substrate i...,LOC107454101,protein kinase C and casein kinase substrate i...,LOC129230744,protein kinase C and casein kinase substrate i...
228,N5.HOG0022330,Loss more likely in non-orb-weavers,50,-2.722522,2.141345,No,0.9938,0.0062,0.0579,0.9421,129217545,GO:0046777 [Name: protein autophosphorylation]...,dual specificity tyrosine-phosphorylation-regu...,LOC107436264,dual specificity tyrosine-phosphorylation-regu...,LOC129217537,dual specificity tyrosine-phosphorylation-regu...
260,N5.HOG0024065,"Loss more likely in non-orb-weavers, duplicati...",66,-2.850324,2.026191,Yes for loss; no for duplication,0.9583,0.0417,0.0115,0.9885,129218972,GO:0005737 [Name: cytoplasm]; GO:0006468 [Name...,uncharacterized LOC129218972,LOC107453369,uncharacterized protein,LOC129218972,uncharacterized protein LOC129218972
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1275,N5.HOG0067099,Duplication more likely in non-orb-weavers,56,2.257462,-2.780946,Yes,0.0830,0.9170,0.9689,0.0311,129225034,GO:0005737 [Name: cytoplasm]; GO:0019901 [Name...,Cdk5 activator-like protein,LOC107441928,cyclin-dependent kinase 5 activator 1 isoform X1,LOC129225034,cyclin-dependent kinase 5 activator 1-like
1283,N5.HOG0067221,Duplication more likely in orb-weavers,89,-1.504431,1.649684,No,0.9095,0.0905,0.0213,0.9787,129222939,GO:0006670 [Name: sphingosine metabolic proces...,sphingosine-1-phosphate phosphatase 2-like,LOC107455069,sphingosine-1-phosphate phosphatase 2,LOC129222939,sphingosine-1-phosphate phosphatase 2-like
1347,N5.HOG0068715,Loss more likely in non-orb-weavers,83,-2.162736,0.712293,No,0.9910,0.0090,0.2442,0.7558,129232140,GO:0004930 [Name: G-protein coupled receptor a...,probable G-protein coupled receptor AH9.1,LOC107451782,probable G-protein coupled receptor AH9.1,LOC129232140,probable G-protein coupled receptor AH9.1
1354,N5.HOG0068937,Loss more likely in orb-weavers,78,1.716305,-0.226392,No,0.0063,0.9937,0.5667,0.4333,129225023,GO:0007218 [Name: neuropeptide signaling pathway],FMRFamide propeptide,LOC107451807,myomodulin neuropeptides,LOC129225023,FMRF-amide neuropeptides-like
1378,N5.HOG0069577,Loss more likely in non-orb-weavers,81,-1.740438,0.352464,No,0.9532,0.0468,0.2143,0.7857,129219120,GO:0000981 [Name: RNA polymerase II transcript...,homeobox protein vnd-like,LOC107445723,homeobox protein Nkx-2.5,LOC129219120,homeobox protein vnd-like

In [46]:
relax_previous_interesting_df = relax_df[relax_df['HOG'].isin(previous_interesting['HOG'])]
relax_previous_interesting_df

,HOG,result,p_value,k,LRT,MG94xREV_ω_reference,MG94xREV_ω_test,ω0_test,ω0_test_P,ω1_test,ω1_test_P,ω2_test,ω2_test_P,ω3_test,ω3_test_P,ω0_ref,ω0_ref_P,ω1_ref,ω1_ref_P,ω2_ref,ω2_ref_P,ω3_ref,ω3_ref_P,ω0_test_pd,ω0_test_pd_P,ω1_test_pd,ω1_test_pd_P,ω2_test_pd,ω2_test_pd_P,ω3_test_pd,ω3_test_pd_P,ω0_ref_pd,ω0_ref_pd_P,ω1_ref_pd,ω1_ref_pd_P,ω2_ref_pd,ω2_ref_pd_P,ω3_ref_pd,ω3_ref_pd_P,ω_mean_test,ω_mean_ref,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit LOC,P. tepidariorum best BLAST hit description,U. diversus best BLAST hit LOC,U. diversus best BLAST hit description
46,N5.HOG0060564,intensified,1.794975e-11,1.242106,45.182548,0.282573,0.207065,3.205404e+02,2.989533e-04,0.113390,0.838814,0.353333,0.160887,1.166608,0.000000,5.060487e+02,0.000000,0.173322,0.839065,0.432763,0.160935,1.132088,0.000000,2.827192e+02,2.867180e-04,0.117649,0.736989,0.223756,0.262724,8.273864,0.000000,2.798144e+02,0.000000,0.041166,0.419772,0.369513,5.802280e-01,1.739584,0.000000,0.151960,0.215075,129225508,GO:0032958 [Name: inositol phosphate biosynthe...,Inositol phosphate kinase 2,LOC107444393,inositol polyphosphate multikinase,LOC129225508,inositol polyphosphate multikinase-like
122,N5.HOG0037768,intensified,2.608851e-05,1.200034,17.683461,0.178519,0.130200,3.960071e+02,1.315228e-03,0.003714,0.126552,0.102937,0.856464,1.000000,0.015669,1.229980e+02,0.000165,0.009440,0.126698,0.150372,0.857451,1.000000,0.015687,3.738820e+02,1.410115e-03,0.009580,0.316625,0.141377,0.681965,1.010475,0.000000,1.758686e+02,0.000402,0.095203,0.593301,0.140597,3.597045e-01,1.156151,0.046593,0.104301,0.145820,129222813,GO:2000272 [Name: negative regulation of recep...,CB1 cannabinoid receptor-interacting protein 1...,LOC107454249,CB1 cannabinoid receptor-interacting protein 1,LOC129222813,CB1 cannabinoid receptor-interacting protein 1...
146,N5.HOG0068715,relaxed,8.376131e-03,0.900309,6.951237,0.051662,0.058590,1.999279e+02,0.000000e+00,0.000000,0.562697,0.066199,0.406671,1.000000,0.030632,2.072589e+02,0.000000,0.000000,0.562697,0.049010,0.406671,1.000000,0.030632,4.978669e+02,0.000000e+00,0.000000,0.517664,0.056553,0.448508,1.000000,0.033828,2.072589e+02,0.000000,0.000000,0.534452,0.044669,4.346187e-01,1.000000,0.030930,0.057553,0.050563,129232140,GO:0004930 [Name: G-protein coupled receptor a...,probable G-protein coupled receptor AH9.1,LOC107451782,probable G-protein coupled receptor AH9.1,LOC129232140,probable G-protein coupled receptor AH9.1
147,N5.HOG0019920,intensified,1.309230e-06,1.069434,23.409608,0.096838,0.097535,8.296899e+04,5.658401e-04,0.061742,0.999434,1.000000,0.000000,2.762661,0.000000,1.000000e+10,0.000072,0.073978,0.999928,1.000000,0.000000,2.586271,0.000000,1.510591e+05,5.658465e-04,0.061334,0.999434,0.730814,0.000000,8.080776,0.000000,1.000000e+10,0.000072,0.074880,0.999928,0.730814,0.000000e+00,8.080776,0.000000,0.061707,0.073973,129222487,GO:0005515 [Name: protein binding]; GO:0007052...,mitogen-activated protein kinase-binding prote...,LOC107456011,mitogen-activated protein kinase-binding prote...,LOC129222487,LOW QUALITY PROTEIN: mitogen-activated protein...
162,N5.HOG0035805,relaxed,1.685055e-07,0.874394,27.364394,0.030676,0.047009,1.034693e+02,0.000000e+00,0.028075,0.000000,0.028349,1.000000,1.005431,0.000000,5.068216e+03,0.000170,0.016805,0.000000,0.016992,0.999830,1.006213,0.000000,2.053290e+02,0.000000e+00,0.016805,0.000000,0.028106,1.000000,2.286005,0.000000,5.053383e+03,0.000166,0.005051,0.000000,0.017243,9.998336e-01,1.009295,0.000000,0.028349,0.016989,129221294,GO:0016020 [Name: membrane]; GO:0007186 [Name:...,somatostatin receptor type 2-like,LOC107456079,somatostatin receptor type 2-like,LOC129221294,somatostatin receptor type 2-like
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1890,N5.HOG0053800,relaxed,2.082151e-08,0.888680,31.416397,0.070764,0.109130,1.000000e+10,3.080611e-04,0.069489,0.005624,0.078511,0.992464,2.413258,0.001603,3.054158e+02,0.000000,0.049756,0.005626,0.057082,0.992770,2.694824,0.001604,1.000000e+10,3.164379e-04,0.079951,0.999684,0.127451,0.000000,1.010475,0.000000,2.108767e+02,0.000000,0.045189,0.981715,1.000000,5.050113e-07,1.261712,0.018284,0.082178,0.061271,129223440,GO:0034097 [Name: response to cytokine]; GO:00...,embryonic polarity protein dorsal-like,LOC107442783,embryonic polarity protein dorsal isoform X2,LOC129223440,embryonic polarity protein dorsal-like
1907,N5.HOG0032433,intensified,4.526478e-04,1.130057,12.301280,0.030896,0.021832,2.500261e+02,2.177087e-19,0.013620,0.909820,0.024517,0.088941,3.399922,0.001238,1.075636e+02,0.000000,0.022331,0.909820,0.037568,0.088941,2.953266,0.001238,2.577208e+02,2.177087e-19,0.010262,0.177260,0.014065,0.820053,2.314187,0.002687,5.164726e+02,0.000000,0.025184,1.000000,0.029835,0.000000e+00,5.957346,0.000000,0.018782,0.027316,129233910,GO:0005634 [Name: nucleus]; GO:0090090 [Name: ...,glycogen synthase kinase-3 beta-like,LOC107443254,glycogen synthase kinase-3 beta,LOC129233910,glycogen synthase kinase-3 beta-like
1981,N5.HOG0049782,intensified,2.010248e-02,1.056589,5.402973,0.143761,0.135606,1.047639e+02,0.000000e+00,0.000003,0.000000,0.088735,1.000000,1.019643,0.000000,1.703609e+03,0.000090,0.000005,0.000000,0.101026,0.999910,1.018581,0.000000,4.890105e+02,0.000000e+00,0.000025,0.000000,0.087891,1.000000,6.814566,0.000000,5.266375e+03,0.000107,0.101741,0.999893,0.903609,0.000000e+00,2.413033,0.000000,0.088735,0.101017,129224572,GO:0005524 [Name: ATP binding]; GO:0004335 [Na...,galactokinase-like,LOC107452728,galactokinase,LOC129224572,galactokinase-like
2110,N5.HOG0060437,intensified,1.848932e-05,1.185724,18.338898,0.016248,0.008000,1.000000e+02,0.000000e+00,0.005641,0.996372,0.006965,0.001132,1.011963,0.002496,1.000000e+02,0.000152,0.012693,0.996221,0.015164,0.001132,1.010080,0.002495,1.000000e+02,0.000000e+00,0.005732,0.997791,0.996456,0.000000,1.078470,0.002209,1.000000e+02,0.000000,0.012600,0.997310,0.801207,2.315892e-03,19.360939,0.000374,0.008154,0.015183,129223920,GO:0005515 [Name: protein binding]; GO:0005737...,guanine nucleotide-binding protein subunit beta-5,LOC107439029,guanine nucleotide-binding protein subunit beta-5,LOC129223920,guanine nucleotide-binding protein subunit bet...
2156,N5.HOG0054457,intensified,3.972466e-09,1.098640,34.637177,0.137612,0.111946,1.996789e+02,0.000000e+00,0.083628,1.000000,0.623894,0.000000,1.066321,0.000000,1.293680e+02,0.000000,0.104498,1.000000,0.650888,0.000000,1.060191,0.000000,1.346876e+02,0.000000e+00,0.082661,1.000000,0.650888,0.000000,7.327190,0.000000,1.224025e+02,0.000000,0.106492,1.000000,0.650888,0.000000e+00,2.418639,0.000000,0.083628,0.104498,129220609,GO:0016020 [Name: membrane]; GO:0004930 [Name:...,uncharacterized LOC129220609,LOC107436875,uncharacterized protein isoform X1,LOC129220609,uncharacterized protein LOC129220609

In [47]:
busted_previous_interesting_df = busted_df[busted_df['HOG'].isin(previous_interesting['HOG'])]
busted_previous_interesting_df

Empty DataFrame
Columns: [HOG, foreground, test_pval, test_LRT, background_pval, background_LRT, shared_pval, shared_LRT, MG94xREV_ω_test, MG94xREV_ω_ref, ω0_test, ω0_test_P, ω1_test, ω1_test_P, ω2_test, ω2_test_P, ω3_test, ω3_test_P, ω0_ref, ω0_ref_P, ω1_ref, ω1_ref_P, ω2_ref, ω2_ref_P, ω3_ref, ω3_ref_P, ω0_test_null, ω0_test_null_P, ω1_test_null, ω1_test_null_P, ω2_test_null, ω2_test_null_P, ω3_test_null, ω3_test_null_P, ω0_ref_null, ω0_ref_null_P, ω1_ref_null, ω1_ref_null_P, ω2_ref_null, ω2_ref_null_P, ω3_ref_null, ω3_ref_null_P, ω_mean_test, ω_mean_ref, U. diversus gene ID, U. diversus GO terms, U. diversus gene description, P. tepidariorum best BLAST hit LOC, P. tepidariorum best BLAST hit description, U. diversus best BLAST hit LOC, U. diversus best BLAST hit description]
Index: []

## Spider accessions and BUSCO scores

In [48]:
buscos = pd.read_csv(f'{data}/orthorun_list_fams_busco90.csv')
accessions = pd.read_csv(f'{data}/txptome_accessions.csv')
accessions.drop(columns=['Infraorder', 'Family', 'Web_Type', 'Cribellum'], inplace=True)

buscos_accessions = pd.merge(buscos, accessions, on='Species', how='left')

buscos_accessions.drop_duplicates(inplace=True)
buscos_accessions.dropna(how='any', inplace=True)
buscos_accessions.reset_index(drop=True, inplace=True)
# Collapse rows: group by all columns except 'Accession', join 'Accession' values as comma-separated string
buscos_accessions.rename(columns={'Single': 'Single_copy_BUSCOs', 'Duplicated': 'Duplicated_BUSCOs', 'Total': 'Total_BUSCOs'}, inplace=True)
buscos_accessions.shape[0]

102

In [49]:
buscos_accessions.to_excel(f'{results}/Supplementary_Table_1_SpiderAccessions_BUSCOs.xlsx', index=False)

In [50]:
# Count rows with NaN in the 'Accession' column before collapsing
num_nan_accession = buscos_accessions['Accession'].isna().sum()
print(f"Rows with NaN in 'Accession': {num_nan_accession}")

Rows with NaN in 'Accession': 0

## N5 HOGs

this is just to make the format match the others

In [27]:
n5_hogs = pd.read_csv(f'{data}/N5.tsv', sep='\t')
n5_hogs

/var/folders/bh/l9d0n24d5011lh6bfqzp4n7r0000gn/T/ipykernel_83737/2966892365.py:1: DtypeWarning: Columns (3,4,5,6,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,36,37,39,40,41,42,43,44,45,46,47,48,49,51,52,53,54,55,56,57,58,59,60,61,62,63,64,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94) have mixed types. Specify dtype option on import or set low_memory=False.
  n5_hogs = pd.read_csv(f'{data}/N5.tsv', sep='\t')

,HOG,OG,Gene Tree Parent Clade,Acroaspis_sp_IDV6688,Acrosomoides_sp_IDV7426,Ainerigone_saitoi,Ambicodamus_IDV6680,Antrodiaetus_roretzi,Araneus_inustus,Arcuphantes_paiki,Arcuphantes_tamaensis,Arcuphantes_uenoi,Argiope_aetheroides,Argiope_bruennichi,Argiope_keyserlingi,Argyrodes_flavescens,Argyrodes_miniaceus,Backobourkia_brouni,Baryphymula_kamakuraensis,Caerostris_darwini,Caerostris_extrusa,Chrysso_octomaculata,Clubiona_robusta,Cryptachaea_gigantipes,Cyclosa_octotuberculata,Cyrtarachne_bufo,Cyrtophora_cicatrosa,Deinopis_sp_IDV6783,Deinopis_sp_IDV7365,Desis_marina,Diaea_subdola,Doenitzius_peniculus,Doenitzius_pruvus,Dolophones_sp_IDV6683,Drapetisca_socialis,Drosophila_melanogaster,Ebrechtella_tricuspidata,Eriophora_pustulosa,Falcileptoneta_japonica,Floronia_bucculenta,Gnathonarium_exsiccatum,Helpis_minitabunda,Hypselistes_asiaticus,Hypsosinga_pygmaea,Larinia_phthisica,Lariniaria_argiopiformis,Larinioides_cornutus,Latrodectus_hasseltii,Lehtinelagia_evanida,Leucauge_dromedari,Masirana_silvicola,Mesida_sp_IDV5268,Metazygia_zilloides,Metleucauge_yunohamensis,Microbathyphantes_tateyamaensis,Neoantistea_quelpartensis,Neon_minutus,Neoscona_adianta,Neoscona_nautica,Neoscona_scylla,Neoscona_subpullata,Neoscona_theisi,Neriene_clathrata,Neriene_oidedicata,Nuctenea_umbratica,Orchestina_okitsui,Ordgarius_hobsoni,Ordgarius_sexspinosus,Oxytate_striatipes,Ozyptila_nongae,Parasteatoda_culicivora,Paratheuma_awasensis,Pardosa_graminea,Pharta_brevipalpus,Phonognatha_graeffei,Phrurolithus_coreanus,Piratula_tanakai,Plebs_sachalinensis,Poecilopachys_australasia,Psechrus_IDV5238,Pseudomicrargus_latitegulatus,Rhomphaea_labiata,Robertus_nojimai,Ryojius_japonicus,Saaristoa_nipponica,Saitonia_ojiroensis,Steatoda_grossa,Stephanopis_cambridgei,Stertinius_kumadai,Syedra_oii,Tekellina_sadamotoi,Tetragnatha_brevignatha,Tetragnatha_extensa,Tetragnatha_filiciphilia,Tetragnatha_mandibulata,Tetragnatha_maxillosa,Tetragnatha_paludicola,Tetragnatha_quasimodo,Tetragnatha_stelarobusta,Tetragnatha_vermiformis,Tetragnatha_waikamoi,Tetragnatha_yesoensis,Theridion_varians,Uloborus_diversus,Ummeliata_osakaensis,Zelotes_iriomotensis
0,N5.HOG0000000,OG0000000,n6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBHE01016182.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBYA01011843.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N5.HOG0000001,OG0000000,n10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAJV01004504.1.p1, IAJV01032038.1.p1",IAFI01007613.1.p1,IAHZ01018353.1.p1,NaN,NaN,IBHV01013931.1.p1,NaN,ICDG01046476.1.p1,NaN,IBVS01009860.1.p1,NaN,NaN,NaN,IBRX01018078.1.p1,"ICBF01004250.1.p1, ICBF01032375.1.p1",IAEU01028549.1.p2,"IBPZ01042485.1.p1, IBPZ01001432.1.p1","IAXT01039719.1.p1, IAXT01003871.1.p1",NaN,NaN,"IAPM01038371.1.p1, IAPM01013637.1.p1, IAPM0102...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GITM01041654.1.p1,IAHF01031891.1.p1,GITN01024129.1.p1,ICFC01017347.1.p1,"ICMP01008935.1.p1, ICMP01020576.1.p1",GITO01026887.1.p1,GITP01051515.1.p1,GITQ01067807.1.p1,IAJJ01011887.1.p1,GITR01106566.1.p1,IBMZ01020084.1.p1,NaN,NaN,NaN,NaN
2,N5.HOG0000002,OG0000000,n40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IASB01000065.1.p1,NaN,IAET01037148.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBJP01018148.1.p1,IBVW01007283.1.p1,NaN,NaN,NaN,NaN,IBIK01042678.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBDY01023263.1.p1,IBVS01007432.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IALM01040017.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ICHT01027615.1.p1, ICHT01017775.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N5.HOG0000003,OG0000000,n50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICCG01026617.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAQZ01002733.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAUM01007052.1.p1,NaN,NaN,NaN,NaN,IAHZ01017123.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N5.HOG0000004,OG0000000,n54,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICCG01017817.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAQZ01033432.1.p1,NaN,NaN,NaN,ICOI01021205.1.p1,NaN,NaN,NaN,NaN,"IBZG01014388.1.p1, IBZG01025934.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAOT01017345.1.p1,ICEG01003535.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IBDY01001551.1.p1, IBDY01030445.1.p1",NaN,ICFH01038389.1.p1,NaN,IAIC01008931.1.p1,IBRX01015679.1.p1,NaN,IAEU01025729.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAGL01014301.1.p1,ICMU01023364.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"GJZJ01103430.1.p1, GJZJ01279486.1.p1, GJZJ0101...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107981,N5.HOG0107981,OG0046213,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01041866.1.p2, IAHP01035491.1.p2"
107982,N5.HOG0107982,OG0046214,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01042646.1.p2, IAHP01035715.1.p2"
107983,N5.HOG0107983,OG0046215,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01041096.1.p1, IAHP01036455.1.p1"
107984,N5.HOG0107984,OG0046216,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01037270.1.p1, IAHP01039697.1.p1"
107985,N5.HOG0107985,OG0046217,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01038618.1.p1, IAHP01041943.1.p1"

In [28]:
# Count non-NaN entries across species columns (from current 4th column to end)
occupancy = n5_hogs.iloc[:, 3:].notna().sum(axis=1)

# Ensure "Occupancy" is placed between "Gene Tree Parent Clade" and "Acroaspis_sp_IDV6688"
if "Occupancy" in n5_hogs.columns:
    n5_hogs = n5_hogs.drop(columns=["Occupancy"])

n5_hogs.insert(3, "Occupancy", occupancy)

n5_hogs

,HOG,OG,Gene Tree Parent Clade,Occupancy,Acroaspis_sp_IDV6688,Acrosomoides_sp_IDV7426,Ainerigone_saitoi,Ambicodamus_IDV6680,Antrodiaetus_roretzi,Araneus_inustus,Arcuphantes_paiki,Arcuphantes_tamaensis,Arcuphantes_uenoi,Argiope_aetheroides,Argiope_bruennichi,Argiope_keyserlingi,Argyrodes_flavescens,Argyrodes_miniaceus,Backobourkia_brouni,Baryphymula_kamakuraensis,Caerostris_darwini,Caerostris_extrusa,Chrysso_octomaculata,Clubiona_robusta,Cryptachaea_gigantipes,Cyclosa_octotuberculata,Cyrtarachne_bufo,Cyrtophora_cicatrosa,Deinopis_sp_IDV6783,Deinopis_sp_IDV7365,Desis_marina,Diaea_subdola,Doenitzius_peniculus,Doenitzius_pruvus,Dolophones_sp_IDV6683,Drapetisca_socialis,Drosophila_melanogaster,Ebrechtella_tricuspidata,Eriophora_pustulosa,Falcileptoneta_japonica,Floronia_bucculenta,Gnathonarium_exsiccatum,Helpis_minitabunda,Hypselistes_asiaticus,Hypsosinga_pygmaea,Larinia_phthisica,Lariniaria_argiopiformis,Larinioides_cornutus,Latrodectus_hasseltii,Lehtinelagia_evanida,Leucauge_dromedari,Masirana_silvicola,Mesida_sp_IDV5268,Metazygia_zilloides,Metleucauge_yunohamensis,Microbathyphantes_tateyamaensis,Neoantistea_quelpartensis,Neon_minutus,Neoscona_adianta,Neoscona_nautica,Neoscona_scylla,Neoscona_subpullata,Neoscona_theisi,Neriene_clathrata,Neriene_oidedicata,Nuctenea_umbratica,Orchestina_okitsui,Ordgarius_hobsoni,Ordgarius_sexspinosus,Oxytate_striatipes,Ozyptila_nongae,Parasteatoda_culicivora,Paratheuma_awasensis,Pardosa_graminea,Pharta_brevipalpus,Phonognatha_graeffei,Phrurolithus_coreanus,Piratula_tanakai,Plebs_sachalinensis,Poecilopachys_australasia,Psechrus_IDV5238,Pseudomicrargus_latitegulatus,Rhomphaea_labiata,Robertus_nojimai,Ryojius_japonicus,Saaristoa_nipponica,Saitonia_ojiroensis,Steatoda_grossa,Stephanopis_cambridgei,Stertinius_kumadai,Syedra_oii,Tekellina_sadamotoi,Tetragnatha_brevignatha,Tetragnatha_extensa,Tetragnatha_filiciphilia,Tetragnatha_mandibulata,Tetragnatha_maxillosa,Tetragnatha_paludicola,Tetragnatha_quasimodo,Tetragnatha_stelarobusta,Tetragnatha_vermiformis,Tetragnatha_waikamoi,Tetragnatha_yesoensis,Theridion_varians,Uloborus_diversus,Ummeliata_osakaensis,Zelotes_iriomotensis
0,N5.HOG0000000,OG0000000,n6,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBHE01016182.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBYA01011843.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,N5.HOG0000001,OG0000000,n10,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAJV01004504.1.p1, IAJV01032038.1.p1",IAFI01007613.1.p1,IAHZ01018353.1.p1,NaN,NaN,IBHV01013931.1.p1,NaN,ICDG01046476.1.p1,NaN,IBVS01009860.1.p1,NaN,NaN,NaN,IBRX01018078.1.p1,"ICBF01004250.1.p1, ICBF01032375.1.p1",IAEU01028549.1.p2,"IBPZ01042485.1.p1, IBPZ01001432.1.p1","IAXT01039719.1.p1, IAXT01003871.1.p1",NaN,NaN,"IAPM01038371.1.p1, IAPM01013637.1.p1, IAPM0102...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GITM01041654.1.p1,IAHF01031891.1.p1,GITN01024129.1.p1,ICFC01017347.1.p1,"ICMP01008935.1.p1, ICMP01020576.1.p1",GITO01026887.1.p1,GITP01051515.1.p1,GITQ01067807.1.p1,IAJJ01011887.1.p1,GITR01106566.1.p1,IBMZ01020084.1.p1,NaN,NaN,NaN,NaN
2,N5.HOG0000002,OG0000000,n40,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IASB01000065.1.p1,NaN,IAET01037148.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBJP01018148.1.p1,IBVW01007283.1.p1,NaN,NaN,NaN,NaN,IBIK01042678.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBDY01023263.1.p1,IBVS01007432.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IALM01040017.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ICHT01027615.1.p1, ICHT01017775.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,N5.HOG0000003,OG0000000,n50,4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICCG01026617.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAQZ01002733.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAUM01007052.1.p1,NaN,NaN,NaN,NaN,IAHZ01017123.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,N5.HOG0000004,OG0000000,n54,14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICCG01017817.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAQZ01033432.1.p1,NaN,NaN,NaN,ICOI01021205.1.p1,NaN,NaN,NaN,NaN,"IBZG01014388.1.p1, IBZG01025934.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAOT01017345.1.p1,ICEG01003535.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IBDY01001551.1.p1, IBDY01030445.1.p1",NaN,ICFH01038389.1.p1,NaN,IAIC01008931.1.p1,IBRX01015679.1.p1,NaN,IAEU01025729.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAGL01014301.1.p1,ICMU01023364.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"GJZJ01103430.1.p1, GJZJ01279486.1.p1, GJZJ0101...",NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107981,N5.HOG0107981,OG0046213,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01041866.1.p2, IAHP01035491.1.p2"
107982,N5.HOG0107982,OG0046214,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01042646.1.p2, IAHP01035715.1.p2"
107983,N5.HOG0107983,OG0046215,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01041096.1.p1, IAHP01036455.1.p1"
107984,N5.HOG0107984,OG0046216,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01037270.1.p1, IAHP01039697.1.p1"
107985,N5.HOG0107985,OG0046217,-,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IAHP01038618.1.p1, IAHP01041943.1.p1"

Filter to occupancy 30+ (all analyses in the paper used minimum occupancy of 30, 50 or 75)

In [29]:
n5_hogs_occ_30 = n5_hogs[n5_hogs['Occupancy'] >= 30]
n5_hogs_occ_30

,HOG,OG,Gene Tree Parent Clade,Occupancy,Acroaspis_sp_IDV6688,Acrosomoides_sp_IDV7426,Ainerigone_saitoi,Ambicodamus_IDV6680,Antrodiaetus_roretzi,Araneus_inustus,Arcuphantes_paiki,Arcuphantes_tamaensis,Arcuphantes_uenoi,Argiope_aetheroides,Argiope_bruennichi,Argiope_keyserlingi,Argyrodes_flavescens,Argyrodes_miniaceus,Backobourkia_brouni,Baryphymula_kamakuraensis,Caerostris_darwini,Caerostris_extrusa,Chrysso_octomaculata,Clubiona_robusta,Cryptachaea_gigantipes,Cyclosa_octotuberculata,Cyrtarachne_bufo,Cyrtophora_cicatrosa,Deinopis_sp_IDV6783,Deinopis_sp_IDV7365,Desis_marina,Diaea_subdola,Doenitzius_peniculus,Doenitzius_pruvus,Dolophones_sp_IDV6683,Drapetisca_socialis,Drosophila_melanogaster,Ebrechtella_tricuspidata,Eriophora_pustulosa,Falcileptoneta_japonica,Floronia_bucculenta,Gnathonarium_exsiccatum,Helpis_minitabunda,Hypselistes_asiaticus,Hypsosinga_pygmaea,Larinia_phthisica,Lariniaria_argiopiformis,Larinioides_cornutus,Latrodectus_hasseltii,Lehtinelagia_evanida,Leucauge_dromedari,Masirana_silvicola,Mesida_sp_IDV5268,Metazygia_zilloides,Metleucauge_yunohamensis,Microbathyphantes_tateyamaensis,Neoantistea_quelpartensis,Neon_minutus,Neoscona_adianta,Neoscona_nautica,Neoscona_scylla,Neoscona_subpullata,Neoscona_theisi,Neriene_clathrata,Neriene_oidedicata,Nuctenea_umbratica,Orchestina_okitsui,Ordgarius_hobsoni,Ordgarius_sexspinosus,Oxytate_striatipes,Ozyptila_nongae,Parasteatoda_culicivora,Paratheuma_awasensis,Pardosa_graminea,Pharta_brevipalpus,Phonognatha_graeffei,Phrurolithus_coreanus,Piratula_tanakai,Plebs_sachalinensis,Poecilopachys_australasia,Psechrus_IDV5238,Pseudomicrargus_latitegulatus,Rhomphaea_labiata,Robertus_nojimai,Ryojius_japonicus,Saaristoa_nipponica,Saitonia_ojiroensis,Steatoda_grossa,Stephanopis_cambridgei,Stertinius_kumadai,Syedra_oii,Tekellina_sadamotoi,Tetragnatha_brevignatha,Tetragnatha_extensa,Tetragnatha_filiciphilia,Tetragnatha_mandibulata,Tetragnatha_maxillosa,Tetragnatha_paludicola,Tetragnatha_quasimodo,Tetragnatha_stelarobusta,Tetragnatha_vermiformis,Tetragnatha_waikamoi,Tetragnatha_yesoensis,Theridion_varians,Uloborus_diversus,Ummeliata_osakaensis,Zelotes_iriomotensis
42,N5.HOG0000042,OG0000000,n521,30,NaN,NaN,IBTE01045250.1.p1,NaN,NaN,NaN,NaN,IAKU01033670.1.p2,NaN,NaN,NaN,IAET01038018.1.p1,IAFU01017320.1.p2,IBQT01027662.1.p2,ICCG01023241.1.p1,IBGF01007960.1.p3,NaN,NaN,NaN,NaN,NaN,IAQZ01013625.1.p2,NaN,IBHY01031234.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"IBIK01029058.1.p2, IBIK01035878.1.p1",NaN,"ICGA01033433.1.p2, ICGA01025359.1.p2",NaN,NaN,IAOT01038489.1.p3,NaN,"IAJV01010093.1.p1, IAJV01019277.1.p1",NaN,IAHZ01019957.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IBVS01042499.1.p1,ICFH01001894.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAXT01012028.1.p2,NaN,NaN,"IAPM01002546.1.p1, IAPM01007779.1.p1",NaN,NaN,ICMU01011756.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IATW01039505.1.p1,NaN,NaN,"ICHT01026571.1.p1, ICHT01009148.1.p1",NaN,NaN,IBJR01049059.1.p3,ICFA01019693.1.p2,ICAL01003840.1.p1,NaN,IBAR01011710.1.p1,NaN,"IAPP01031453.1.p1, IAPP01018406.1.p1, IAPP0100...",NaN,NaN,IAXS01029553.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GITP01099019.1.p1,GITQ01074980.1.p1,NaN,NaN,IBMZ01047024.1.p1,NaN,NaN,NaN,NaN
52,N5.HOG0000052,OG0000000,n667,30,NaN,NaN,NaN,ICBW01009633.1.p1,NaN,IAHS01041868.1.p1,NaN,IAKU01006172.1.p1,IBBK01025117.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"ICOE01034450.1.p1, ICOE01020152.1.p1",NaN,NaN,NaN,NaN,NaN,IBHY01006183.1.p1,NaN,NaN,NaN,ICGF01019809.1.p1,NaN,IBVW01012136.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICEG01034146.1.p1,IAJV01041573.1.p1,IAFI01040479.1.p1,IAHZ01026716.1.p1,NaN,IBFM01010861.1.p1,NaN,NaN,NaN,IBDY01012329.1.p1,IBVS01036228.1.p1,NaN,NaN,IAIC01019294.1.p1,"IBRX01015955.1.p1, IBRX01015087.1.p1",ICBF01028066.1.p1,IAEU01018909.1.p1,IBPZ01016824.1.p1,NaN,"IAFP01028931.1.p1, IAFP01007703.1.p1, IAFP0100...",IAQC01004191.1.p1,NaN,NaN,NaN,NaN,IALM01031986.1.p1,ICBR01046734.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICFA01036094.1.p1,NaN,IBWO01022169.1.p1,NaN,NaN,NaN,ICHM01016774.1.p1,"IAUC01015023.1.p1, IAUC01043947.1.p3, IAUC0104...",IAXS01007743.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAHP01002859.1.p1
147,N5.HOG0000147,OG0000000,n1866,34,IANO01045459.1.p1,ICOJ01034563.1.p1,NaN,NaN,NaN,IAHS01010517.1.p1,NaN,NaN,NaN,IASB01004179.1.p1,IBFJ01008057.1.p1,IAET01001136.1.p1,NaN,NaN,NaN,NaN,ICOF01016127.1.p1,ICOE01010111.1.p1,NaN,NaN,NaN,IAQZ01021454.1.p1,ICFD01036047.1.p1,"IBHY01036715.1.p1, IBHY01023209.1.p1, IBHY0102...",NaN,NaN,GIWQ01381602.1.p1,NaN,NaN,NaN,IBZG01032581.1.p1,NaN,NaN,NaN,IBIK01028214.1.p1,NaN,NaN,NaN,NaN,NaN,ICEG01018260.1.p1,NaN,NaN,NaN,NaN,NaN,IBHV01007634.1.p1,NaN,NaN,IBDY01031959.1.p1,"IBVS01031350.1.p1, IBVS01009057.1.p1","ICFH01036969.1.p1, ICFH01009273.1.p1",NaN,NaN,IBRX01012041.1.p1,ICBF01026346.1.p1,IAEU01009270.1.p1,IBPZ01024792.1.p1,IAXT01012292.1.p1,NaN,NaN,IAPM01019489.1.p1,NaN,IAGL01002019.1.p1,ICMU01001930.1.p1,NaN,NaN,NaN,IARK01036035.1.p1,NaN,NaN,IATW01005412.1.p1,NaN,NaN,ICHT01034227.1.p1,ICKB01015416.1.p1,IAQN01003844.1.p1,NaN,NaN,NaN,IBWO01038624.1.p1,NaN,NaN,IAPP01000817.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,N5.HOG0000196,OG0000000,n2556,46,IANO01032399.1.p1,ICOJ01037145.1.p1,NaN,ICBW01020954.1.p1,NaN,IAHS01007736.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,IAFU01008817.1.p1,IBQT01025194.1.p1,NaN,IBGF01043878.1.p1,ICOF01006072.1.p1,NaN,NaN,NaN,NaN,NaN,ICFD01014754.1.p1,IBHY01005130.1.p1,IBBP01002725.1.p1,NaN,NaN,ICGF01010448.1.p1,NaN,IBVW01042278.1.p1,"IBZG01018677.1.p1, IBZG01004248.1.p1",NaN,NaN,NaN,IBIK01041139.1.p1,NaN,ICGA01034284.1.p1,ICCR01015754.1.p1,NaN,NaN,NaN,IAJV01031018.1.p1,NaN,IAHZ01041432.1.p1,IBKS01003116.1.p1,NaN,IBHV01011975.1.p1,NaN,NaN,NaN,IBVS01016666.1.p1,ICFH01015354.1.p1,NaN,NaN,IBRX01034936.1.p1,NaN,NaN,IBPZ01017323.1.p1,IAXT01001688.1.p1,IAFP01018621.1.p1,NaN,NaN,NaN,"IAGL01040560.1.p1, IAGL01031492.1.p1",ICMU01000314.1.p1,IALM01039207.1.p1,ICBR01028520.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICHT01020831.1.p1,NaN,NaN,IBJR01014622.1.p1,ICFA01004483.1.p1,ICAL01010752.1.p1,IBWO01026510.1.p1,IBAR01012902.1.p1,NaN,NaN,NaN,NaN,NaN,IALE01037253.1.p1,NaN,NaN,GITN01088792.1.p1,NaN,"ICMP01041011.1.p1, ICMP01002610.1.p1","GITO01054842.1.p1, GITO01000601.1.p1",NaN,GITQ01025507.1.p1,IAJJ01017983.1.p1,GITR01102608.1.p1,"IBMZ01028119.1.p1, IBMZ01009689.1.p1",NaN,NaN,IBXZ01011769.1.p1,NaN
276,N5.HOG0000276,OG0000000,n3453,30,IANO01031715.1.p1,ICOJ01034962.1.p1,NaN,NaN,NaN,IAHS01033255.1.p1,NaN,NaN,NaN,IASB01012130.1.p1,IBFJ01030513.1.p1,IAET01007769.1.p1,NaN,NaN,ICCG01027298.1.p1,NaN,ICOF01000903.1.p1,ICOE01014025.1.p1,NaN,NaN,NaN,IAQZ01013785.1.p1,ICFD01041007.1.p1,IBHY01041380.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,"IBZG01009391.1.p1, IBZG01029040.1.p1",NaN,NaN,NaN,IBIK01022906.1.p1,NaN,NaN,NaN,NaN,NaN,ICEG01030255.1.p1,IAJV01027646.1.p1,IAFI01011162.1.p1,IAHZ01030342.1.p1,NaN,NaN,NaN,NaN,NaN,IBDY01015241.1.p1,NaN,NaN,NaN,NaN,IBRX01019363.1.p1,ICBF01039514.1.p1,IAEU01041650.1.p1,IBPZ01047814.1.p1,IAXT01028253.1.p1,NaN,NaN,IAPM01041038.1.p1,NaN,IAGL01036927.1.p1,"ICMU01021987.1.p1, ICMU01013273.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,IATW01023225.1.p1,NaN,NaN,ICHT01014576.1.p1,ICKB01005891.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73724,N5.HOG0073724,OG0010664,n0,31,NaN,ICOJ01040730.1.p1,IBTE01046677.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAFU01008057.1.p1,IBQT01038485.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBHY01016117.1.p1,NaN,NaN,GIWQ01135313.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICGA01040230.1.p1,NaN,NaN,IAOT01035970.1.p1,NaN,IAJV01034819.1.p1,IAFI01041558.1.p1,NaN,NaN,NaN,NaN,NaN,ICDG01042469.1.p1,NaN,IBVS01020873.1.p1,NaN,NaN,NaN,IBRX01013188.1.p1,NaN,IAEU01019630.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBTW01026556.1.p1,IARK01001627.1.p1,ICDS01023904.1.p1,NaN,NaN,NaN,NaN,ICHT01036049.1.p1,NaN,IAQN01035291.1.p1,NaN,ICFA01018177.1.p1,NaN,NaN,NaN,NaN,IAPP01018210.1.p1,NaN,NaN,NaN,NaN,GITM01003150.1.p1,NaN,GITN01079596.1.p1,ICFC01006401.1.p1,ICMP01009837.1.p1,GITO01024665.1.p1,"GITP01082162.1.p1, GITP01071870.1.p1",GITQ01001293.1.p1,IAJJ01034856.1.p1,GITR01008734.1.p1,IBMZ01008021.1.p1,NaN,NaN,NaN,NaN
73740,N5.HOG0073740,OG0010674,n0,30,NaN,NaN,NaN,ICBW01000105.1.p2,NaN,NaN,IAWN01030888.1.p1,NaN,IBBK01018300.1.p1,NaN,NaN,NaN,NaN,IBQT01004616.1.p1,NaN,IBGF01047311.1.p1,NaN,NaN,NaN,ICJS01011875.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,GIWQ01117802.1.p1,ICGF01041525.1.p1,IBJP01030739.1.p1,NaN,IBZG01034776.1.p1,NaN,NaN,ICBZ01025532.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBFM01004794.1.p1,NaN,NaN,ICDG01020384.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,ICBF01027551.1.p2,NaN,IBPZ01002143.1.p3,NaN,IAFP01023432.1.p1,NaN,NaN,NaN,NaN,NaN,IALM01033208.1.p1,NaN,NaN,IARK01026543.1.p2,ICDS01003106.1.p3,IAWA01000034.1.p2,IATW01008106.1.p1,IBPN01003877.1.p1,IBYA01043291.1.p1,NaN,NaN,IAQN01022845.1.p1,NaN,ICFA01032641.1.p1,ICAL01014058.1.p1,IBWO01011520.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICMP01043134.1.p1,NaN,NaN,NaN,NaN,NaN,IBMZ01023210.1.p2,NaN,jg24230.t1.p1,NaN,NaN
73766,N5.HOG0073766,OG0010684,n0,30,NaN,NaN,NaN,NaN,NaN,IAHS01040657.1.p1,IAWN01008785.1.p2,IAKU01006408.1.p2,IBBK01028251.1.p2,NaN,NaN,NaN,IAFU01037065.1.p1,NaN,NaN,IBGF01018746.1.p1,NaN,NaN,NaN,ICJS01005026.1.p1,NaN,NaN,NaN,IBHY01021609.1.p1,IBBP01017949.1.p1,NaN,GIWQ01132137.1.p1,ICGF01019478.1.p1,IBJP01000789.1.p2,NaN,IBZG01018576.1.p1,ICKS01041030.1.p3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICEG01035043.1.p1,NaN,NaN,NaN,NaN,IBFM01020812.1.p3,NaN,NaN,NaN,NaN,NaN,ICFH01001098.1.p1,NaN,NaN,NaN,ICBF01039148.1.p1,NaN,IBPZ01015023.1.p1,IAXT01005806.1.p1,IAFP01033995.1.p1,IAQC01016858.1.p1,NaN,NaN,NaN,NaN,IALM01033509.1.p1,ICBR01030418.1.p1,NaN,NaN,ICDS01000240.1.p1,NaN,NaN,NaN,IBYA01045995.1.p1,NaN,ICKB01018174.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAXS01001729.1.p3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBMZ01046339.1.p1,NaN,GJZJ01249014.1.p1,NaN,NaN
73773,N5.HOG0073773,OG0010691,n0,32,NaN,NaN,NaN,NaN,NaN,NaN,IAWN01042058.1.p1,IAKU01018766.1.p1,IBBK01012119.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GIWQ01078670.1.p1,NaN,IBJP01036834.1.p1,NaN,IBZG01031076.1.p1,ICKS01003098.1.p1,NaN,NaN,IBIK01037113.1.p1,NaN,ICGA01010898.1.p1,ICCR01025524.1.p1,NaN,NaN,NaN,IAJV01005156.1.p1,NaN,NaN,NaN,IBFM01033393.1.p1,IBHV01023425.1.p1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ICBF01028898.1.p1,NaN,NaN,NaN,IAFP01026296.1.p1,NaN,NaN,NaN,IAGL01005682.1.p1,ICMU01000769.1.p1,NaN,NaN,NaN,IARK01008905.1.p1,ICDS01041418.1.p1,NaN,IATW01012982.1.p1,IBPN01039291.1.p1,NaN,NaN,ICKB01012518.1.p1,NaN,NaN,NaN,ICAL01021288.1.p1,IBWO01015655.1.p1,NaN,NaN,NaN,NaN,IAUC01036457.1.p1,IAXS01035856.1.p1,IALE01033371.1.p1,NaN,IAHF01001704.1.p1,NaN,ICFC01003335.1.p1,NaN,NaN,NaN,NaN,IAJJ01038305.1.p2,NaN,NaN,NaN,GJZJ01239057.1.p1,NaN,IAHP01000870.1.p1
73818,N5.HOG0073818,OG0010723,n0,30,IANO01037111.1.p1,NaN,NaN,ICBW01013549.1.p1,NaN,NaN,IAWN01024921.1.p1,NaN,NaN,IASB01025750.1.p1,NaN,NaN,NaN,NaN,NaN,IBGF01044780.1.p1,NaN,ICOE01025274.1.p1,NaN,NaN,IBTR01005915.1.p1,NaN,ICFD01035609.1.p1,NaN,NaN,NaN,GIWQ01383041.1.p1,NaN,NaN,NaN,IBZG01012975.1.p1,NaN,NaN,NaN,IBIK01005536.1.p1,NaN,NaN,NaN,NaN,NaN,ICEG01017263.1.p1,NaN,IAFI01001428.1.p1,NaN,IBKS01017448.1.p2,"IBFM01031672.1.p1, IBFM01017932.1.p1",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IAGL01007245.1.p1,NaN,NaN,NaN,IBTW01046018.1.p2,IARK01017407.1.p1,ICDS01011957.1.p1,IAWA01034949.1.p1,NaN,NaN,NaN,NaN,NaN,IAQN01018303.1.p1,NaN,NaN,ICAL01036097.1.p1,NaN,NaN,NaN,IAPP01029674.1.p1,ICHM01024813.1.p2,NaN,NaN,IALE01009140.1.p1,NaN,IAHF01049739.1.p1,NaN,ICFC01002755.1.p1,NaN,GITO01060063.1.p2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,IBXZ01047078.1.p1,IAHP01017676.1.p1

In [45]:
n5_hogs_occ_30.to_csv(f'{data}/N5_occ_30.tsv', sep='\t', index=False)

In [31]:
n5_hogs_occ_30.to_excel(f'{results}/Supplementary_Table_2_Entelegyne_HOGs.xlsx', index=False)

## PhyloGLM results

In [51]:
phyloglm = pd.read_csv(f'{results}/phyloglm/phyloglm_p_adj.csv', index_col="HOG")
phyloglm

,error,coef_(Intercept)_Estimate,coef_(Intercept)_StdErr,coef_(Intercept)_z.value,coef_(Intercept)_p.value,coef_orb_weavingTRUE_Estimate,coef_orb_weavingTRUE_StdErr,coef_orb_weavingTRUE_z.value,coef_orb_weavingTRUE_p.value,p_adj_bonferroni
HOG,,,,,,,,,,
N5.HOG0067161,NaN,-0.131217,0.111454,-1.177318,0.239069,0.462570,0.050010,9.249622,2.252871e-20,2.695110e-16
N5.HOG0062479,NaN,-0.102667,0.072843,-1.409441,0.158705,0.283759,0.032246,8.799725,1.371518e-18,1.640747e-14
N5.HOG0068083,NaN,-0.116300,0.102023,-1.139940,0.254311,0.391135,0.045379,8.619335,6.734435e-18,8.056405e-14
N5.HOG0068230,NaN,0.118418,0.062018,1.909418,0.056208,-0.274228,0.032937,-8.325893,8.369532e-17,1.001247e-12
N5.HOG0030400,NaN,1.146628,0.302901,3.785491,0.000153,-1.144605,0.137932,-8.298313,1.056000e-16,1.263293e-12
...,...,...,...,...,...,...,...,...,...,...
N5.HOG0066701,NaN,0.203044,0.124608,1.629462,0.103215,-0.312257,0.067792,-4.606109,4.102731e-06,4.908098e-02
N5.HOG0060348,NaN,0.493869,0.236504,2.088208,0.036779,-1.055627,0.229242,-4.604867,4.127303e-06,4.937492e-02
N5.HOG0061162,NaN,0.178121,0.154513,1.152796,0.248994,0.314913,0.068417,4.602884,4.166809e-06,4.984754e-02
N5.HOG0050233,NaN,0.637260,0.211430,3.014054,0.002578,-0.715788,0.155517,-4.602618,4.172129e-06,4.991118e-02
N5.HOG0065991,NaN,0.044545,0.116964,0.380840,0.703322,-0.288436,0.062672,-4.602332,4.177865e-06,4.997980e-02

In [52]:
phyloglm_sig = phyloglm.drop(columns=[
    'error', 'coef_(Intercept)_Estimate', 'coef_(Intercept)_StdErr', 'coef_(Intercept)_z.value', 'coef_(Intercept)_p.value'])
phyloglm_sig.rename(columns={
    'coef_orb_weavingTRUE_Estimate': 'Orb-weaving coefficient estimate',
    'coef_orb_weavingTRUE_StdErr': 'Orb-weaving coefficient standard error',
    'coef_orb_weavingTRUE_z.value': 'Orb-weaving coefficient z-value',
    'coef_orb_weavingTRUE_p.value': 'Orb-weaving coefficient p-value'
    }, inplace=True)

In [53]:
phyloglm_locs = convert_hogs_to_locs(phyloglm_sig, os.path.join(repo_root, "data/N5.tsv"), one_random_gene=True)
phyloglm_locs_fltrd = phyloglm_locs.drop(columns=['udiv_genes', 'dmel_orthologs', 'txpt']).drop_duplicates().reset_index(drop=True)
phyloglm_locs_fltrd = move_column(phyloglm_locs_fltrd, 'HOG', 0)
phyloglm_locs_fltrd.rename(columns={
    'LOC': 'U. diversus gene ID',
    'GO_terms': 'U. diversus GO terms',
    'Description': 'U. diversus gene description'
    }, inplace=True)
phyloglm_locs_fltrd

Processing HOGs: 100%|██████████| 337/337 [00:00<00:00, 30091.98it/s]

,HOG,Orb-weaving coefficient estimate,Orb-weaving coefficient standard error,Orb-weaving coefficient z-value,Orb-weaving coefficient p-value,p_adj_bonferroni,U. diversus gene ID,U. diversus GO terms,U. diversus gene description
0,N5.HOG0067161,0.462570,0.050010,9.249622,2.252871e-20,2.695110e-16,NaN,NaN,NaN
1,N5.HOG0062479,0.283759,0.032246,8.799725,1.371518e-18,1.640747e-14,129224049,-,zygotic DNA replication licensing factor mcm3-...
2,N5.HOG0068083,0.391135,0.045379,8.619335,6.734435e-18,8.056405e-14,129224240,GO:0006888 [Name: ER to Golgi vesicle-mediated...,trafficking protein particle complex subunit 4...
3,N5.HOG0068230,-0.274228,0.032937,-8.325893,8.369532e-17,1.001247e-12,129229571,GO:0005739 [Name: mitochondrion]; GO:0000287 [...,mitochondrial ribosome-associated GTPase 2-like
4,N5.HOG0030400,-1.144605,0.137932,-8.298313,1.056000e-16,1.263293e-12,129223000,GO:0005615 [Name: extracellular space],uncharacterized LOC129223000
...,...,...,...,...,...,...,...,...,...
332,N5.HOG0066701,-0.312257,0.067792,-4.606109,4.102731e-06,4.908098e-02,129230750,GO:0045454 [Name: cell redox homeostasis]; GO:...,thioredoxin reductase-like selenoprotein T hom...
333,N5.HOG0060348,-1.055627,0.229242,-4.604867,4.127303e-06,4.937492e-02,129231768,-,U-scoloptoxin(19)-Tl1a-like
334,N5.HOG0061162,0.314913,0.068417,4.602884,4.166809e-06,4.984754e-02,129233683,GO:0005689 [Name: U12-type spliceosomal comple...,U11/U12 small nuclear ribonucleoprotein 25 kDa...
335,N5.HOG0050233,-0.715788,0.155517,-4.602618,4.172129e-06,4.991118e-02,129217819,GO:0017171 [Name: serine hydrolase activity],lethal (2) k09913
336,N5.HOG0065991,-0.288436,0.062672,-4.602332,4.177865e-06,4.997980e-02,129222783,GO:0004721 [Name: phosphoprotein phosphatase a...,mitochondrial import inner membrane translocas...

In [54]:
phyloglm_df = get_ptep_description(phyloglm_locs_fltrd)
phyloglm_df = get_udiv_best_blast(phyloglm_df)
phyloglm_df.to_excel(os.path.join(repo_root, 'results/Supplementary_Table_7_PhyloGLM_hits.xlsx'), index=False)
phyloglm_df

,HOG,Orb-weaving coefficient estimate,Orb-weaving coefficient standard error,Orb-weaving coefficient z-value,Orb-weaving coefficient p-value,p_adj_bonferroni,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit LOC,P. tepidariorum best BLAST hit description,U. diversus best BLAST hit LOC,U. diversus best BLAST hit description
0,N5.HOG0067161,0.462570,0.050010,9.249622,2.252871e-20,2.695110e-16,NaN,NaN,NaN,LOC107443813,electron transfer flavoprotein subunit beta,NO_HIT,NO_HIT
1,N5.HOG0062479,0.283759,0.032246,8.799725,1.371518e-18,1.640747e-14,129224049,-,zygotic DNA replication licensing factor mcm3-...,LOC107438264,zygotic DNA replication licensing factor mcm3 ...,LOC129218073,LOW QUALITY PROTEIN: zygotic DNA replication l...
2,N5.HOG0068083,0.391135,0.045379,8.619335,6.734435e-18,8.056405e-14,129224240,GO:0006888 [Name: ER to Golgi vesicle-mediated...,trafficking protein particle complex subunit 4...,LOC107438798,trafficking protein particle complex subunit 4,LOC129224240,trafficking protein particle complex subunit 4...
3,N5.HOG0068230,-0.274228,0.032937,-8.325893,8.369532e-17,1.001247e-12,129229571,GO:0005739 [Name: mitochondrion]; GO:0000287 [...,mitochondrial ribosome-associated GTPase 2-like,LOC107454111,mitochondrial ribosome-associated GTPase 2,LOC129229571,mitochondrial ribosome-associated GTPase 2-like
4,N5.HOG0030400,-1.144605,0.137932,-8.298313,1.056000e-16,1.263293e-12,129223000,GO:0005615 [Name: extracellular space],uncharacterized LOC129223000,LOC107442673,uncharacterized protein,LOC129223000,uncharacterized protein LOC129223000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
332,N5.HOG0066701,-0.312257,0.067792,-4.606109,4.102731e-06,4.908098e-02,129230750,GO:0045454 [Name: cell redox homeostasis]; GO:...,thioredoxin reductase-like selenoprotein T hom...,LOC122271094,LOW QUALITY PROTEIN: thioredoxin reductase-lik...,LOC129230750,LOW QUALITY PROTEIN: thioredoxin reductase-lik...
333,N5.HOG0060348,-1.055627,0.229242,-4.604867,4.127303e-06,4.937492e-02,129231768,-,U-scoloptoxin(19)-Tl1a-like,LOC107448937,U-scoloptoxin(19)-Tl1a isoform X1,LOC129231768,U-scoloptoxin(19)-Tl1a-like
334,N5.HOG0061162,0.314913,0.068417,4.602884,4.166809e-06,4.984754e-02,129233683,GO:0005689 [Name: U12-type spliceosomal comple...,U11/U12 small nuclear ribonucleoprotein 25 kDa...,LOC107444085,U11/U12 small nuclear ribonucleoprotein 25 kDa...,LOC129233683,U11/U12 small nuclear ribonucleoprotein 25 kDa...
335,N5.HOG0050233,-0.715788,0.155517,-4.602618,4.172129e-06,4.991118e-02,129217819,GO:0017171 [Name: serine hydrolase activity],lethal (2) k09913,LOC107446798,uncharacterized protein isoform X1,LOC129217819,transmembrane protein 53-like
336,N5.HOG0065991,-0.288436,0.062672,-4.602332,4.177865e-06,4.997980e-02,129222783,GO:0004721 [Name: phosphoprotein phosphatase a...,mitochondrial import inner membrane translocas...,LOC107442742,mitochondrial import inner membrane translocas...,LOC129222783,mitochondrial import inner membrane translocas...

In [55]:
previous_interesting_pglm_df = phyloglm_df[phyloglm_df['HOG'].isin(previous_interesting['HOG'])]
previous_interesting_pglm_df

,HOG,Orb-weaving coefficient estimate,Orb-weaving coefficient standard error,Orb-weaving coefficient z-value,Orb-weaving coefficient p-value,p_adj_bonferroni,U. diversus gene ID,U. diversus GO terms,U. diversus gene description,P. tepidariorum best BLAST hit LOC,P. tepidariorum best BLAST hit description,U. diversus best BLAST hit LOC,U. diversus best BLAST hit description
253,N5.HOG0064389,0.472255,0.097118,4.862688,0.000001,0.013853,129233173,GO:0008254 [Name: 3'-nucleotidase activity]; G...,inositol monophosphatase 3-like,LOC107438486,inositol monophosphatase 3,LOC129233272,inositol monophosphatase 3-like
306,N5.HOG0059007,-0.435067,0.092856,-4.685398,0.000003,0.033427,129222006,GO:0003712 [Name: transcription cofactor activ...,G protein pathway suppressor 2-like,LOC107443620,G protein pathway suppressor 2,LOC129222006,G protein pathway suppressor 2-like